// lib/classic/lobby-copy.ts — filone «classic», lobby (#CLASSIC-LOBBY-1008)
//
// Le stringhe NUOVE della lobby classic, nelle 11 lingue del sito (le due di
// BASE_TRANSLATIONS — en, it — più le nove di lib/i18n/extra-locales.ts).
// Stanno qui e non in `TRANSLATIONS` del monolite perché la lobby classic
// vive dietro un flag di build: a flag spento il dizionario del sito resta
// byte per byte quello di main. Il test di parità (lobby-copy.test.ts) tiene
// le 11 tabelle allineate; una lingua sconosciuta ricade sull'inglese.
//
// Lessico: niente bonus, urgenza, scarsità, «tips», «lock», «guaranteed».
// Titoli banner ≤ 6 parole, sottotitoli ≤ 12 (anche questo è nel test).

export const CLASSIC_LANGS = ["en", "it", "es", "fr", "de", "pt", "nl", "pl", "tr", "sv", "ru"] as const;
export type ClassicLang = (typeof CLASSIC_LANGS)[number];

export type ClassicCopy = {
  bannersLabel: string;
  b1Title: string; b1Sub: string; b1Cta: string;
  b2Title: string; b2Sub: string; b2Cta: string;
  b3Title: string; b3Sub: string; b3Cta: string;
  /** #CLASSIC-INT-1008 — il secondo link del banner «record»: /tools. */
  b3Tools: string;
  tabsLabel: string;
  tabFeatured: string; tabInPlay: string; tabSoon: string; tabAll: string;
  searchLabel: string; searchPlaceholder: string; clearSearch: string;
  sportsLabel: string; popular: string; football: string; tennis: string;
  featuredTitle: string; featuredHint: string; prev: string; next: string;
  differsTitle: string; differsHint: string;
  leaguesTitle: string; leaguesHint: string; timesIn: string;
  filterLabel: string; fAll: string; fLive: string; fToday: string; fTomorrow: string;
  matchesN: string; liveN: string;
  moreInAll: string; seeAllSports: string;
  emptyLive: string; emptySoon: string; emptySearch: string; emptyFilter: string; loading: string;
  england: string; scotland: string; international: string;
  otherLeagues: string; otherTournaments: string;
};

const en: ClassicCopy = {
  bannersLabel: "Where to start",
  b1Title: "Today’s football board",
  b1Sub: "Every match we cover today, with our estimate.",
  b1Cta: "Open the board",
  b2Title: "Live now",
  b2Sub: "Live scores and our estimate, match by match.",
  b2Cta: "See live matches",
  b3Title: "Our track record",
  b3Sub: "Won or lost, every reading is public.",
  b3Cta: "See the record",
  b3Tools: "Free tools",
  tabsLabel: "Browse matches",
  tabFeatured: "Featured", tabInPlay: "In-Play", tabSoon: "Starting Soon", tabAll: "All Sports",
  searchLabel: "Search matches", searchPlaceholder: "Team, player or league", clearSearch: "Clear search",
  sportsLabel: "Sports", popular: "Popular", football: "Football", tennis: "Tennis",
  featuredTitle: "Featured matches",
  featuredHint: "Matches in play first, then the next kick-offs in the top leagues.",
  prev: "Previous matches", next: "Next matches",
  differsTitle: "Where our estimate differs most",
  differsHint: "Matches not yet started where our estimate and the market are furthest apart. Gaps beyond 15 points are left out.",
  leaguesTitle: "Matches by league",
  leaguesHint: "Top leagues first, then by kick-off time.",
  timesIn: "Times in {tz}",
  filterLabel: "When", fAll: "All", fLive: "Live", fToday: "Today", fTomorrow: "Tomorrow",
  matchesN: "Matches: {n}", liveN: "{n} live",
  moreInAll: "Showing the top leagues. {n} more in other leagues.", seeAllSports: "Show all sports",
  emptyLive: "No matches in play right now.",
  emptySoon: "Nothing kicks off in the next three hours.",
  emptySearch: "No match for “{q}”.",
  emptyFilter: "No matches for this filter.",
  loading: "Loading today’s board…",
  england: "England", scotland: "Scotland", international: "International",
  otherLeagues: "Other leagues", otherTournaments: "Other tournaments",
};

const it: ClassicCopy = {
  bannersLabel: "Da dove partire",
  b1Title: "Il board del calcio oggi",
  b1Sub: "Ogni partita che copriamo oggi, con la nostra stima.",
  b1Cta: "Apri il board",
  b2Title: "In corso ora",
  b2Sub: "Punteggi live e la nostra stima, partita per partita.",
  b2Cta: "Vedi le partite live",
  b3Title: "Il nostro storico",
  b3Sub: "Vinta o persa, ogni lettura è pubblica.",
  b3Cta: "Vedi lo storico",
  b3Tools: "Strumenti gratuiti",
  tabsLabel: "Sfoglia le partite",
  tabFeatured: "In evidenza", tabInPlay: "In gioco", tabSoon: "A breve", tabAll: "Tutti gli sport",
  searchLabel: "Cerca partite", searchPlaceholder: "Squadra, giocatore o lega", clearSearch: "Cancella ricerca",
  sportsLabel: "Sport", popular: "Popolari", football: "Calcio", tennis: "Tennis",
  featuredTitle: "Partite in evidenza",
  featuredHint: "Prima le partite in gioco, poi i prossimi calci d’inizio delle leghe top.",
  prev: "Partite precedenti", next: "Partite successive",
  differsTitle: "Dove la nostra stima si discosta di più",
  differsHint: "Partite non ancora iniziate dove la nostra stima e il mercato sono più lontani. Oltre 15 punti di scarto restano fuori.",
  leaguesTitle: "Partite per lega",
  leaguesHint: "Prima le leghe top, poi per orario di inizio.",
  timesIn: "Orari in {tz}",
  filterLabel: "Quando", fAll: "Tutte", fLive: "Live", fToday: "Oggi", fTomorrow: "Domani",
  matchesN: "Partite: {n}", liveN: "{n} live",
  moreInAll: "Stai vedendo le leghe top. Altre {n} nelle altre leghe.", seeAllSports: "Mostra tutti gli sport",
  emptyLive: "Nessuna partita in gioco adesso.",
  emptySoon: "Nessun inizio nelle prossime tre ore.",
  emptySearch: "Nessuna partita per «{q}».",
  emptyFilter: "Nessuna partita per questo filtro.",
  loading: "Carico il board di oggi…",
  england: "Inghilterra", scotland: "Scozia", international: "Internazionale",
  otherLeagues: "Altre leghe", otherTournaments: "Altri tornei",
};

const es: ClassicCopy = {
  bannersLabel: "Por dónde empezar",
  b1Title: "El board de fútbol de hoy",
  b1Sub: "Cada partido que cubrimos hoy, con estimación.",
  b1Cta: "Abrir el board",
  b2Title: "En vivo ahora",
  b2Sub: "Marcadores en vivo y nuestra estimación.",
  b2Cta: "Ver partidos en vivo",
  b3Title: "Nuestro historial",
  b3Sub: "Ganada o perdida, cada lectura es pública.",
  b3Cta: "Ver el historial",
  b3Tools: "Herramientas",
  tabsLabel: "Explorar partidos",
  tabFeatured: "Destacados", tabInPlay: "En juego", tabSoon: "Empiezan pronto", tabAll: "Todos los deportes",
  searchLabel: "Buscar partidos", searchPlaceholder: "Equipo, jugador o liga", clearSearch: "Borrar búsqueda",
  sportsLabel: "Deportes", popular: "Populares", football: "Fútbol", tennis: "Tenis",
  featuredTitle: "Partidos destacados",
  featuredHint: "Primero los partidos en juego, luego los próximos inicios de las ligas top.",
  prev: "Partidos anteriores", next: "Partidos siguientes",
  differsTitle: "Donde nuestra estimación más difiere",
  differsHint: "Partidos sin empezar donde nuestra estimación y el mercado están más lejos. Las diferencias de más de 15 puntos quedan fuera.",
  leaguesTitle: "Partidos por liga",
  leaguesHint: "Primero las ligas top, luego por hora de inicio.",
  timesIn: "Horas en {tz}",
  filterLabel: "Cuándo", fAll: "Todos", fLive: "En vivo", fToday: "Hoy", fTomorrow: "Mañana",
  matchesN: "Partidos: {n}", liveN: "{n} en vivo",
  moreInAll: "Ves las ligas top. {n} más en otras ligas.", seeAllSports: "Ver todos los deportes",
  emptyLive: "Ningún partido en juego ahora.",
  emptySoon: "Nada empieza en las próximas tres horas.",
  emptySearch: "Ningún partido para «{q}».",
  emptyFilter: "Ningún partido con este filtro.",
  loading: "Cargando el board de hoy…",
  england: "Inglaterra", scotland: "Escocia", international: "Internacional",
  otherLeagues: "Otras ligas", otherTournaments: "Otros torneos",
};

const fr: ClassicCopy = {
  bannersLabel: "Par où commencer",
  b1Title: "Le board football du jour",
  b1Sub: "Chaque match couvert aujourd’hui, avec estimation.",
  b1Cta: "Ouvrir le board",
  b2Title: "En direct",
  b2Sub: "Scores en direct et notre estimation.",
  b2Cta: "Voir les matchs en direct",
  b3Title: "Notre historique",
  b3Sub: "Gagnée ou perdue, chaque lecture est publique.",
  b3Cta: "Voir l’historique",
  b3Tools: "Outils gratuits",
  tabsLabel: "Parcourir les matchs",
  tabFeatured: "À la une", tabInPlay: "En cours", tabSoon: "Bientôt", tabAll: "Tous les sports",
  searchLabel: "Rechercher des matchs", searchPlaceholder: "Équipe, joueur ou ligue", clearSearch: "Effacer la recherche",
  sportsLabel: "Sports", popular: "Populaires", football: "Football", tennis: "Tennis",
  featuredTitle: "Matchs à la une",
  featuredHint: "D’abord les matchs en cours, puis les prochains coups d’envoi des grandes ligues.",
  prev: "Matchs précédents", next: "Matchs suivants",
  differsTitle: "Là où notre estimation diffère le plus",
  differsHint: "Matchs pas encore commencés où notre estimation et le marché sont les plus éloignés. Les écarts de plus de 15 points sont exclus.",
  leaguesTitle: "Matchs par ligue",
  leaguesHint: "Les grandes ligues d’abord, puis par heure de début.",
  timesIn: "Heures en {tz}",
  filterLabel: "Quand", fAll: "Tous", fLive: "Direct", fToday: "Aujourd’hui", fTomorrow: "Demain",
  matchesN: "Matchs : {n}", liveN: "{n} en direct",
  moreInAll: "Vous voyez les grandes ligues. {n} de plus dans les autres ligues.", seeAllSports: "Voir tous les sports",
  emptyLive: "Aucun match en cours.",
  emptySoon: "Rien ne commence dans les trois prochaines heures.",
  emptySearch: "Aucun match pour « {q} ».",
  emptyFilter: "Aucun match pour ce filtre.",
  loading: "Chargement du board du jour…",
  england: "Angleterre", scotland: "Écosse", international: "International",
  otherLeagues: "Autres ligues", otherTournaments: "Autres tournois",
};

const de: ClassicCopy = {
  bannersLabel: "Wo du anfängst",
  b1Title: "Das Fußball-Board von heute",
  b1Sub: "Jedes Spiel, das wir heute abdecken, mit Schätzung.",
  b1Cta: "Board öffnen",
  b2Title: "Jetzt live",
  b2Sub: "Live-Spielstände und unsere Schätzung.",
  b2Cta: "Live-Spiele ansehen",
  b3Title: "Unsere Bilanz",
  b3Sub: "Gewonnen oder verloren: alles öffentlich.",
  b3Cta: "Bilanz ansehen",
  b3Tools: "Kostenlose Tools",
  tabsLabel: "Spiele durchsuchen",
  tabFeatured: "Empfohlen", tabInPlay: "Laufend", tabSoon: "Beginnt bald", tabAll: "Alle Sportarten",
  searchLabel: "Spiele suchen", searchPlaceholder: "Team, Spieler oder Liga", clearSearch: "Suche löschen",
  sportsLabel: "Sportarten", popular: "Beliebt", football: "Fußball", tennis: "Tennis",
  featuredTitle: "Ausgewählte Spiele",
  featuredHint: "Zuerst laufende Spiele, dann die nächsten Anstöße der Top-Ligen.",
  prev: "Vorherige Spiele", next: "Nächste Spiele",
  differsTitle: "Wo unsere Schätzung am stärksten abweicht",
  differsHint: "Noch nicht begonnene Spiele, bei denen unsere Schätzung und der Markt am weitesten auseinanderliegen. Abstände über 15 Punkte bleiben draußen.",
  leaguesTitle: "Spiele nach Liga",
  leaguesHint: "Zuerst die Top-Ligen, dann nach Anstoßzeit.",
  timesIn: "Zeiten in {tz}",
  filterLabel: "Wann", fAll: "Alle", fLive: "Live", fToday: "Heute", fTomorrow: "Morgen",
  matchesN: "Spiele: {n}", liveN: "{n} live",
  moreInAll: "Du siehst die Top-Ligen. {n} weitere in anderen Ligen.", seeAllSports: "Alle Sportarten zeigen",
  emptyLive: "Gerade läuft kein Spiel.",
  emptySoon: "In den nächsten drei Stunden beginnt nichts.",
  emptySearch: "Kein Spiel für „{q}“.",
  emptyFilter: "Keine Spiele für diesen Filter.",
  loading: "Das heutige Board wird geladen…",
  england: "England", scotland: "Schottland", international: "International",
  otherLeagues: "Weitere Ligen", otherTournaments: "Weitere Turniere",
};

const pt: ClassicCopy = {
  bannersLabel: "Por onde começar",
  b1Title: "O board de futebol de hoje",
  b1Sub: "Cada jogo que cobrimos hoje, com estimativa.",
  b1Cta: "Abrir o board",
  b2Title: "Ao vivo agora",
  b2Sub: "Resultados ao vivo e a nossa estimativa.",
  b2Cta: "Ver jogos ao vivo",
  b3Title: "O nosso histórico",
  b3Sub: "Ganha ou perdida, cada leitura é pública.",
  b3Cta: "Ver o histórico",
  b3Tools: "Ferramentas grátis",
  tabsLabel: "Explorar jogos",
  tabFeatured: "Destaques", tabInPlay: "Em jogo", tabSoon: "Começam em breve", tabAll: "Todos os desportos",
  searchLabel: "Pesquisar jogos", searchPlaceholder: "Equipa, jogador ou liga", clearSearch: "Limpar pesquisa",
  sportsLabel: "Desportos", popular: "Populares", football: "Futebol", tennis: "Ténis",
  featuredTitle: "Jogos em destaque",
  featuredHint: "Primeiro os jogos em curso, depois os próximos inícios das ligas principais.",
  prev: "Jogos anteriores", next: "Jogos seguintes",
  differsTitle: "Onde a nossa estimativa mais difere",
  differsHint: "Jogos ainda por começar onde a nossa estimativa e o mercado estão mais distantes. Diferenças acima de 15 pontos ficam de fora.",
  leaguesTitle: "Jogos por liga",
  leaguesHint: "Primeiro as ligas principais, depois por hora de início.",
  timesIn: "Horas em {tz}",
  filterLabel: "Quando", fAll: "Todos", fLive: "Ao vivo", fToday: "Hoje", fTomorrow: "Amanhã",
  matchesN: "Jogos: {n}", liveN: "{n} ao vivo",
  moreInAll: "Estás a ver as ligas principais. Mais {n} noutras ligas.", seeAllSports: "Ver todos os desportos",
  emptyLive: "Nenhum jogo em curso agora.",
  emptySoon: "Nada começa nas próximas três horas.",
  emptySearch: "Nenhum jogo para «{q}».",
  emptyFilter: "Nenhum jogo para este filtro.",
  loading: "A carregar o board de hoje…",
  england: "Inglaterra", scotland: "Escócia", international: "Internacional",
  otherLeagues: "Outras ligas", otherTournaments: "Outros torneios",
};

const nl: ClassicCopy = {
  bannersLabel: "Waar je begint",
  b1Title: "Het voetbalboard van vandaag",
  b1Sub: "Elke wedstrijd die we vandaag volgen, met schatting.",
  b1Cta: "Open het board",
  b2Title: "Nu live",
  b2Sub: "Livescores en onze schatting per wedstrijd.",
  b2Cta: "Bekijk live wedstrijden",
  b3Title: "Ons trackrecord",
  b3Sub: "Gewonnen of verloren: alles openbaar.",
  b3Cta: "Bekijk het record",
  b3Tools: "Gratis tools",
  tabsLabel: "Wedstrijden bekijken",
  tabFeatured: "Uitgelicht", tabInPlay: "Bezig", tabSoon: "Begint zo", tabAll: "Alle sporten",
  searchLabel: "Wedstrijden zoeken", searchPlaceholder: "Team, speler of competitie", clearSearch: "Zoekopdracht wissen",
  sportsLabel: "Sporten", popular: "Populair", football: "Voetbal", tennis: "Tennis",
  featuredTitle: "Uitgelichte wedstrijden",
  featuredHint: "Eerst wedstrijden die bezig zijn, dan de volgende aftrappen in de topcompetities.",
  prev: "Vorige wedstrijden", next: "Volgende wedstrijden",
  differsTitle: "Waar onze schatting het meest afwijkt",
  differsHint: "Nog niet begonnen wedstrijden waar onze schatting en de markt het verst uit elkaar liggen. Verschillen boven 15 punten vallen weg.",
  leaguesTitle: "Wedstrijden per competitie",
  leaguesHint: "Eerst de topcompetities, dan op aftraptijd.",
  timesIn: "Tijden in {tz}",
  filterLabel: "Wanneer", fAll: "Alle", fLive: "Live", fToday: "Vandaag", fTomorrow: "Morgen",
  matchesN: "Wedstrijden: {n}", liveN: "{n} live",
  moreInAll: "Je ziet de topcompetities. Nog {n} in andere competities.", seeAllSports: "Alle sporten tonen",
  emptyLive: "Er is nu geen wedstrijd bezig.",
  emptySoon: "In de komende drie uur begint er niets.",
  emptySearch: "Geen wedstrijd voor ‘{q}’.",
  emptyFilter: "Geen wedstrijden voor dit filter.",
  loading: "Board van vandaag laden…",
  england: "Engeland", scotland: "Schotland", international: "Internationaal",
  otherLeagues: "Overige competities", otherTournaments: "Overige toernooien",
};

const pl: ClassicCopy = {
  bannersLabel: "Od czego zacząć",
  b1Title: "Dzisiejszy board piłkarski",
  b1Sub: "Każdy mecz, który dziś analizujemy, z oceną.",
  b1Cta: "Otwórz board",
  b2Title: "Teraz na żywo",
  b2Sub: "Wyniki na żywo i nasza ocena.",
  b2Cta: "Zobacz mecze na żywo",
  b3Title: "Nasza historia wyników",
  b3Sub: "Wygrane i przegrane: wszystko publicznie.",
  b3Cta: "Zobacz historię",
  b3Tools: "Darmowe narzędzia",
  tabsLabel: "Przeglądaj mecze",
  tabFeatured: "Wyróżnione", tabInPlay: "W trakcie", tabSoon: "Wkrótce", tabAll: "Wszystkie sporty",
  searchLabel: "Szukaj meczów", searchPlaceholder: "Drużyna, zawodnik lub liga", clearSearch: "Wyczyść wyszukiwanie",
  sportsLabel: "Sporty", popular: "Popularne", football: "Piłka nożna", tennis: "Tenis",
  featuredTitle: "Wyróżnione mecze",
  featuredHint: "Najpierw mecze w trakcie, potem najbliższe rozpoczęcia w czołowych ligach.",
  prev: "Poprzednie mecze", next: "Następne mecze",
  differsTitle: "Gdzie nasza ocena różni się najbardziej",
  differsHint: "Mecze, które jeszcze się nie zaczęły, gdzie nasza ocena i rynek są najdalej od siebie. Różnice powyżej 15 punktów są pomijane.",
  leaguesTitle: "Mecze według ligi",
  leaguesHint: "Najpierw czołowe ligi, potem według godziny rozpoczęcia.",
  timesIn: "Godziny: {tz}",
  filterLabel: "Kiedy", fAll: "Wszystkie", fLive: "Na żywo", fToday: "Dziś", fTomorrow: "Jutro",
  matchesN: "Mecze: {n}", liveN: "Na żywo: {n}",
  moreInAll: "Widzisz czołowe ligi. Pozostałe ligi: {n}.", seeAllSports: "Pokaż wszystkie sporty",
  emptyLive: "Teraz nie trwa żaden mecz.",
  emptySoon: "W ciągu najbliższych trzech godzin nic się nie zaczyna.",
  emptySearch: "Brak meczu dla „{q}”.",
  emptyFilter: "Brak meczów dla tego filtra.",
  loading: "Ładowanie dzisiejszego boardu…",
  england: "Anglia", scotland: "Szkocja", international: "Międzynarodowe",
  otherLeagues: "Inne ligi", otherTournaments: "Inne turnieje",
};

const tr: ClassicCopy = {
  bannersLabel: "Nereden başlamalı",
  b1Title: "Bugünün futbol board’u",
  b1Sub: "Bugün takip ettiğimiz her maç, tahminimizle.",
  b1Cta: "Board’u aç",
  b2Title: "Şimdi canlı",
  b2Sub: "Canlı skorlar ve tahminimiz.",
  b2Cta: "Canlı maçları gör",
  b3Title: "Geçmiş sonuçlarımız",
  b3Sub: "Kazanan da kaybeden de herkese açık.",
  b3Cta: "Sonuçları gör",
  b3Tools: "Ücretsiz araçlar",
  tabsLabel: "Maçlara göz at",
  tabFeatured: "Öne çıkanlar", tabInPlay: "Oynanıyor", tabSoon: "Yakında başlıyor", tabAll: "Tüm sporlar",
  searchLabel: "Maç ara", searchPlaceholder: "Takım, oyuncu veya lig", clearSearch: "Aramayı temizle",
  sportsLabel: "Sporlar", popular: "Popüler", football: "Futbol", tennis: "Tenis",
  featuredTitle: "Öne çıkan maçlar",
  featuredHint: "Önce oynanan maçlar, sonra üst liglerin sıradaki başlama saatleri.",
  prev: "Önceki maçlar", next: "Sonraki maçlar",
  differsTitle: "Tahminimizin en çok ayrıştığı yerler",
  differsHint: "Henüz başlamamış, tahminimizle piyasanın en uzak olduğu maçlar. 15 puanı aşan farklar dahil edilmez.",
  leaguesTitle: "Liglere göre maçlar",
  leaguesHint: "Önce üst ligler, sonra başlama saatine göre.",
  timesIn: "Saatler: {tz}",
  filterLabel: "Ne zaman", fAll: "Tümü", fLive: "Canlı", fToday: "Bugün", fTomorrow: "Yarın",
  matchesN: "Maç: {n}", liveN: "Canlı: {n}",
  moreInAll: "Üst ligleri görüyorsun. Diğer liglerde {n} maç daha.", seeAllSports: "Tüm sporları göster",
  emptyLive: "Şu anda oynanan maç yok.",
  emptySoon: "Önümüzdeki üç saatte başlayan maç yok.",
  emptySearch: "“{q}” için maç yok.",
  emptyFilter: "Bu filtre için maç yok.",
  loading: "Bugünün board’u yükleniyor…",
  england: "İngiltere", scotland: "İskoçya", international: "Uluslararası",
  otherLeagues: "Diğer ligler", otherTournaments: "Diğer turnuvalar",
};

const sv: ClassicCopy = {
  bannersLabel: "Var du börjar",
  b1Title: "Dagens fotbollsboard",
  b1Sub: "Varje match vi följer i dag, med uppskattning.",
  b1Cta: "Öppna boarden",
  b2Title: "Live nu",
  b2Sub: "Liveställningar och vår uppskattning.",
  b2Cta: "Se livematcher",
  b3Title: "Vår historik",
  b3Sub: "Vunnet eller förlorat: allt är öppet.",
  b3Cta: "Se historiken",
  b3Tools: "Gratis verktyg",
  tabsLabel: "Bläddra bland matcher",
  tabFeatured: "Utvalda", tabInPlay: "Pågår", tabSoon: "Börjar snart", tabAll: "Alla sporter",
  searchLabel: "Sök matcher", searchPlaceholder: "Lag, spelare eller liga", clearSearch: "Rensa sökning",
  sportsLabel: "Sporter", popular: "Populärt", football: "Fotboll", tennis: "Tennis",
  featuredTitle: "Utvalda matcher",
  featuredHint: "Först pågående matcher, sedan nästa avspark i toppligorna.",
  prev: "Föregående matcher", next: "Nästa matcher",
  differsTitle: "Där vår uppskattning skiljer sig mest",
  differsHint: "Matcher som inte har börjat där vår uppskattning och marknaden ligger längst ifrån varandra. Skillnader över 15 poäng tas inte med.",
  leaguesTitle: "Matcher per liga",
  leaguesHint: "Toppligorna först, sedan efter avsparkstid.",
  timesIn: "Tider i {tz}",
  filterLabel: "När", fAll: "Alla", fLive: "Live", fToday: "I dag", fTomorrow: "I morgon",
  matchesN: "Matcher: {n}", liveN: "{n} live",
  moreInAll: "Du ser toppligorna. {n} till i andra ligor.", seeAllSports: "Visa alla sporter",
  emptyLive: "Ingen match pågår just nu.",
  emptySoon: "Inget börjar inom de närmaste tre timmarna.",
  emptySearch: "Ingen match för ”{q}”.",
  emptyFilter: "Inga matcher för det här filtret.",
  loading: "Laddar dagens board…",
  england: "England", scotland: "Skottland", international: "Internationellt",
  otherLeagues: "Övriga ligor", otherTournaments: "Övriga turneringar",
};

const ru: ClassicCopy = {
  bannersLabel: "С чего начать",
  b1Title: "Футбольный борд на сегодня",
  b1Sub: "Наши матчи дня — с нашей оценкой.",
  b1Cta: "Открыть борд",
  b2Title: "Сейчас в игре",
  b2Sub: "Счёт в игре и наша оценка.",
  b2Cta: "Смотреть лайв",
  b3Title: "Наша история",
  b3Sub: "Открыто всё, включая проигрыши.",
  b3Cta: "К истории",
  b3Tools: "Инструменты",
  tabsLabel: "Просмотр матчей",
  tabFeatured: "Избранное", tabInPlay: "В игре", tabSoon: "Скоро начало", tabAll: "Все виды спорта",
  searchLabel: "Поиск матчей", searchPlaceholder: "Команда, игрок или лига", clearSearch: "Очистить поиск",
  sportsLabel: "Виды спорта", popular: "Популярное", football: "Футбол", tennis: "Теннис",
  featuredTitle: "Избранные матчи",
  featuredHint: "Сначала матчи в игре, затем ближайшие начала в топ-лигах.",
  prev: "Предыдущие матчи", next: "Следующие матчи",
  differsTitle: "Где наша оценка расходится сильнее всего",
  differsHint: "Ещё не начавшиеся матчи, где наша оценка и рынок дальше всего друг от друга. Разрывы больше 15 пунктов исключены.",
  leaguesTitle: "Матчи по лигам",
  leaguesHint: "Сначала топ-лиги, затем по времени начала.",
  timesIn: "Время: {tz}",
  filterLabel: "Когда", fAll: "Все", fLive: "Лайв", fToday: "Сегодня", fTomorrow: "Завтра",
  matchesN: "Матчей: {n}", liveN: "В игре: {n}",
  moreInAll: "Показаны топ-лиги. В других лигах ещё: {n}.", seeAllSports: "Показать все виды спорта",
  emptyLive: "Сейчас нет матчей в игре.",
  emptySoon: "В ближайшие три часа ничего не начинается.",
  emptySearch: "Нет матчей по запросу «{q}».",
  emptyFilter: "Нет матчей для этого фильтра.",
  loading: "Загружаем сегодняшний борд…",
  england: "Англия", scotland: "Шотландия", international: "Международные",
  otherLeagues: "Другие лиги", otherTournaments: "Другие турниры",
};

export const CLASSIC_COPY: Record<ClassicLang, ClassicCopy> = { en, it, es, fr, de, pt, nl, pl, tr, sv, ru };

/** Lingua sconosciuta → inglese (fallback dichiarato). */
export function classicCopy(lang: string): ClassicCopy {
  return (CLASSIC_COPY as Record<string, ClassicCopy>)[lang] ?? en;
}

/** Sostituisce i segnaposto `{nome}`. */
export function fill(s: string, vars: Record<string, string | number>): string {
  return s.replace(/\{(\w+)\}/g, (m, k: string) => (k in vars ? String(vars[k]) : m));
}
