#!/bin/bash
# Prompt 02 — mockup del redesign v6 via gptimg (Codex image-gen), UNA chiamata alla volta,
# sempre con </dev/null (vedi ~/.claude/agents/art-director.md, bug noto 05-06/10).
# Uso: bash 02-mockups.sh [nome]   → senza argomento genera tutti; con nome genera solo quello.
# I NUMERI NEI PROMPT SONO SEGNAPOSTO DI LAYOUT, non dati: non vanno mai copiati nel codice.
set -u
OUT="$(cd "$(dirname "$0")/.." && pwd)/mockups"
mkdir -p "$OUT"
ONLY="${1:-}"

LIGHT='Mockup UI ad alta fedeltà di una web app dashboard interna per un analista dati, reso come screenshot nitido, piatto, frontale, senza prospettiva, senza cornice del browser, senza device. Tema chiaro "carta": sfondo pagina #F3EDDC, pannelli #FFFCF4 con bordo sottile #E9E1CC, testo inchiostro #14171C, testo secondario grigio #4A515B. Accento azione blu royal #144BD6 usato SOLO per la tab attiva e i link. Tipografia: titoli di sezione in maiuscolo in un grotesque condensato pesante (stile Big Shoulders), testo e numeri in un sans neutro (stile Archivo), numeri grandi condensati e tabulari. I chip di stato hanno SEMPRE icona + etichetta: "● Contato" verde scuro #1E7F5C su fondo verde chiarissimo; "◐ Proxy" blu #0E6FA8 su azzurro chiarissimo; "≈ Stimato" verde oliva #4C7A00 su giallo-lime chiarissimo; "△ Errore" rosso #B42318 su rosa chiarissimo; un dato mancante non ha MAI un numero né un trattino: compare solo come riga di testo "non misurato" con un lucchetto. Marcatore di anomalia: triangolo pieno ambra scuro #8A5A00. Niente glow, niente gradienti, niente ombre pesanti, niente illustrazioni, niente icone decorative, niente grafici a torta: densità da strumento professionale, griglia a 12 colonne, margini 24px, angoli 8px, spaziatura verticale regolare. Lingua interfaccia: italiano. In alto a sinistra solo la parola "BetRedge" scritta in nero come wordmark testuale semplice (nessun simbolo, nessun logo inventato) seguita da una piccola pill "GROWTH".'

DARK='Mockup UI ad alta fedeltà di una web app dashboard interna per un analista dati, reso come screenshot nitido, piatto, frontale, senza prospettiva, senza cornice del browser, senza device. Tema scuro navy: sfondo pagina #071329, pannelli #0D2343 con bordo sottile azzurro al 20% di opacità, testo #EDEFF2, testo secondario #A8BDD6. Accento azione blu royal #145AFF usato SOLO per la tab attiva, link in azzurro #6EA4FF. Tipografia: titoli di sezione in maiuscolo in un grotesque condensato pesante (stile Big Shoulders), testo e numeri in un sans neutro (stile Archivo), numeri grandi condensati e tabulari. I chip di stato hanno SEMPRE icona + etichetta: "● Contato" verde #34D399; "◐ Proxy" azzurro #81D9FF; "≈ Stimato" lime #D3FE50; "△ Errore" rosso #F87171; tutti come testo colorato su fondo scuro con bordo sottile dello stesso colore; un dato mancante non ha MAI un numero né un trattino: compare solo come riga di testo "non misurato" con un lucchetto. Marcatore di anomalia: triangolo pieno giallo #FFE818. Niente glow, niente gradienti, niente ombre, niente illustrazioni, niente icone decorative, niente grafici a torta: densità da strumento professionale, griglia a 12 colonne, margini 24px, angoli 8px. Lingua interfaccia: italiano. In alto a sinistra solo la parola "BetRedge" in bianco come wordmark testuale semplice (nessun simbolo, nessun logo inventato) seguita da una piccola pill "GROWTH".'

P_HOME='Layout desktop largo 1440px, formato orizzontale, la pagina continua sotto con un taglio pulito. Righe dall'"'"'alto: (1) barra superiore alta 56px: wordmark + pill GROWTH a sinistra; al centro un segmented control "Oggi | 7 giorni | 30 giorni" con "Oggi" attivo; a destra il testo piccolo "Letto alle 13:10 (Roma) · ricarica" e un link "Lavoro · 13 aperti →". (2) Blocco hero con titolo condensato "OGGI IN 30 SECONDI", diviso in due colonne. Colonna sinistra (7/12) intitolata "Cosa è cambiato" con 4 righe, ognuna con nome della metrica, numero grande, delta con freccia e la dicitura "vs media 14 giorni", e un chip di stato: "Page view probabilmente umani · 31 · ▲ +2,8σ · ≈ Stimato", "Sessioni con consenso · 6 · ▼ −40% · ◐ Proxy", "Signup completati · 2 · ▲ +1 · ● Contato", "Errori client · 0 · = · ● Contato". Colonna destra (5/12): pannello con bordo sinistro spesso ambra intitolato "Non fidarti di" con due avvisi in elenco: "92% dei page view di oggi è senza paese (649 su 702): leggi la riga Stimato, non i grezzi" e "Conteggi delle fasi: unità diverse per passo, nessuna conversione calcolabile"; in fondo al pannello una riga piccola "2 anomalie oggi · 17 KPI non misurati →". (3) Riga "CONTEGGI DELLE FASI · unità diverse, utenti non collegati" con il chip "◐ Proxy" accanto al titolo; quattro colonne affiancate SENZA frecce e SENZA percentuali di conversione, separate solo da linee verticali sottili: "Visitatori 6", "Signup avviati 8", "Profili creati 0", "Ordini pagati 0"; sotto ogni numero l'"'"'unità in piccolo ("sessioni con consenso", "eventi signup_started", "righe profiles", "ordini pagati"); sotto, una riga collassata "Perché non è un funnel ▸". (4) Riga "KPI PRINCIPALI" con 6 card in una riga: "Page view probabilmente umani 31 ≈ Stimato" con accanto, più piccolo nella stessa card, "grezzi 702 ● Contato"; "Sessioni con consenso 6 ◐ Proxy"; "Signup completati 2 ● Contato"; "Nuovi profili 0 ● Contato"; "Paganti verificati 4 ● Contato"; "Incassato 30 giorni $0,00 ● Contato". Ogni card: etichetta piccola, numero molto grande, delta piccolo, chip, link "perché ▸". (5) Riga "FONTI" con due tabelle compatte affiancate: "Ingressi per fonte" (righe: referrer:google.com 3 · ig 1 · interni, esclusi 0) e "Sessioni per fonte" (riga: (nessuna fonte) 6), ogni riga con una mini sparkline a destra.'

P_HOME_MOBILE='Layout mobile stretto 390px, formato verticale, schermata singola che continua sotto con taglio pulito. Una sola colonna, margini 16px. Dall'"'"'alto: barra con wordmark + pill GROWTH e a destra un link "Lavoro · 13"; sotto un segmented control a tutta larghezza "Oggi | 7 giorni | 30 giorni" con "Oggi" attivo; riga piccola "Letto alle 13:10 (Roma) · ricarica"; titolo condensato "OGGI IN 30 SECONDI"; sottotitolo "Cosa è cambiato"; 4 righe compatte impilate, ciascuna con nome metrica a sinistra, numero grande a destra, sotto il delta con freccia "vs media 14 giorni" e il chip di stato: "Page view probabilmente umani 31 ▲ +2,8σ ≈ Stimato", "Sessioni con consenso 6 ▼ −40% ◐ Proxy", "Signup completati 2 ▲ +1 ● Contato", "Errori client 0 = ● Contato"; poi il pannello con bordo sinistro ambra "Non fidarti di" con l'"'"'avviso "92% dei page view di oggi è senza paese: leggi la riga Stimato, non i grezzi" e la riga piccola "2 anomalie · 17 KPI non misurati →"; poi "CONTEGGI DELLE FASI ◐ Proxy" con sottotitolo "unità diverse, utenti non collegati" come 4 righe etichetta/valore impilate, senza frecce né percentuali: "Visitatori · sessioni con consenso · 6", "Signup avviati · eventi · 8", "Profili creati · righe profiles · 0", "Ordini pagati · 0"; poi "KPI PRINCIPALI" come griglia a 2 colonne di card con numero grande e chip ("Page view probabilmente umani 31 ≈ Stimato / grezzi 702", "Sessioni con consenso 6 ◐ Proxy", "Signup completati 2 ● Contato", "Paganti verificati 4 ● Contato"). Testo mai sotto i 13px equivalenti, tutto dentro i margini.'

KPI='Layout desktop largo 1440px, formato orizzontale. Mostra la sezione KPI "ACQUISITION" della dashboard, con a sinistra una colonna di navigazione stretta (200px) e fissa con le voci: "Oggi", "Funnel", "Acquisition" (attiva, in blu royal), "Activation", "Revenue", "Retention", "Product Quality", "Andamento 30 giorni", "Dati che non abbiamo ancora · 17"; sotto, in piccolo, la legenda dei 4 chip con icona. Area principale: titolo condensato "ACQUISITION · da dove arrivano" con sottotitolo "Oggi · 31 probabilmente umani ≈ Stimato · 702 grezzi ● Contato". Riga "Principali": 2 card grandi affiancate: la prima "Page view probabilmente umani" con numero grandissimo "31", chip "≈ Stimato", e nella stessa card a destra, separato da una linea verticale, "grezzi 702 ● Contato" più piccolo, sotto una riga "esclusi: 649 senza paese · 22 da paesi senza sessioni · 0 in raffica"; la seconda "Sessioni con consenso" con numero "6", chip "◐ Proxy", riga "approssima le sessioni organiche · 97% dei page view senza session_id". Sotto, riga "Secondari" come tabella compatta a righe alte 44px con colonne: Metrica · Valore · Stato · Finestra · "perché": "Ingressi con fonte · 4 · ● Contato · Oggi · perché ▸", "Sessioni /tools · 1 · ◐ Proxy · Oggi · perché ▸", "Sessioni /predictions · 0 · ◐ Proxy · Oggi · perché ▸", "Nuovi signup con referral · 0 · ● Contato · Oggi · perché ▸"; la riga "Sessioni /tools" è espansa e mostra sotto, in un riquadro rientrato grigio chiaro, il testo "Sessioni con almeno un page_view su /tools* (anche con prefisso lingua). Solo traffico con consenso: 97% dei page view nella finestra non ha session_id e non è contato." e una riga "Serve: conteggio anche senza consenso (G13) · sblocca: Calde". Sotto, due tabelle affiancate "Ingressi per fonte" e "Sessioni per fonte" con sparkline. In fondo una riga in grigio con lucchetto: "Non misurato in questa sezione: CAC per canale → vedi Dati che non abbiamo ancora". Nessuna card vuota, nessun trattino al posto di un numero.'

MISSING='Layout desktop largo 1440px, formato orizzontale. Mostra la sezione "DATI CHE NON ABBIAMO ANCORA · 17 KPI" della dashboard, con la stessa colonna di navigazione a sinistra (voce attiva "Dati che non abbiamo ancora"). Sottotitolo: "Nessuno di questi ha un numero: non sono 0, non sono trattini. Ogni riga dice cosa serve e chi lo sblocca." A destra in alto un piccolo riquadro di avanzamento "Gap di tracking: 1 di 13 chiusi" con una barra sottile e un link "Apri in Lavoro →". Il contenuto è una lista raggruppata per gap: ogni gruppo ha un'"'"'intestazione con id, titolo, pill di priorità e owner, es. "G01 · Nessun id utente stabile negli events · P0 · sblocca: Calde · aperto"; sotto, righe di KPI con icona lucchetto grigio, nome del KPI, la sezione a cui appartiene in grigio e la colonna "cosa serve": "🔒 WAA (utenti attivi settimanali) · Retention · id utente stabile negli events", "🔒 Retention D7 / D30 / M3 · Retention · id utente stabile", "🔒 Utenti di ritorno · Activation · id utente stabile". Secondo gruppo "G03 · Revenue senza importi utilizzabili · P0 · sblocca: Andrea · aperto" con righe "🔒 MRR · Revenue · importo + periodo + valuta per abbonamento", "🔒 ARPU · Revenue · dipende dall'"'"'MRR", "🔒 Revenue per canale · Revenue · importi normalizzati". Terzo gruppo "G06 · CAC: nessuna spesa marketing per canale · P1 · sblocca: Andrea" con righe "🔒 CAC per canale · Acquisition · tabella spesa per canale", "🔒 Payback · Revenue · CAC + MRR". Quarto gruppo "G09 · Latenza quote · P2 · sblocca: Calde" con riga "🔒 Latenza quote · Product Quality · timestamp della quota alla fonte". Le pill di priorità: P0 rosso scuro, P1 ambra scuro, P2 grigio. Niente numeri grandi in questa sezione, nessuna card: solo righe ordinate e leggibili.'

LAVORO='Layout desktop largo 1440px, formato orizzontale. Pagina "LAVORO GROWTH" (spazio di lavoro di un analista), tema e tipografia identici alla dashboard. Barra superiore con wordmark + pill GROWTH, a destra link "← Dashboard". Sotto il titolo condensato "LAVORO GROWTH", 4 riquadri di avanzamento affiancati che fungono da tab: "Tracking gaps · 1 di 13 chiusi" (attivo, bordo blu royal, con barra di avanzamento sottile), "Esperimenti · 2 in corso · 1 deciso", "Memo settimanale · settimana 41 · bozza", "Accessi e fonti · 3 di 17 concessi". Area principale divisa in due: a sinistra (8/12) la lista dei gap come righe alte con: id "G01" in grigio, titolo in grassetto "Nessun id utente stabile negli events", pill "P0" rosso scuro, "sblocca 4 KPI", owner "Calde", e a destra uno stepper a 3 passi "aperto · in corso · chiuso" con il passo corrente evidenziato; righe: G01 (P0, in corso), G02 "«Analisi» non definita né tracciata per utente" (P0, aperto), G03 "Revenue senza importi utilizzabili" (P0, aperto), G04 "Watchlist solo nel browser" (P2, aperto), G05 "Tag ?src= non distribuiti sui canali" (P1, in corso), G06 "CAC: nessuna spesa per canale" (P1, aperto). A destra (4/12) un pannello di dettaglio per G01 selezionato: titolo, descrizione "events ha solo session_id, che cambia a ogni tab/sessione ed esiste solo col consenso cookie", elenco "KPI sbloccati: WAA · Retention D7/D30/M3 · Utenti di ritorno · 3 analisi/settimana", "Owner: Calde", "Passi: 1. user_id hash negli events 2. backfill 30 giorni 3. verifica in dashboard", e in fondo una nota in grigio "Il contenuto si modifica in content/tracking-gaps.json con un commit". Sotto la lista, un'"'"'anteprima della tab Esperimenti come 3 colonne "Idea · In corso · Deciso" con 2 card per colonna, ognuna con titolo, ipotesi in una riga e un chip "scale" verde / "fix" ambra / "kill" grigio nella colonna Deciso.'

LAVORO_MOBILE='Layout mobile stretto 390px, formato verticale, una colonna, margini 16px. Pagina "LAVORO GROWTH". Barra con wordmark + pill GROWTH e link "← Dashboard"; titolo condensato "LAVORO GROWTH"; una fila orizzontale scorrevole di 4 chip di avanzamento: "Gap 1/13" (attiva, blu royal), "Esperimenti 2 in corso", "Memo sett. 41 · bozza", "Accessi 3/17"; sotto, la lista dei tracking gap come card impilate: ogni card ha in alto "G01 · P0" e lo stato "in corso" come chip, titolo in grassetto "Nessun id utente stabile negli events", una riga "sblocca 4 KPI · Calde", e una barra a 3 segmenti (aperto · in corso · chiuso) con i primi 2 pieni; poi G02 "«Analisi» non definita né tracciata per utente" (P0 · aperto), G03 "Revenue senza importi utilizzabili" (P0 · aperto), G05 "Tag ?src= non distribuiti sui canali" (P1 · in corso). Testo mai sotto i 13px equivalenti, tutto dentro i margini, nessuno scroll orizzontale a parte la fila di chip.'

STATES='Tavola di componenti (design system sheet) su fondo neutro, formato orizzontale, divisa in due metà: a sinistra tema chiaro carta (#F3EDDC), a destra tema scuro navy (#071329). In ogni metà, in alto, la "anatomia della card KPI" con callout numerati: 1 etichetta piccola in maiuscolo, 2 numero grande condensato tabulare, 3 chip di stato con icona, 4 delta con freccia e "vs media 14 giorni", 5 link "perché ▸" che apre il caveat. Sotto, una riga con le 5 varianti della card affiancate: "Contato" (chip ● verde, numero 702), "Proxy" (chip ◐ azzurro/blu, numero 6), "Stimato" (chip ≈ lime/oliva, numero 31 con accanto "grezzi 702 ● Contato" più piccolo), "Errore" (chip △ rosso, nessun numero, testo "Lettura fallita, nessun valore mostrato"), "Non misurato" (NON è una card: è una riga di testo con lucchetto "🔒 non misurato · cosa serve · chi sblocca" per far vedere che non occupa lo spazio di un dato). Sotto ancora, una riga "marcatori": triangolo pieno di anomalia con testo "▲ anomalia 22/09 · +5,0σ", pill di priorità "P0" "P1" "P2", stepper "aperto · in corso · chiuso", e un segmented control "Oggi | 7 giorni | 30 giorni". Tutte le etichette in italiano, con i codici colore scritti in piccolo sotto ogni chip. Nessuna illustrazione, nessun logo.'

run() { # nome, stile, contenuto
  local name="$1" style="$2" body="$3"
  if [ -n "$ONLY" ] && [ "$ONLY" != "$name" ]; then return; fi
  echo "== $name $(date +%H:%M:%S)"
  gptimg -r "$style $body" "$OUT/$name.png" </dev/null
  echo "rc=$?"
}

run home-desktop-light  "$LIGHT" "$P_HOME"
run home-desktop-dark   "$DARK"  "$P_HOME"
run home-mobile-light   "$LIGHT" "$P_HOME_MOBILE"
run kpi-section-light   "$LIGHT" "$KPI"
run missing-data-light  "$LIGHT" "$MISSING"
run lavoro-desktop-light "$LIGHT" "$LAVORO"
run lavoro-mobile-light "$LIGHT" "$LAVORO_MOBILE"
run states-sheet        "$LIGHT" "$STATES"
echo "== fine $(date +%H:%M:%S)"
