import { NextResponse } from "next/server";

export const dynamic = "force-dynamic";

const DB_URL = process.env.DATABASE_URL;

async function dbQuery<T = Record<string, unknown>>(sql: string, params: unknown[] = []): Promise<T[]> {
  if (!DB_URL) return [];
  try {
    const { neon } = await import("@neondatabase/serverless");
    const db = neon(DB_URL);
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    return ((await (db as any).query(sql, params)) ?? []) as T[];
  } catch {
    return [];
  }
}

export async function POST(req: Request) {
  let body: { match_id?: string; player1?: string; player2?: string };
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "invalid json" }, { status: 400 });
  }

  const match_id = body.match_id;
  if (!match_id) {
    return NextResponse.json({ analysis: null });
  }

  // Read analysis generated by TennisResearchAgent (Ollama) stored in match_research
  const rows = await dbQuery<{ summary: string; created_at: string }>(
    `SELECT summary, created_at FROM match_research
     WHERE match_id = $1
     ORDER BY created_at DESC
     LIMIT 1`,
    [match_id]
  );

  if (rows.length > 0 && rows[0].summary) {
    return NextResponse.json({ analysis: rows[0].summary });
  }

  return NextResponse.json({ analysis: null });
}
