// The committed list of internal/test accounts (content/internal-accounts.json,
// generated by scripts/internal-accounts.ts), validated once at load: a
// malformed file fails the build instead of reaching a query.
import internalJson from "@/content/internal-accounts.json";
import { type InternalLists, validateInternal } from "@/core/internal";

export const INTERNAL: InternalLists = validateInternal(internalJson);
