// lib/v3c/community-copy.ts (#REDESIGN-V3C · filone pages, parte community)
// Copy v3c di /leaderboard, /invite, /community e della cornice di /privacy,
// /terms, /profilo. EN è la fonte, IT è completa; le altre nove lingue
// ricadono sull'inglese (F10). Lessico: estimate · probability · record ·
// points. Mai hit-rate, ROI, tip, guaranteed. ≤22 parole per elemento.

export type CommunityLang = "en" | "it";

const EN = {
  lb: {
    tab: "Leaderboard · members",
    title: "Members' table",
    metaStrong: "10 points per won bet",
    metaRest: "updates after each settlement · opt in from your settings",
    rank: "#",
    player: "Member",
    points: "Points",
    record: "Won / total",
    sport: "Sport",
    podium: "Top three",
    yourRank: "Your position",
    notListed: "You are not on the table yet.",
    notOptedIn: "Enable the leaderboard in your settings to appear on the table.",
    loading: "Loading the table…",
    error: "The table could not load.",
    retry: "Retry",
    emptyTitle: "No ranking yet.",
    emptyHint: "The table fills in after bets settle. Members choose to appear; nobody is listed by default.",
    note: "Points count members' own settled bets. They say nothing about our estimates; the record does that.",
    recordLink: "See the record",
    pts: (n: number) => `${n} pts`,
    unit: "pts",
  },
  inv: {
    tab: "Invite · your link",
    title: "Invite a friend",
    metaStrong: "One link per account",
    metaRest: "rewards come from the server, as they are granted",
    intro: "Share your link: every friend who signs up and pays brings you closer to the next reward.",
    codeLabel: "Choose your creator code",
    placeholder: "YOURCODE",
    hint: "2–20 characters: letters, numbers, - _ · cannot be changed once claimed",
    claimBtn: "Claim code",
    claimBusy: "Claiming…",
    errTaken: "Code already taken. Pick another.",
    errInvalid: "Invalid code: 2–20 characters, letters, numbers, - _.",
    errGeneric: "Temporary error, try again.",
    yourCode: "Your code",
    linkLabel: "Your invite link",
    copy: "Copy link",
    copied: "Copied",
    signups: "Sign-ups with your code",
    paying: "Paying friends",
    kpiConv: "Conversion",
    kpiEarned: "Pro days earned",
    zeroState: "No sign-ups yet. Send the link above to people who already ask you about prices.",
    statsErr: "Stats unavailable right now.",
    retry: "Retry",
    pending: "on its way",
    loading: "Loading…",
    friendGets: (d: number) => `Anyone who signs up with your link gets ${d} free days of Pro.`,
    rewardsTitle: "Your rewards",
    progress: (n: number, k: number) => `${n === 1 ? "1 paying friend" : `${n} paying friends`} · ${k} to the next reward`,
    progressDone: (n: number) => `${n} paying friends · all rewards unlocked`,
    tierAt: (n: number) => `at ${n} friends`,
    rewardDays: (d: number) => `+${d} days of Pro`,
    rewardRoom: "Private Telegram room",
    nextUp: (r: string, n: number) => `Next: ${r} · at ${n} paying friends`,
    note: "Creator option: revenue on your sign-ups only if we enable it on your code. Write to us to ask.",
    promo: "The launch discount applies to anyone who signs up, invited or not. It is not a perk of your link.",
    signInTitle: "Sign in to get your invite link",
    signInBody: "Your code and its numbers belong to your account.",
    signIn: "Sign in",
  },
  cm: {
    tab: "Community · creator slips",
    title: "Creator slips",
    metaStrong: "Built by members",
    metaRest: "each leg carries the model's own probability, unchanged",
    create: "Build yours",
    loading: "Loading…",
    loadError: "The slips could not load.",
    retry: "Retry",
    emptyTitle: "No slips published yet.",
    emptySub: "Be the first: build one in the probability view and share it.",
    open: "Open slip",
    gateNoneTitle: "Creator slips are part of Pro",
    gateNoneSub: "Matches are visible to everyone. Legs and probabilities open with Pro.",
    gatePartial: "Your plan opens some slips. Pro opens every one.",
    seePlans: "See Pro",
    lockedLine: "Legs and probability open with Pro",
    combined: "Combined",
    legs: (n: number) => (n === 1 ? "1 leg" : `${n} legs`),
    responsible: "18+ · analysis, not advice",
    locale: "en-GB",
  },
  legal: {
    title: "Legal",
    privacyTab: "Legal · privacy",
    termsTab: "Legal · terms",
    note: "The full text, below.",
  },
  profile: {
    tab: "Account · profile",
    title: "Your profile",
  },
};

export type CommunityCopy = typeof EN;

const IT: CommunityCopy = {
  lb: {
    tab: "Classifica · membri",
    title: "La classifica dei membri",
    metaStrong: "10 punti per scommessa vinta",
    metaRest: "si aggiorna a ogni settlement · si entra dalle impostazioni",
    rank: "#",
    player: "Membro",
    points: "Punti",
    record: "Vinte / totali",
    sport: "Sport",
    podium: "I primi tre",
    yourRank: "La tua posizione",
    notListed: "Non sei ancora in classifica.",
    notOptedIn: "Attiva la classifica nelle impostazioni per comparire.",
    loading: "Carico la classifica…",
    error: "La classifica non si è caricata.",
    retry: "Riprova",
    emptyTitle: "Ancora nessuna classifica.",
    emptyHint: "La classifica si riempie dopo il settlement. Ci compare solo chi lo sceglie.",
    note: "I punti contano le scommesse dei membri. Non dicono nulla delle nostre stime: per quello c'è il registro.",
    recordLink: "Apri il registro",
    pts: (n: number) => `${n} pt`,
    unit: "pt",
  },
  inv: {
    tab: "Invita · il tuo link",
    title: "Invita un amico",
    metaStrong: "Un link per account",
    metaRest: "i premi arrivano dal server, quando sono concessi",
    intro: "Condividi il tuo link: ogni amico che si iscrive e paga ti avvicina al premio successivo.",
    codeLabel: "Scegli il tuo codice creator",
    placeholder: "ILTUOCODICE",
    hint: "2–20 caratteri: lettere, numeri, - _ · una volta scelto non si cambia",
    claimBtn: "Riserva il codice",
    claimBusy: "Riservo…",
    errTaken: "Codice già preso: scegline un altro.",
    errInvalid: "Codice non valido: 2–20 caratteri, lettere, numeri, - _.",
    errGeneric: "Errore momentaneo, riprova.",
    yourCode: "Il tuo codice",
    linkLabel: "Il tuo link di invito",
    copy: "Copia link",
    copied: "Copiato",
    signups: "Iscritti col tuo codice",
    paying: "Amici paganti",
    kpiConv: "Conversione",
    kpiEarned: "Giorni Pro ottenuti",
    zeroState: "Ancora nessun iscritto. Manda il link a chi ti chiede già dei prezzi.",
    statsErr: "Statistiche non disponibili al momento.",
    retry: "Riprova",
    pending: "in arrivo",
    loading: "Carico…",
    friendGets: (d: number) => `Chi si iscrive col tuo link riceve ${d} giorni di Pro gratis.`,
    rewardsTitle: "I tuoi premi",
    progress: (n: number, k: number) => `${n === 1 ? "1 amico pagante" : `${n} amici paganti`} · ${k} al prossimo premio`,
    progressDone: (n: number) => `${n} amici paganti · tutti i premi sbloccati`,
    tierAt: (n: number) => `a ${n} amici`,
    rewardDays: (d: number) => `+${d} giorni di Pro`,
    rewardRoom: "Stanza Telegram riservata",
    nextUp: (r: string, n: number) => `Prossimo: ${r} · a ${n} amici paganti`,
    note: "Opzione creator: revenue sui tuoi iscritti solo se la attiviamo sul tuo codice. Scrivici per chiederla.",
    promo: "Lo sconto di lancio vale per chiunque si iscriva, con o senza invito: non è un vantaggio del tuo link.",
    signInTitle: "Accedi per avere il tuo link di invito",
    signInBody: "Il codice e i suoi numeri appartengono al tuo account.",
    signIn: "Accedi",
  },
  cm: {
    tab: "Community · schedine creator",
    title: "Schedine dei creator",
    metaStrong: "Costruite dai membri",
    metaRest: "ogni selezione porta la probabilità del modello, invariata",
    create: "Crea la tua",
    loading: "Carico…",
    loadError: "Le schedine non si sono caricate.",
    retry: "Riprova",
    emptyTitle: "Nessuna schedina pubblicata.",
    emptySub: "Sii il primo: costruiscila nella vista probabilità e condividila.",
    open: "Apri la schedina",
    gateNoneTitle: "Le schedine dei creator sono in Pro",
    gateNoneSub: "Le partite le vedono tutti. Selezioni e probabilità si aprono con Pro.",
    gatePartial: "Il tuo piano apre alcune schedine. Pro le apre tutte.",
    seePlans: "Vedi Pro",
    lockedLine: "Selezioni e probabilità si aprono con Pro",
    combined: "Combinata",
    legs: (n: number) => (n === 1 ? "1 selezione" : `${n} selezioni`),
    responsible: "18+ · analisi, non consigli",
    locale: "it-IT",
  },
  legal: {
    title: "Note legali",
    privacyTab: "Note legali · privacy",
    termsTab: "Note legali · termini",
    note: "Il testo completo, qui sotto, in inglese.",
  },
  profile: {
    tab: "Account · profilo",
    title: "Il tuo profilo",
  },
};

export function communityCopyFor(lang: string): CommunityCopy {
  return lang === "it" ? IT : EN;
}
