// lib/v3c/copy.ts (#REDESIGN-V3C F3)
// La copy del redesign: EN è la fonte, IT è completa, le altre nove lingue
// ricadono sull'inglese CHIAVE PER CHIAVE (copyFor). Le chiavi sono elencate
// in docs/v3c-i18n-keys.md per F10. Lessico del deck: market · estimate · gap
// (in points) · sealed · blend 70/30 — mai «tip», «edge» come profitto, «hot».
// Nessun numero di performance qui dentro: i numeri li porta il dato.

export type V3cLang = "en" | "it";

const EN = {
  nav: {
    board: "Board",
    tools: "Tools",
    price: "Price check",
    priceShort: "Price",
    record: "Record",
    books: "Books",
    news: "News",
    pro: "Pro",
    primary: "Primary",
  },
  fascia: {
    tab: "Board · football & tennis",
    tabPredictions: "Predictions · football & tennis",
    matches: (n: number) => (n === 1 ? "1 match" : `${n} matches`),
    pricesAsOf: (t: string) => `prices as of ${t}`,
    sealed: "sealed",
    sealedBefore: "sealed before kick-off",
    titlePredictions: "The board",
    unavailable: "board data unavailable",
    sealedCount: (s: number, n: number) => `${s} of ${n} sealed before kick-off`,
    window: (d: number) => `next ${d} days`,
  },
  toolbar: {
    sport: "Sport",
    all: "All",
    football: "Football",
    tennis: "Tennis",
    day: "Day",
    allDays: "All days",
    today: "Today",
    tomorrow: "Tomorrow",
    league: "League",
    allLeagues: "All leagues",
    explain: "Market %: the composite price, margin removed. Estimate: 70% market, 30% model. Gap: estimate − market, in points.",
    legendMarket: "Market %, margin removed",
    legendEstimate: "Estimate: 70% market + 30% model (football), model (tennis)",
    legendGap: "Gap = estimate − market, in points.",
  },
  board: {
    label: "Today’s board",
    kickoff: "Kick-off",
    match: "Match · lead outcome",
    price: "Price",
    priceSub: "market",
    market: "Market",
    marketSub: "margin removed",
    estimate: "Estimate",
    estimateSub: "70/30 blend",
    gap: "Gap",
    gapSub: "pp",
    best: "Best price",
    bestSub: "connected books",
    moreBooks: "More books",
    noPrice: "no feed price",
    inLine: "in line",
    gapWord: "gap",
    draw: "Draw",
    noMarket: "no market",
    noMarketLong: "No market price stored: the estimate is the model alone and there is no gap to show.",
    rowNote: "Each row shows the outcome with the largest gap, the others beneath it. Tap a row for all three and the book prices.",
    sealedAt: (t: string) => `sealed ${t}`,
    sealedWhy: (t: string) => `This match entered the public ledger on ${t}, before kick-off. The row cannot be edited afterwards; the numbers shown are the latest estimate and can differ from the sealed ones.`,
    estimateAsOf: (t: string) => `estimate as of ${t}`,
    margin: (m: string) => `margin removed ${m}`,
    blend: "estimate = 70% market + 30% model",
    modelOnly: "estimate = model (no market)",
    booksFor: (o: string) => `Connected books · ${o}`,
    allOutcomes: "All three outcomes",
    open: "Open",
    close: "Close",
    live: "Live",
    liveGroup: "Live now",
    liveSince: (m: number) => `${m}′`,
    rowAria: (lead: string, price: string, market: string, est: string, gap: string) =>
      `${lead} at ${price}, market ${market} percent, estimate ${est} percent, gap ${gap} points. Show all outcomes`,
    outcome: "Outcome",
    scaleHead: "Market → estimate",
    scaleSub: "on a 0–100% scale",
    scaleAria: (m: string, e: string, g: string) => `Market ${m} percent, estimate ${e} percent, gap ${g} points, on a 0 to 100 percent scale`,
    scaleAriaNoMarket: (e: string) => `No market price; estimate ${e} percent, model only`,
    seeAll: (n: number) => `The whole board · ${n} matches →`,
    noFeedBooks: "No connected book has a price for this outcome yet.",
    bestCta: (label: string, price: string, book: string) => `Best price on ${label}: ${price} at ${book}`,
    bestNote: "Opens the book’s site in a new tab. Commercial affiliate link · 18+ · the price on the book can differ from the one shown.",
    group: (n: number) => (n === 1 ? "1 match" : `${n} matches`),
    partnerAria: (book: string) => `${book}, affiliate link, opens in a new tab`,
    partnerBlocked: "Partner prices are not shown in your region.",
  },
  tennis: {
    title: "Tennis",
    coming: "market comparison coming",
    comingLong: "Tennis rows show our estimate and the connected books’ prices. The market comparison and the gap arrive once a market/model split is stored per match.",
    marketOnly: "market price only",
    marketOnlyLong: "No model of ours on this match: the percentage is the book’s price with the margin removed (temperature 1.68). A gap against itself would be zero.",
    winner: "Winner",
    estimateModel: "Estimate · model",
    sealedCol: "Sealed",
    gapCol: "Gap at seal",
    atSeal: "at seal",
    kindModel: "Elo v4, our model",
    kindModelTempered: "Elo v4 with temperature 1.68, our model (no market when served)",
    kindMarket: "Market price without margin, temperature 1.68: not a model of ours",
    rawElo: (p: string) => `raw Elo ${p}% (not sealed)`,
    gapVs: (book: string, time: string) => `Gap = our sealed estimate − the ${book} price captured on ${time}, before the seal, margin removed. A difference of probabilities, not a profit.`,
    reasonNotSealed: "Not sealed yet: the gap appears once our estimate is in the ledger.",
    reasonNoMarketAtSeal: "No FortunePlay or YBets price was captured in the 150 minutes before the seal, so there is no gap to show.",
    reasonAnchored: "The sealed number is the market price itself (our Elo was anchored to it): a gap against itself would be zero.",
    rowAria: (lead: string, scale: string) => `${lead}: ${scale}. Show both players`,
    scaleAriaModel: (e: string) => `Estimate ${e} percent, our model; no market comparison yet`,
    scaleAriaMarket: (e: string) => `Market ${e} percent, margin removed; no model estimate`,
    scaleAriaSeal: (m: string, e: string, g: string) => `At the seal: market ${m} percent, our estimate ${e} percent, gap ${g} points`,
  },
  empty: {
    filter: "No match for this filter.",
    filterHint: "Try another day or sport; the board covers the next ten days.",
    noLive: "No match is live right now.",
    biggestGap: "Biggest gap today",
    biggestGapLine: (match: string, lead: string, gap: string) => `${match} · ${lead} · ${gap} pp`,
    nextUp: "Next up",
    startsIn: (s: string) => `starts in ${s}`,
    yesterday: "Yesterday’s review",
    yesterdayLine: (won: number, lost: number) => `${won} won · ${lost} lost, from the sealed ledger`,
    nothing: "Nothing on the board.",
    nothingHint: "No published match in the next ten days. The board fills as fixtures are priced.",
    seeAll: "Show the whole board",
    hours: (h: number, m: number) => `${h} h ${m} min`,
    minutes: (m: number) => `${m} min`,
    days: (d: number, h: number) => `${d} d ${h} h`,
  },
  error: {
    title: "The board didn’t load.",
    body: "The data source did not answer. Nothing is cached in your browser, so a retry asks again.",
    retry: "Try again",
  },
  loading: "Loading the board",
  yday: {
    title: "Yesterday, won and lost",
    unavailable: "Yesterday’s settlements didn’t load. The record keeps them.",
    wonOne: "Won",
    lostOne: "Lost",
    picked: (pick: string, p: string) => `sealed on ${pick} at ${p}%`,
    paper: "no market price at seal",
    more: (n: number) => `${n} more in the record.`,
    lab: (d: string) => `Yesterday · ${d} · from the sealed ledger`,
    body: "Won and lost are the settled picks. “Expected” is the sum of the sealed probabilities: what the estimates were supposed to win.",
    settled: "Settled",
    won: "Won",
    lost: "Lost",
    other: "Void",
    expected: "Expected",
    football: "Football",
    tennis: "Tennis",
    none: "Nothing settled yesterday.",
    noneHint: "No sealed pick kicked off yesterday, or the settlements are still pending.",
    full: "Full record",
    limited: "limited sample",
  },
  bench: {
    lab: "The bench · 11 tools · free, no sign-in",
    title: "Do the maths on any price",
    all: "All 11 tools →",
    pcName: "Price check",
    pcLine: "Type the three prices from your book: margin and market probability, estimate next to it.",
    pcCta: "Check a price",
    marginWord: "margin",
    vs: "vs",
    note: (match: string) => `Examples use ${match} from today’s board. Each tool takes your numbers and ends on the board, not a paywall.`,
    noteNoMatch: "Examples use a sample price until today’s board has a match with a market.",
    tools: {
      "ev-calculator": { name: "EV calculator", line: "is the price worth it at your probability?" },
      "probability-calculator": { name: "Probability calculator", line: "three prices to probabilities, margin removed" },
      "kelly-criterion": { name: "Kelly criterion", line: "fraction of bankroll, with half and quarter Kelly" },
      "margin-calculator": { name: "Margin calculator", line: "how much the book keeps on a market" },
    } as Record<string, { name: string; line: string }>,
  },
  faq: { title: "Questions people ask before signing up" },
  foot: {
    lede: "Market price, our estimate next to it, the sealed record. Then the best price from a connected book.",
    product: "Product",
    trust: "Trust",
    legal: "Legal",
    tools: "Tools · 11, free",
    method: "Method",
    terms: "Terms",
    privacy: "Privacy",
    partners: "Partners",
    disclaimer: "Analysis, not advice. BetRedge is not a bookmaker and takes no bets.",
    blend: "Football estimates are 70% market, 30% model.",
    affiliates: "Partner links are commercial affiliates.",
    responsible: "Gamble responsibly",
    age: "18+",
  },
  theme: { toDark: "Switch to dark", toPaper: "Switch to paper" },
};

export type V3cCopy = typeof EN;

const IT: V3cCopy = {
  nav: { ...EN.nav, board: "Board", tools: "Strumenti", price: "Controllo prezzo", priceShort: "Prezzo", record: "Registro", books: "Book", news: "Notizie", pro: "Pro", primary: "Principale" },
  fascia: {
    tab: "Board · calcio & tennis",
    tabPredictions: "Previsioni · calcio & tennis",
    matches: (n) => (n === 1 ? "1 partita" : `${n} partite`),
    pricesAsOf: (t) => `prezzi alle ${t}`,
    sealed: "sigillato",
    sealedBefore: "sigillato prima del fischio",
    titlePredictions: "La board",
    unavailable: "dati della board non disponibili",
    sealedCount: (s, n) => `${s} su ${n} sigillate prima del fischio`,
    window: (d) => `prossimi ${d} giorni`,
  },
  toolbar: {
    sport: "Sport",
    all: "Tutti",
    football: "Calcio",
    tennis: "Tennis",
    day: "Giorno",
    allDays: "Tutti i giorni",
    today: "Oggi",
    tomorrow: "Domani",
    league: "Campionato",
    allLeagues: "Tutti i campionati",
    explain: "Mercato %: il prezzo composito, margine tolto. Stima: 70% mercato, 30% modello. Gap: stima − mercato, in punti.",
    legendMarket: "Mercato %, margine tolto",
    legendEstimate: "Stima: 70% mercato + 30% modello (calcio), modello (tennis)",
    legendGap: "Gap = stima − mercato, in punti.",
  },
  board: {
    label: "La board di oggi",
    kickoff: "Inizio",
    match: "Partita · esito guida",
    price: "Prezzo",
    priceSub: "mercato",
    market: "Mercato",
    marketSub: "margine tolto",
    estimate: "Stima",
    estimateSub: "blend 70/30",
    gap: "Gap",
    gapSub: "pp",
    best: "Miglior prezzo",
    bestSub: "book connessi",
    moreBooks: "Altri book",
    noPrice: "nessun prezzo dal feed",
    inLine: "in linea",
    gapWord: "gap",
    draw: "Pareggio",
    noMarket: "senza mercato",
    noMarketLong: "Nessun prezzo di mercato archiviato: la stima è il solo modello e non c’è un gap da mostrare.",
    rowNote: "Ogni riga mostra l’esito con il gap più ampio, gli altri sotto. Tocca una riga per tutti e tre e i prezzi dei book.",
    sealedAt: (t) => `sigillato ${t}`,
    sealedWhy: (t) => `Questa partita è entrata nel registro pubblico il ${t}, prima del fischio. La riga non si può più modificare; i numeri mostrati sono l’ultima stima e possono differire da quelli sigillati.`,
    estimateAsOf: (t) => `stima delle ${t}`,
    margin: (m) => `margine tolto ${m}`,
    blend: "stima = 70% mercato + 30% modello",
    modelOnly: "stima = modello (senza mercato)",
    booksFor: (o) => `Book connessi · ${o}`,
    allOutcomes: "Tutti e tre gli esiti",
    open: "Apri",
    close: "Chiudi",
    live: "Live",
    liveGroup: "In corso",
    liveSince: (m) => `${m}′`,
    rowAria: (lead, price, market, est, gap) => `${lead} a ${price}, mercato ${market} per cento, stima ${est} per cento, gap ${gap} punti. Mostra tutti gli esiti`,
    outcome: "Esito",
    scaleHead: "Mercato → stima",
    scaleSub: "su scala 0–100%",
    scaleAria: (m, e, g) => `Mercato ${m} per cento, stima ${e} per cento, gap ${g} punti, su scala da 0 a 100 per cento`,
    scaleAriaNoMarket: (e) => `Nessun prezzo di mercato; stima ${e} per cento, solo modello`,
    seeAll: (n) => `Tutta la board · ${n} partite →`,
    noFeedBooks: "Nessun book connesso ha ancora un prezzo per questo esito.",
    bestCta: (label, price, book) => `Miglior prezzo per ${label}: ${price} da ${book}`,
    bestNote: "Apre il sito del book in una nuova scheda. Link affiliato commerciale · 18+ · il prezzo sul book può differire da quello mostrato.",
    group: (n) => (n === 1 ? "1 partita" : `${n} partite`),
    partnerAria: (book) => `${book}, link affiliato, si apre in una nuova scheda`,
    partnerBlocked: "I prezzi dei partner non si mostrano nella tua regione.",
  },
  tennis: {
    title: "Tennis",
    coming: "confronto col mercato in arrivo",
    comingLong: "Le righe del tennis mostrano la nostra stima e i prezzi dei book connessi. Il confronto col mercato e il gap arrivano quando sarà archiviata la separazione mercato/modello per partita.",
    marketOnly: "solo prezzo di mercato",
    marketOnlyLong: "Nessun nostro modello su questa partita: la percentuale è il prezzo del book senza margine (temperatura 1,68). Un gap contro sé stesso sarebbe zero.",
    winner: "Vincente",
    estimateModel: "Stima · modello",
    sealedCol: "Sigillata",
    gapCol: "Gap al sigillo",
    atSeal: "al sigillo",
    kindModel: "Elo v4, il nostro modello",
    kindModelTempered: "Elo v4 con temperatura 1,68, il nostro modello (senza mercato quando servita)",
    kindMarket: "Prezzo di mercato senza margine, temperatura 1,68: non è un nostro modello",
    rawElo: (p) => `Elo grezzo ${p}% (non sigillato)`,
    gapVs: (book, time) => `Gap = la nostra stima sigillata − il prezzo ${book} catturato il ${time}, prima del sigillo, margine tolto. Una differenza di probabilità, non un profitto.`,
    reasonNotSealed: "Non ancora sigillata: il gap compare quando la nostra stima entra nel registro.",
    reasonNoMarketAtSeal: "Nessun prezzo FortunePlay o YBets catturato nei 150 minuti prima del sigillo: non c’è un gap da mostrare.",
    reasonAnchored: "Il numero sigillato è il prezzo di mercato stesso (il nostro Elo vi era ancorato): un gap contro sé stesso sarebbe zero.",
    rowAria: (lead, scale) => `${lead}: ${scale}. Mostra entrambi i giocatori`,
    scaleAriaModel: (e) => `Stima ${e} per cento, il nostro modello; ancora nessun confronto col mercato`,
    scaleAriaMarket: (e) => `Mercato ${e} per cento, margine tolto; nessuna stima del modello`,
    scaleAriaSeal: (m, e, g) => `Al sigillo: mercato ${m} per cento, la nostra stima ${e} per cento, gap ${g} punti`,
  },
  empty: {
    filter: "Nessuna partita per questo filtro.",
    filterHint: "Prova un altro giorno o sport; la board copre i prossimi dieci giorni.",
    noLive: "Nessuna partita è live adesso.",
    biggestGap: "Il gap più ampio di oggi",
    biggestGapLine: (match, lead, gap) => `${match} · ${lead} · ${gap} pp`,
    nextUp: "La prossima",
    startsIn: (s) => `inizia tra ${s}`,
    yesterday: "La revisione di ieri",
    yesterdayLine: (won, lost) => `${won} vinte · ${lost} perse, dal registro sigillato`,
    nothing: "Niente sulla board.",
    nothingHint: "Nessuna partita pubblicata nei prossimi dieci giorni. La board si riempie man mano che le partite vengono prezzate.",
    seeAll: "Mostra tutta la board",
    hours: (h, m) => `${h} h ${m} min`,
    minutes: (m) => `${m} min`,
    days: (d, h) => `${d} g ${h} h`,
  },
  error: {
    title: "La board non si è caricata.",
    body: "La fonte dati non ha risposto. Nel browser non c’è nulla in cache, quindi un nuovo tentativo richiede di nuovo.",
    retry: "Riprova",
  },
  loading: "Caricamento della board",
  yday: {
    title: "Ieri, vinte e perse",
    unavailable: "Le chiusure di ieri non si sono caricate. Il registro le conserva.",
    wonOne: "Vinta",
    lostOne: "Persa",
    picked: (pick, p) => `sigillata su ${pick} al ${p}%`,
    paper: "senza prezzo di mercato al sigillo",
    more: (n) => `Altre ${n} nel registro.`,
    lab: (d) => `Ieri · ${d} · dal registro sigillato`,
    body: "Vinte e perse sono le pick chiuse. «Attese» è la somma delle probabilità sigillate: quante le stime dovevano vincerne.",
    settled: "Chiuse",
    won: "Vinte",
    lost: "Perse",
    other: "Annullate",
    expected: "Attese",
    football: "Calcio",
    tennis: "Tennis",
    none: "Nessuna chiusura ieri.",
    noneHint: "Nessuna pick sigillata è iniziata ieri, oppure le chiusure sono ancora in sospeso.",
    full: "Registro completo",
    limited: "campione limitato",
  },
  bench: {
    lab: "Il banco · 11 strumenti · gratis, senza registrazione",
    title: "Fai i conti su qualunque prezzo",
    all: "Tutti gli 11 strumenti →",
    pcName: "Controllo prezzo",
    pcLine: "Scrivi i tre prezzi del tuo book: margine e probabilità di mercato, la stima accanto.",
    pcCta: "Controlla un prezzo",
    marginWord: "margine",
    vs: "vs",
    note: (match) => `Gli esempi usano ${match} dalla board di oggi. Ogni strumento prende i tuoi numeri e finisce sulla board, non su un paywall.`,
    noteNoMatch: "Gli esempi usano un prezzo campione finché la board di oggi non ha una partita con un mercato.",
    tools: {
      "ev-calculator": { name: "Calcolatore EV", line: "il prezzo vale alla tua probabilità?" },
      "probability-calculator": { name: "Calcolatore di probabilità", line: "da tre prezzi alle probabilità, margine tolto" },
      "kelly-criterion": { name: "Criterio di Kelly", line: "frazione del bankroll, con mezzo e quarto Kelly" },
      "margin-calculator": { name: "Calcolatore di margine", line: "quanto trattiene il book su un mercato" },
    },
  },
  faq: { title: "Le domande che fanno prima di registrarsi" },
  foot: {
    lede: "Il prezzo di mercato, la nostra stima accanto, il registro sigillato. Poi il miglior prezzo da un book connesso.",
    product: "Prodotto",
    trust: "Fiducia",
    legal: "Legale",
    tools: "Strumenti · 11, gratis",
    method: "Metodo",
    terms: "Termini",
    privacy: "Privacy",
    partners: "Partner",
    disclaimer: "Analisi, non consigli. BetRedge non è un bookmaker e non accetta scommesse.",
    blend: "Le stime del calcio sono 70% mercato, 30% modello.",
    affiliates: "I link partner sono affiliati commerciali.",
    responsible: "Gioca responsabilmente",
    age: "18+",
  },
  theme: { toDark: "Passa allo scuro", toPaper: "Passa alla carta" },
};

export const V3C_COPY: Record<V3cLang, V3cCopy> = { en: EN, it: IT };

/** La lingua del sito (localStorage «agentic-lang»: it/en/es/fr/ru…) → la copy. Tutto ciò che non è `it` legge l'inglese. */
export function copyFor(lang: string | null | undefined): V3cCopy {
  return lang === "it" ? IT : EN;
}

/** Per F10: le chiavi foglia del dizionario, in ordine, così la lista in docs si rigenera e non si scrive a mano. */
export function copyKeys(obj: Record<string, unknown> = EN as unknown as Record<string, unknown>, prefix = ""): string[] {
  const out: string[] = [];
  for (const [k, v] of Object.entries(obj)) {
    const key = prefix ? `${prefix}.${k}` : k;
    if (v && typeof v === "object" && !Array.isArray(v)) out.push(...copyKeys(v as Record<string, unknown>, key));
    else out.push(key);
  }
  return out;
}
