// lib/v3c/copy-record.ts (#REDESIGN-V3C F6) — the copy of /record, EN source,
// IT complete, the other nine languages fall back to EN key by key (F10; keys
// listed in docs/v3c-i18n-keys.md). Own file so the parallel filoni do not
// collide on copy.ts.
// Lexicon: estimate · market · gap (pp) · sealed · receipt · record. Never ROI,
// CLV, hit-rate, win rate, «beat the market», guaranteed. Every claim here is
// a sentence the DATA picks (brierVerdict), not a fixed boast.
import { v3cLang, type V3cLang } from "./copy";

export type BrierVerdict = "market_better" | "tie" | "ours_lower";

const EN = {
  fascia: {
    tab: "Record · read only from the sealed ledger",
    title: "Every estimate, and how it settled",
    since: (d: string) => `On record since ${d}`,
    sealed: (f: string, tn: string) => `${f} football · ${tn} tennis sealed before kick-off`,
    edit: "Nothing here can be edited after publication.",
    unavailable: "record data unavailable",
  },
  kpi: {
    sealed: "Football estimates sealed",
    sealedVs: (since: string, last: string, scored: string) => `${since} – ${last} · ${scored} settled with a result`,
    brier: "Brier score · lower is better",
    ours: "Our estimate",
    market: "Market, margin removed",
    ci: (lo: string, hi: string) => `95% interval ${lo}–${hi}`,
    verdict: {
      market_better: "The market is slightly better than ours. We publish it anyway.",
      tie: "On this sample the two cannot be told apart. We publish it either way.",
      ours_lower: "Ours is lower on this sample. A sample, not a promise.",
    } as Record<BrierVerdict, string>,
    diff: (d: string, lo: string, hi: string, n: string) => `Difference ${d} (95%: ${lo} to ${hi}) on ${n} matches with the market at seal.`,
    blend: "Football estimate = 30% our model + 70% the market, margin removed.",
    coverage: "Coverage",
    coverageMain: (paired: string, scored: string) => `${paired} of ${scored}`,
    coverageVs: "settled matches carry the market price at the moment of the seal",
    coverageRest: (pending: string, orphans: string, paper: string) => `${pending} awaiting a result · ${orphans} past kick-off without one · ${paper} sealed with no market (paper)`,
  },
  cal: {
    title: "Does a 60% happen 60 times in 100?",
    lede: "Calibration: stated probability against how often it happened. Accuracy is the Brier score above.",
    fig: "Reliability · stated against observed",
    figSub: (pairs: string, n: string) => `${pairs} outcomes from ${n} matches · bars are 95% intervals`,
    aria: "Reliability diagram of our football estimate and of the market against the diagonal of perfect calibration",
    ours: "our estimate",
    market: "market",
    diag: "perfect calibration",
    xAxis: "stated probability",
    yAxis: "observed",
    caption: "Hollow marks: fewer than 30 outcomes in the bin. Dot size follows n.",
    binsTitle: "By bin, with n",
    stated: "Stated",
    observed: "Observed",
    pm: "±95%",
    n: "n",
    gap: "Gap",
    limited: "limited sample",
    binsNote: "Wilson 95% intervals. Gap = observed − stated, in points.",
  },
  weeks: {
    title: "Expected against observed, by week",
    sub: "A record is luck or measurement; this is how you tell.",
    expected: "Expected: sum of sealed probabilities of the most likely outcome",
    observed: "Observed: how often that outcome happened",
    aria: "Expected against observed outcomes, by ISO week",
    week: (d: string) => `wk of ${d}`,
    caption: "Whiskers are the 95% interval of the observed count. Weeks under 30 matches: expected bar in grey, n marked *.",
    // final2: why the bars drop, settled/sealed under each week, break and current week
    why: "Shorter bars mean fewer settled matches that week: national-team breaks pause the top leagues, and this week is still being played.",
    counts: "Under each week: matches with an outcome / sealed.",
    awaiting: (n: string) => `${n} awaiting`,
    awaitingKey: "Awaiting: kicked off, result not in yet.",
    breakTag: "Break",
    breakKey: "Nations break: no top-five league match sealed that week.",
    nowTag: "Ongoing",
    nowKey: "This week: in progress, incomplete.",
  },
  tennis: {
    title: "Tennis, kept apart",
    lede: "In tennis the sealed number is market-based, not an estimate of ours, so we show outcomes and match counts only.",
    label: "Market-based probability",
    sealed: "Matches sealed",
    settled: "Settled",
    won: "Won",
    lost: "Lost",
    void: "Void",
    awaiting: "Awaiting a result",
    note: "Won = the picked player won. Without a price at the seal, a tempered Elo stood in. No Brier, no calibration.",
  },
  receipts: {
    title: "Receipts, won and lost alike",
    filter: "Sport",
    all: "All",
    football: "Football",
    tennis: "Tennis",
    sealed: "Sealed (UTC)",
    match: "Match",
    read: "Outcome read",
    price: "Price",
    marketPct: "Market %",
    estimatePct: "Estimate %",
    gap: "Gap",
    result: "Result",
    fingerprint: "Fingerprint",
    draw: "Draw",
    kickoff: "kick-off",
    top: "top outcome · no pick shown",
    pick: "pick shown",
    noMarket: "no market at seal",
    isMarket: "is the market",
    marketBased: "market-based",
    paper: "paper",
    corrected: "corrected",
    verdict: { in_favour: "in favour", against: "against", void: "void", unresolved: "unresolved" } as Record<"in_favour" | "against" | "void" | "unresolved", string>,
    // ui2: la pill dell'esito accanto a ogni ricevuta (W/L/V sono la sigla internazionale, la parola è questa)
    outcome: { won: "Won", lost: "Lost", void: "Void", pending: "Pending" } as Record<"won" | "lost" | "void" | "pending", string>,
    older: "Older receipts",
    newer: "Newer",
    page: (p: number) => `Page ${p}`,
    scroll: "Scroll sideways for the full row.",
    recipe: "Fingerprint = SHA-256 of v1|table|id|model|sealed at|p home|p draw|p away|price. Recompute it from the row.",
    recipeNote: "The ledger stores no hash; this one is computed from the sealed fields, not at the seal.",
    noReturn: "No return figure: it would not be independent of us.",
    fullHash: "Full SHA-256",
    empty: "Nothing settled yet. A sealed estimate appears here once its match has a result.",
    emptyFilter: "No settled rows for this sport yet.",
  },
  corr: {
    title: "Corrections, shown as corrections",
    lede: (n: string) => `A result is never edited in place: a correction is a new row with its reason. ${n} so far.`,
    when: "Corrected",
    match: "Match",
    change: "Before → after",
    reason: "Reason",
    cause: {
      late_result: (src: string) => `Result recovered late${src ? ` (source: ${src})` : ""}`,
      postponed: (d: string) => `Postponed beyond 48 h${d ? ` (to ${d})` : ""}: void`,
      no_pick_shown: () => "No pick was shown: the won/lost label was voided",
      late_fill: () => "Result filled in late",
      other: () => "Correction",
    },
    byCause: "By reason",
    settle: { won: "won", lost: "lost", void: "void", unresolved: "unresolved" } as Record<string, string>,
    none: "No result has been corrected.",
    unavailable: "Corrections didn’t load. The ledger keeps them.",
  },
  state: {
    loading: "Reading the ledger",
    errorTitle: "The record didn’t load.",
    errorBody: "The ledger is intact; this page couldn’t read it. Try again in a moment.",
    retry: "Try again",
    empty: "Nothing sealed yet.",
    emptyBody: "The record starts with the first estimate sealed before a kick-off.",
  },
  limited: "limited sample",
};

export type V3cRecordCopy = typeof EN;

const IT: V3cRecordCopy = {
  fascia: {
    tab: "Registro · letto solo dal registro sigillato",
    title: "Ogni stima, e come è finita",
    since: (d) => `Nel registro dal ${d}`,
    sealed: (f, tn) => `${f} calcio · ${tn} tennis sigillate prima del fischio`,
    edit: "Niente qui si può modificare dopo la pubblicazione.",
    unavailable: "dati del registro non disponibili",
  },
  kpi: {
    sealed: "Stime calcio sigillate",
    sealedVs: (since, last, scored) => `${since} – ${last} · ${scored} concluse con un esito`,
    brier: "Brier score · più basso è meglio",
    ours: "La nostra stima",
    market: "Mercato, senza margine",
    ci: (lo, hi) => `intervallo 95% ${lo}–${hi}`,
    verdict: {
      market_better: "Il mercato è leggermente meglio di noi. Lo pubblichiamo lo stesso.",
      tie: "Su questo campione i due non si distinguono. Lo pubblichiamo comunque.",
      ours_lower: "Il nostro è più basso su questo campione. Un campione, non una promessa.",
    },
    diff: (d, lo, hi, n) => `Differenza ${d} (95%: da ${lo} a ${hi}) su ${n} partite con il mercato al sigillo.`,
    blend: "Stima calcio = 30% il nostro modello + 70% il mercato senza margine.",
    coverage: "Copertura",
    coverageMain: (paired, scored) => `${paired} su ${scored}`,
    coverageVs: "partite concluse hanno il prezzo di mercato del momento del sigillo",
    coverageRest: (pending, orphans, paper) => `${pending} in attesa dell’esito · ${orphans} oltre il fischio senza esito · ${paper} sigillate senza mercato (paper)`,
  },
  cal: {
    title: "Un 60% succede 60 volte su 100?",
    lede: "Calibrazione: probabilità dichiarata contro quante volte è successo. L’accuratezza è il Brier qui sopra.",
    fig: "Affidabilità · dichiarato contro osservato",
    figSub: (pairs, n) => `${pairs} esiti da ${n} partite · le barre sono intervalli al 95%`,
    aria: "Diagramma di affidabilità della nostra stima calcio e del mercato rispetto alla diagonale della calibrazione perfetta",
    ours: "la nostra stima",
    market: "mercato",
    diag: "calibrazione perfetta",
    xAxis: "probabilità dichiarata",
    yAxis: "osservato",
    caption: "Segni vuoti: meno di 30 esiti nella fascia. La dimensione del punto segue n.",
    binsTitle: "Per fascia, con n",
    stated: "Dichiarato",
    observed: "Osservato",
    pm: "±95%",
    n: "n",
    gap: "Scarto",
    limited: "campione limitato",
    binsNote: "Intervalli di Wilson al 95%. Scarto = osservato − dichiarato, in punti.",
  },
  weeks: {
    title: "Atteso contro osservato, settimana per settimana",
    sub: "Un registro è fortuna o misura: così si distingue.",
    expected: "Atteso: somma delle probabilità sigillate dell’esito più probabile",
    observed: "Osservato: quante volte quell’esito è successo",
    aria: "Esiti attesi contro osservati, per settimana ISO",
    week: (d) => `sett. del ${d}`,
    caption: "I baffi sono l’intervallo al 95% del conteggio osservato. Settimane sotto le 30 partite: barra attesa in grigio, n segnato *.",
    // final2: why the bars drop, settled/sealed under each week, break and current week
    why: "Barre più basse, meno partite concluse: le soste delle nazionali fermano i grandi campionati e la settimana in corso non è finita.",
    counts: "Sotto ogni settimana: partite con esito / sigillate.",
    awaiting: (n) => `${n} in attesa`,
    awaitingKey: "In attesa di risultato: iniziate, esito non ancora arrivato.",
    breakTag: "Sosta",
    breakKey: "Sosta nazionali: nessuna partita sigillata dei cinque grandi campionati quella settimana.",
    nowTag: "In corso",
    nowKey: "Settimana in corso, incompleta.",
  },
  tennis: {
    title: "Il tennis, a parte",
    lede: "Nel tennis il numero sigillato viene dal mercato, non è una nostra stima: mostriamo solo esiti e numero di partite.",
    label: "Probabilità basata sul mercato",
    sealed: "Partite sigillate",
    settled: "Concluse",
    won: "Vinte",
    lost: "Perse",
    void: "Annullate",
    awaiting: "In attesa dell’esito",
    note: "Vinta = ha vinto il giocatore scelto. Senza prezzo al sigillo c’è un Elo temperato. Niente Brier, niente calibrazione.",
  },
  receipts: {
    title: "Le ricevute, vinte e perse",
    filter: "Sport",
    all: "Tutti",
    football: "Calcio",
    tennis: "Tennis",
    sealed: "Sigillo (UTC)",
    match: "Partita",
    read: "Esito letto",
    price: "Quota",
    marketPct: "Mercato %",
    estimatePct: "Stima %",
    gap: "Scarto",
    result: "Esito",
    fingerprint: "Impronta",
    draw: "Pareggio",
    kickoff: "inizio",
    top: "esito più probabile · nessuna pick mostrata",
    pick: "pick mostrata",
    noMarket: "nessun mercato al sigillo",
    isMarket: "è il mercato",
    marketBased: "dal mercato",
    paper: "paper",
    corrected: "corretta",
    verdict: { in_favour: "a favore", against: "contro", void: "annullata", unresolved: "non risolta" },
    // ui2: la pill dell'esito accanto a ogni ricevuta (W/L/V sono la sigla internazionale, la parola è questa)
    outcome: { won: "Vinta", lost: "Persa", void: "Annullata", pending: "In attesa" },
    older: "Ricevute più vecchie",
    newer: "Più recenti",
    page: (p) => `Pagina ${p}`,
    scroll: "Scorri di lato per la riga intera.",
    recipe: "Impronta = SHA-256 di v1|tabella|id|modello|sigillo|p casa|p pari|p trasferta|quota. Ricalcolabile dalla riga.",
    recipeNote: "Il registro non salva un hash: questo è calcolato dai campi sigillati, non al momento del sigillo.",
    noReturn: "Nessuna cifra di rendimento: non sarebbe indipendente da noi.",
    fullHash: "SHA-256 completo",
    empty: "Ancora niente di concluso. Una stima sigillata compare qui quando la sua partita ha un esito.",
    emptyFilter: "Ancora nessuna riga conclusa per questo sport.",
  },
  corr: {
    title: "Le correzioni, mostrate come correzioni",
    lede: (n) => `Un esito non si modifica mai sul posto: una correzione è una riga nuova con il suo motivo. Finora ${n}.`,
    when: "Corretta",
    match: "Partita",
    change: "Prima → dopo",
    reason: "Motivo",
    cause: {
      late_result: (src) => `Esito recuperato in ritardo${src ? ` (fonte: ${src})` : ""}`,
      postponed: (d) => `Rinviata oltre 48 h${d ? ` (al ${d})` : ""}: annullata`,
      no_pick_shown: () => "Nessuna pick mostrata: l’etichetta vinta/persa è stata annullata",
      late_fill: () => "Esito inserito in ritardo",
      other: () => "Correzione",
    },
    byCause: "Per motivo",
    settle: { won: "vinta", lost: "persa", void: "annullata", unresolved: "non risolta" },
    none: "Nessun esito è stato corretto.",
    unavailable: "Le correzioni non si sono caricate. Il registro le conserva.",
  },
  state: {
    loading: "Lettura del registro",
    errorTitle: "Il registro non si è caricato.",
    errorBody: "Il registro è integro; questa pagina non è riuscita a leggerlo. Riprova fra un momento.",
    retry: "Riprova",
    empty: "Ancora niente di sigillato.",
    emptyBody: "Il registro parte dalla prima stima sigillata prima di un fischio d’inizio.",
  },
  limited: "campione limitato",
};

const DE: V3cRecordCopy = {
  fascia: {
    tab: "Register · nur aus dem Siegel-Register",
    title: "Jede Schätzung, und wie sie ausging",
    since: (d: string) => `Im Register seit ${d}`,
    sealed: (f: string, tn: string) => `${f} Fußball · ${tn} Tennis vor dem Anstoß versiegelt`,
    edit: "Nichts hier lässt sich nach der Veröffentlichung ändern.",
    unavailable: "Registerdaten nicht verfügbar",
  },
  kpi: {
    sealed: "Versiegelte Fußball-Schätzungen",
    sealedVs: (since: string, last: string, scored: string) => `${since} – ${last} · ${scored} mit Ergebnis abgerechnet`,
    brier: "Brier-Score · niedriger ist besser",
    ours: "Unsere Schätzung",
    market: "Markt, ohne Marge",
    ci: (lo: string, hi: string) => `95%-Intervall ${lo}–${hi}`,
    verdict: {
      market_better: "Der Markt ist etwas besser als wir. Wir veröffentlichen es trotzdem.",
      tie: "In dieser Stichprobe sind beide nicht zu unterscheiden. Wir veröffentlichen es so oder so.",
      ours_lower: "Unserer ist in dieser Stichprobe niedriger. Eine Stichprobe, kein Versprechen.",
    },
    diff: (d: string, lo: string, hi: string, n: string) => `Differenz ${d} (95%: ${lo} bis ${hi}) bei ${n} Spielen mit Markt beim Siegel.`,
    blend: "Fußball-Schätzung = 30% unser Modell + 70% der Markt, ohne Marge.",
    coverage: "Abdeckung",
    coverageMain: (paired: string, scored: string) => `${paired} von ${scored}`,
    coverageVs: "abgerechneten Spielen tragen die Marktquote zum Zeitpunkt des Siegels",
    coverageRest: (pending: string, orphans: string, paper: string) => `${pending} warten auf ein Ergebnis · ${orphans} nach Anstoß ohne Ergebnis · ${paper} ohne Markt versiegelt (Paper)`,
  },
  cal: {
    title: "Tritt eine 60% 60 von 100 Mal ein?",
    lede: "Kalibrierung: angegebene Wahrscheinlichkeit gegen tatsächliche Häufigkeit. Die Genauigkeit misst der Brier-Score oben.",
    fig: "Zuverlässigkeit · angegeben gegen beobachtet",
    figSub: (pairs: string, n: string) => `${pairs} Ausgänge aus ${n} Spielen · Balken sind 95%-Intervalle`,
    aria: "Zuverlässigkeitsdiagramm unserer Fußball-Schätzung und des Markts gegen die Diagonale perfekter Kalibrierung",
    ours: "unsere Schätzung",
    market: "Markt",
    diag: "perfekte Kalibrierung",
    xAxis: "angegebene Wahrscheinlichkeit",
    yAxis: "beobachtet",
    caption: "Hohle Punkte: weniger als 30 Ausgänge in der Klasse. Punktgröße folgt n.",
    binsTitle: "Nach Klasse, mit n",
    stated: "Angegeben",
    observed: "Beobachtet",
    pm: "±95%",
    n: "n",
    gap: "Abstand",
    limited: "kleine Stichprobe",
    binsNote: "Wilson-95%-Intervalle. Abstand = beobachtet − angegeben, in Punkten.",
  },
  weeks: {
    title: "Erwartet gegen beobachtet, pro Woche",
    sub: "Eine Bilanz ist Glück oder Messung; so erkennst du den Unterschied.",
    expected: "Erwartet: Summe der versiegelten Wahrscheinlichkeiten des wahrscheinlichsten Ausgangs",
    observed: "Beobachtet: wie oft dieser Ausgang eintrat",
    aria: "Erwartete gegen beobachtete Ausgänge, pro ISO-Woche",
    week: (d: string) => `Wo. ab ${d}`,
    caption: "Die Fehlerbalken sind das 95%-Intervall der beobachteten Anzahl. Wochen unter 30 Spielen: erwarteter Balken grau, n mit * markiert.",
    // final2: why the bars drop, settled/sealed under each week, break and current week
    why: "Niedrigere Balken heißen weniger abgeschlossene Spiele: Länderspielpausen stoppen die Top-Ligen, und diese Woche läuft noch.",
    counts: "Unter jeder Woche: Spiele mit Ergebnis / versiegelt.",
    awaiting: (n) => `${n} offen`,
    awaitingKey: "Offen: angepfiffen, Ergebnis noch nicht da.",
    breakTag: "Pause",
    breakKey: "Länderspielpause: kein versiegeltes Spiel der fünf Top-Ligen in dieser Woche.",
    nowTag: "Läuft",
    nowKey: "Diese Woche: läuft noch, unvollständig.",
  },
  tennis: {
    title: "Tennis, getrennt geführt",
    lede: "Im Tennis stammt die versiegelte Zahl vom Markt, keine eigene Schätzung: Wir zeigen nur Ergebnisse und die Zahl der Spiele.",
    label: "Marktbasierte Wahrscheinlichkeit",
    sealed: "Versiegelte Spiele",
    settled: "Abgerechnet",
    won: "Gewonnen",
    lost: "Verloren",
    void: "Ungültig",
    awaiting: "Ergebnis ausstehend",
    note: "Gewonnen = der gewählte Spieler gewann. Ohne Quote beim Siegel steht ein temperiertes Elo. Kein Brier, keine Kalibrierung.",
  },
  receipts: {
    title: "Belege, gewonnen wie verloren",
    filter: "Sport",
    all: "Alle",
    football: "Fußball",
    tennis: "Tennis",
    sealed: "Versiegelt (UTC)",
    match: "Spiel",
    read: "Gelesener Ausgang",
    price: "Quote",
    marketPct: "Markt-%",
    estimatePct: "Schätzung %",
    gap: "Abstand",
    result: "Ergebnis",
    fingerprint: "Fingerabdruck",
    draw: "Unentschieden",
    kickoff: "Anstoß",
    top: "Top-Ausgang · kein Pick gezeigt",
    pick: "Pick gezeigt",
    noMarket: "kein Markt beim Siegel",
    isMarket: "ist der Markt",
    marketBased: "marktbasiert",
    paper: "Paper",
    corrected: "korrigiert",
    verdict: { in_favour: "dafür", against: "dagegen", void: "ungültig", unresolved: "offen" } as Record<"in_favour" | "against" | "void" | "unresolved", string>,
    // ui2: la pill dell'esito accanto a ogni ricevuta (W/L/V sono la sigla internazionale, la parola è questa)
    outcome: { won: "Gewonnen", lost: "Verloren", void: "Ungültig", pending: "Offen" },
    older: "Ältere Belege",
    newer: "Neuere",
    page: (p: number) => `Seite ${p}`,
    scroll: "Seitlich scrollen für die ganze Zeile.",
    recipe: "Fingerabdruck = SHA-256 von v1|table|id|model|sealed at|p home|p draw|p away|price. Aus der Zeile nachrechenbar.",
    recipeNote: "Das Register speichert keinen Hash; dieser wird aus den versiegelten Feldern berechnet, nicht beim Siegel.",
    noReturn: "Keine Renditezahl: Sie wäre nicht unabhängig von uns.",
    fullHash: "Vollständiger SHA-256",
    empty: "Noch nichts abgerechnet. Eine versiegelte Schätzung erscheint hier, sobald ihr Spiel ein Ergebnis hat.",
    emptyFilter: "Noch keine abgerechneten Zeilen für diesen Sport.",
  },
  corr: {
    title: "Korrekturen, als Korrekturen gezeigt",
    lede: (n: string) => `Ein Ergebnis wird nie überschrieben: Eine Korrektur ist eine neue Zeile mit Grund. Bisher ${n}.`,
    when: "Korrigiert",
    match: "Spiel",
    change: "Vorher → nachher",
    reason: "Grund",
    cause: {
      late_result: (src: string) => `Ergebnis verspätet nachgeholt${src ? ` (Quelle: ${src})` : ""}`,
      postponed: (d: string) => `Um mehr als 48 Std. verschoben${d ? ` (auf ${d})` : ""}: ungültig`,
      no_pick_shown: () => "Kein Pick gezeigt: Das Label gewonnen/verloren wurde annulliert",
      late_fill: () => "Ergebnis verspätet eingetragen",
      other: () => "Korrektur",
    },
    byCause: "Nach Grund",
    settle: { won: "gewonnen", lost: "verloren", void: "ungültig", unresolved: "offen" } as Record<string, string>,
    none: "Kein Ergebnis wurde korrigiert.",
    unavailable: "Die Korrekturen wurden nicht geladen. Das Register bewahrt sie.",
  },
  state: {
    loading: "Register wird gelesen",
    errorTitle: "Das Register wurde nicht geladen.",
    errorBody: "Das Register ist intakt; diese Seite konnte es nicht lesen. Versuch es gleich noch einmal.",
    retry: "Erneut versuchen",
    empty: "Noch nichts versiegelt.",
    emptyBody: "Das Register beginnt mit der ersten Schätzung, die vor einem Anstoß versiegelt wird.",
  },
  limited: "kleine Stichprobe",
};

const ES: V3cRecordCopy = {
  fascia: {
    tab: "Registro · leído solo del registro sellado",
    title: "Cada estimación, y cómo se liquidó",
    since: (d: string) => `En el registro desde ${d}`,
    sealed: (f: string, tn: string) => `${f} de fútbol · ${tn} de tenis sellados antes del inicio`,
    edit: "Nada de aquí se puede editar tras su publicación.",
    unavailable: "datos del registro no disponibles",
  },
  kpi: {
    sealed: "Estimaciones de fútbol selladas",
    sealedVs: (since: string, last: string, scored: string) => `${since} – ${last} · ${scored} liquidadas con resultado`,
    brier: "Puntuación Brier · cuanto más baja, mejor",
    ours: "Nuestra estimación",
    market: "Mercado, sin margen",
    ci: (lo: string, hi: string) => `Intervalo del 95% ${lo}–${hi}`,
    verdict: {
      market_better: "El mercado es algo mejor que nosotros. Lo publicamos igualmente.",
      tie: "En esta muestra no se pueden distinguir. Lo publicamos en cualquier caso.",
      ours_lower: "La nuestra es más baja en esta muestra. Una muestra, no una promesa.",
    },
    diff: (d: string, lo: string, hi: string, n: string) => `Diferencia ${d} (95%: de ${lo} a ${hi}) en ${n} partidos con mercado al sellar.`,
    blend: "Estimación de fútbol = 30% nuestro modelo + 70% el mercado, sin margen.",
    coverage: "Cobertura",
    coverageMain: (paired: string, scored: string) => `${paired} de ${scored}`,
    coverageVs: "partidos liquidados llevan la cuota de mercado del momento del sello",
    coverageRest: (pending: string, orphans: string, paper: string) => `${pending} esperando resultado · ${orphans} pasado el inicio sin él · ${paper} sellados sin mercado (papel)`,
  },
  cal: {
    title: "¿Un 60% ocurre 60 veces de cada 100?",
    lede: "Calibración: probabilidad declarada frente a la frecuencia real. La precisión es la puntuación Brier de arriba.",
    fig: "Fiabilidad · declarada frente a observada",
    figSub: (pairs: string, n: string) => `${pairs} resultados de ${n} partidos · las barras son intervalos del 95%`,
    aria: "Diagrama de fiabilidad de nuestra estimación de fútbol y del mercado frente a la diagonal de calibración perfecta",
    ours: "nuestra estimación",
    market: "mercado",
    diag: "calibración perfecta",
    xAxis: "probabilidad declarada",
    yAxis: "observada",
    caption: "Marcas huecas: menos de 30 resultados en el intervalo. El tamaño del punto sigue a n.",
    binsTitle: "Por intervalo, con n",
    stated: "Declarada",
    observed: "Observada",
    pm: "±95%",
    n: "n",
    gap: "Diferencia",
    limited: "muestra limitada",
    binsNote: "Intervalos de Wilson al 95%. Diferencia = observada − declarada, en puntos.",
  },
  weeks: {
    title: "Esperado frente a observado, por semana",
    sub: "Un historial es suerte o medición; así se distingue.",
    expected: "Esperado: suma de las probabilidades selladas del resultado más probable",
    observed: "Observado: cuántas veces ocurrió ese resultado",
    aria: "Resultados esperados frente a observados, por semana ISO",
    week: (d: string) => `sem. del ${d}`,
    caption: "Los bigotes son el intervalo del 95% del recuento observado. Semanas con menos de 30 partidos: barra esperada gris, n con *.",
    // final2: why the bars drop, settled/sealed under each week, break and current week
    why: "Barras más bajas, menos partidos terminados: los parones de selecciones detienen las grandes ligas y esta semana aún se juega.",
    counts: "Bajo cada semana: partidos con resultado / sellados.",
    awaiting: (n) => `${n} pendientes`,
    awaitingKey: "Pendientes: ya empezados, resultado aún sin llegar.",
    breakTag: "Parón",
    breakKey: "Parón de selecciones: ningún partido sellado de las cinco grandes ligas esa semana.",
    nowTag: "En curso",
    nowKey: "Esta semana: en curso, incompleta.",
  },
  tennis: {
    title: "Tenis, aparte",
    lede: "En tenis el número sellado viene del mercado, no es una estimación propia: solo mostramos resultados y número de partidos.",
    label: "Probabilidad basada en el mercado",
    sealed: "Partidos sellados",
    settled: "Liquidados",
    won: "Ganados",
    lost: "Perdidos",
    void: "Nulos",
    awaiting: "Pendientes de resultado",
    note: "Ganado = ganó el jugador elegido. Sin cuota al sellar, figura un Elo templado. Sin Brier ni calibración.",
  },
  receipts: {
    title: "Comprobantes, aciertos y fallos por igual",
    filter: "Deporte",
    all: "Todos",
    football: "Fútbol",
    tennis: "Tenis",
    sealed: "Sellado (UTC)",
    match: "Partido",
    read: "Resultado leído",
    price: "Cuota",
    marketPct: "% de mercado",
    estimatePct: "% de estimación",
    gap: "Diferencia",
    result: "Resultado",
    fingerprint: "Huella",
    draw: "Empate",
    kickoff: "inicio",
    top: "resultado principal · sin selección mostrada",
    pick: "selección mostrada",
    noMarket: "sin mercado al sellar",
    isMarket: "es el mercado",
    marketBased: "del mercado",
    paper: "papel",
    corrected: "corregido",
    verdict: { in_favour: "a favor", against: "en contra", void: "nula", unresolved: "sin resolver" } as Record<"in_favour" | "against" | "void" | "unresolved", string>,
    // ui2: la pill dell'esito accanto a ogni ricevuta (W/L/V sono la sigla internazionale, la parola è questa)
    outcome: { won: "Acertada", lost: "Fallada", void: "Nula", pending: "Pendiente" },
    older: "Comprobantes anteriores",
    newer: "Más recientes",
    page: (p: number) => `Página ${p}`,
    scroll: "Desplázate de lado para ver la fila completa.",
    recipe: "Huella = SHA-256 de v1|table|id|model|sealed at|p home|p draw|p away|price. Recalcúlala desde la fila.",
    recipeNote: "El registro no guarda ningún hash; este se calcula a partir de los campos sellados, no en el momento del sello.",
    noReturn: "Sin cifra de rentabilidad: no sería independiente de nosotros.",
    fullHash: "SHA-256 completo",
    empty: "Aún no hay nada liquidado. Una estimación sellada aparece aquí cuando su partido tiene resultado.",
    emptyFilter: "Aún no hay filas liquidadas para este deporte.",
  },
  corr: {
    title: "Correcciones, mostradas como correcciones",
    lede: (n: string) => `Un resultado nunca se edita en su sitio: una corrección es una fila nueva con su motivo. ${n} hasta ahora.`,
    when: "Corregido",
    match: "Partido",
    change: "Antes → después",
    reason: "Motivo",
    cause: {
      late_result: (src: string) => `Resultado recuperado tarde${src ? ` (fuente: ${src})` : ""}`,
      postponed: (d: string) => `Aplazado más de 48 h${d ? ` (al ${d})` : ""}: nulo`,
      no_pick_shown: () => "No se mostró ninguna selección: la etiqueta acertada/fallada se anuló",
      late_fill: () => "Resultado completado tarde",
      other: () => "Corrección",
    },
    byCause: "Por motivo",
    settle: { won: "acertada", lost: "fallada", void: "nula", unresolved: "sin resolver" } as Record<string, string>,
    none: "No se ha corregido ningún resultado.",
    unavailable: "Las correcciones no se han cargado. El registro las guarda.",
  },
  state: {
    loading: "Leyendo el registro",
    errorTitle: "El registro no se ha cargado.",
    errorBody: "El registro está intacto; esta página no ha podido leerlo. Inténtalo de nuevo en un momento.",
    retry: "Reintentar",
    empty: "Aún no hay nada sellado.",
    emptyBody: "El registro empieza con la primera estimación sellada antes de un inicio.",
  },
  limited: "muestra limitada",
};

const FR: V3cRecordCopy = {
  fascia: {
    tab: "Registre · lu du seul registre scellé",
    title: "Chaque estimation, et son issue",
    since: (d: string) => `Au registre depuis le ${d}`,
    sealed: (f: string, tn: string) => `${f} football · ${tn} tennis scellés avant le coup d’envoi`,
    edit: "Rien ici ne peut être modifié après publication.",
    unavailable: "données du registre indisponibles",
  },
  kpi: {
    sealed: "Estimations football scellées",
    sealedVs: (since: string, last: string, scored: string) => `${since} – ${last} · ${scored} réglées avec un résultat`,
    brier: "Score de Brier · plus bas, c’est mieux",
    ours: "Notre estimation",
    market: "Marché, marge retirée",
    ci: (lo: string, hi: string) => `Intervalle à 95 % ${lo}–${hi}`,
    verdict: {
      market_better: "Le marché fait un peu mieux que nous. Nous le publions quand même.",
      tie: "Sur cet échantillon, impossible de les départager. Nous le publions dans tous les cas.",
      ours_lower: "Le nôtre est plus bas sur cet échantillon. Un échantillon, pas une promesse.",
    },
    diff: (d: string, lo: string, hi: string, n: string) => `Différence ${d} (95 % : ${lo} à ${hi}) sur ${n} matchs avec le marché au sceau.`,
    blend: "Estimation football = 30 % notre modèle + 70 % le marché, marge retirée.",
    coverage: "Couverture",
    coverageMain: (paired: string, scored: string) => `${paired} sur ${scored}`,
    coverageVs: "matchs réglés portent la cote du marché au moment du sceau",
    coverageRest: (pending: string, orphans: string, paper: string) => `${pending} en attente de résultat · ${orphans} après le coup d’envoi sans résultat · ${paper} scellés sans marché (papier)`,
  },
  cal: {
    title: "Un 60 % arrive-t-il 60 fois sur 100 ?",
    lede: "Calibration : probabilité annoncée face à sa fréquence réelle. La précision, c’est le score de Brier ci-dessus.",
    fig: "Fiabilité · annoncé face à observé",
    figSub: (pairs: string, n: string) => `${pairs} issues sur ${n} matchs · les barres sont des intervalles à 95 %`,
    aria: "Diagramme de fiabilité de notre estimation football et du marché face à la diagonale de calibration parfaite",
    ours: "notre estimation",
    market: "marché",
    diag: "calibration parfaite",
    xAxis: "probabilité annoncée",
    yAxis: "observé",
    caption: "Marques creuses : moins de 30 issues dans la classe. La taille du point suit n.",
    binsTitle: "Par classe, avec n",
    stated: "Annoncé",
    observed: "Observé",
    pm: "±95 %",
    n: "n",
    gap: "Écart",
    limited: "échantillon limité",
    binsNote: "Intervalles de Wilson à 95 %. Écart = observé − annoncé, en points.",
  },
  weeks: {
    title: "Attendu face à observé, par semaine",
    sub: "Un bilan, c’est de la chance ou de la mesure ; voici comment trancher.",
    expected: "Attendu : somme des probabilités scellées de l’issue la plus probable",
    observed: "Observé : la fréquence réelle de cette issue",
    aria: "Issues attendues face aux issues observées, par semaine ISO",
    week: (d: string) => `sem. du ${d}`,
    caption: "Les moustaches sont l’intervalle à 95 % du compte observé. Semaines sous 30 matchs : barre attendue en gris, n marqué *.",
    // final2: why the bars drop, settled/sealed under each week, break and current week
    why: "Des barres plus basses, moins de matchs terminés : les trêves internationales arrêtent les grands championnats et cette semaine se joue encore.",
    counts: "Sous chaque semaine : matchs avec résultat / scellés.",
    awaiting: (n) => `${n} en attente`,
    awaitingKey: "En attente : coup d’envoi passé, résultat pas encore arrivé.",
    breakTag: "Trêve",
    breakKey: "Trêve internationale : aucun match scellé des cinq grands championnats cette semaine-là.",
    nowTag: "En cours",
    nowKey: "Cette semaine : en cours, incomplète.",
  },
  tennis: {
    title: "Le tennis, à part",
    lede: "Au tennis, le chiffre scellé vient du marché, pas de notre estimation : seulement les résultats et le nombre de matchs.",
    label: "Probabilité issue du marché",
    sealed: "Matchs scellés",
    settled: "Réglés",
    won: "Gagnés",
    lost: "Perdus",
    void: "Annulés",
    awaiting: "En attente du résultat",
    note: "Gagné = le joueur choisi a gagné. Sans cote au sceau, un Elo tempéré la remplace. Ni Brier ni calibration.",
  },
  receipts: {
    title: "Justificatifs, gagnés comme perdus",
    filter: "Sport",
    all: "Tous",
    football: "Football",
    tennis: "Tennis",
    sealed: "Scellé (UTC)",
    match: "Match",
    read: "Issue lue",
    price: "Cote",
    marketPct: "% du marché",
    estimatePct: "% estimation",
    gap: "Écart",
    result: "Résultat",
    fingerprint: "Empreinte",
    draw: "Match nul",
    kickoff: "coup d’envoi",
    top: "issue principale · aucune sélection affichée",
    pick: "sélection affichée",
    noMarket: "pas de marché au sceau",
    isMarket: "est le marché",
    marketBased: "issu du marché",
    paper: "papier",
    corrected: "corrigé",
    verdict: { in_favour: "favorable", against: "défavorable", void: "annulé", unresolved: "non résolu" } as Record<"in_favour" | "against" | "void" | "unresolved", string>,
    // ui2: la pill dell'esito accanto a ogni ricevuta (W/L/V sono la sigla internazionale, la parola è questa)
    outcome: { won: "Gagné", lost: "Perdu", void: "Annulé", pending: "En attente" },
    older: "Justificatifs plus anciens",
    newer: "Plus récents",
    page: (p: number) => `Page ${p}`,
    scroll: "Faites défiler latéralement pour la ligne complète.",
    recipe: "Empreinte = SHA-256 de v1|table|id|model|sealed at|p home|p draw|p away|price. Recalculez-la depuis la ligne.",
    recipeNote: "Le registre ne stocke aucun hash ; celui-ci est calculé depuis les champs scellés, pas au moment du sceau.",
    noReturn: "Aucun chiffre de rendement : il ne serait pas indépendant de nous.",
    fullHash: "SHA-256 complet",
    empty: "Rien de réglé pour l’instant. Une estimation scellée apparaît ici dès que son match a un résultat.",
    emptyFilter: "Aucune ligne réglée pour ce sport pour l’instant.",
  },
  corr: {
    title: "Les corrections, affichées comme corrections",
    lede: (n: string) => `Un résultat n’est jamais modifié sur place : une correction est une nouvelle ligne avec sa raison. ${n} à ce jour.`,
    when: "Corrigé",
    match: "Match",
    change: "Avant → après",
    reason: "Raison",
    cause: {
      late_result: (src: string) => `Résultat récupéré en retard${src ? ` (source : ${src})` : ""}`,
      postponed: (d: string) => `Reporté au-delà de 48 h${d ? ` (au ${d})` : ""} : annulé`,
      no_pick_shown: () => "Aucune sélection n’était affichée : l’étiquette gagné/perdu a été annulée",
      late_fill: () => "Résultat saisi en retard",
      other: () => "Correction",
    },
    byCause: "Par raison",
    settle: { won: "gagné", lost: "perdu", void: "annulé", unresolved: "non résolu" } as Record<string, string>,
    none: "Aucun résultat n’a été corrigé.",
    unavailable: "Les corrections ne se sont pas chargées. Le registre les conserve.",
  },
  state: {
    loading: "Lecture du registre",
    errorTitle: "Le registre ne s’est pas chargé.",
    errorBody: "Le registre est intact ; cette page n’a pas pu le lire. Réessayez dans un instant.",
    retry: "Réessayer",
    empty: "Rien de scellé pour l’instant.",
    emptyBody: "Le registre commence avec la première estimation scellée avant un coup d’envoi.",
  },
  limited: "échantillon limité",
};

const NL: V3cRecordCopy = {
  fascia: {
    tab: "Register · enkel uit verzegeld register",
    title: "Elke schatting, en hoe ze afliep",
    since: (d: string) => `In het register sinds ${d}`,
    sealed: (f: string, tn: string) => `${f} voetbal · ${tn} tennis verzegeld vóór de aftrap`,
    edit: "Niets hier kan na publicatie worden gewijzigd.",
    unavailable: "registerdata niet beschikbaar",
  },
  kpi: {
    sealed: "Verzegelde voetbalschattingen",
    sealedVs: (since: string, last: string, scored: string) => `${since} – ${last} · ${scored} afgerekend met een uitslag`,
    brier: "Brier-score · lager is beter",
    ours: "Onze schatting",
    market: "Markt, zonder marge",
    ci: (lo: string, hi: string) => `95%-interval ${lo}–${hi}`,
    verdict: {
      market_better: "De markt is iets beter dan wij. We publiceren het toch.",
      tie: "Op deze steekproef zijn de twee niet uit elkaar te houden. We publiceren het hoe dan ook.",
      ours_lower: "De onze is lager op deze steekproef. Een steekproef, geen belofte.",
    },
    diff: (d: string, lo: string, hi: string, n: string) => `Verschil ${d} (95%: ${lo} tot ${hi}) over ${n} wedstrijden met de markt bij het zegel.`,
    blend: "Voetbalschatting = 30% ons model + 70% de markt, zonder marge.",
    coverage: "Dekking",
    coverageMain: (paired: string, scored: string) => `${paired} van ${scored}`,
    coverageVs: "afgerekende wedstrijden hebben de marktodd van het moment van het zegel",
    coverageRest: (pending: string, orphans: string, paper: string) => `${pending} wachten op een uitslag · ${orphans} na de aftrap zonder uitslag · ${paper} verzegeld zonder markt (papier)`,
  },
  cal: {
    title: "Gebeurt 60% ook 60 keer op 100?",
    lede: "Kalibratie: opgegeven kans tegenover hoe vaak het gebeurde. Nauwkeurigheid is de Brier-score hierboven.",
    fig: "Betrouwbaarheid · opgegeven tegenover waargenomen",
    figSub: (pairs: string, n: string) => `${pairs} uitkomsten uit ${n} wedstrijden · balken zijn 95%-intervallen`,
    aria: "Betrouwbaarheidsdiagram van onze voetbalschatting en van de markt tegenover de diagonaal van perfecte kalibratie",
    ours: "onze schatting",
    market: "markt",
    diag: "perfecte kalibratie",
    xAxis: "opgegeven kans",
    yAxis: "waargenomen",
    caption: "Holle punten: minder dan 30 uitkomsten in de klasse. De puntgrootte volgt n.",
    binsTitle: "Per klasse, met n",
    stated: "Opgegeven",
    observed: "Waargenomen",
    pm: "±95%",
    n: "n",
    gap: "Verschil",
    limited: "beperkte steekproef",
    binsNote: "Wilson 95%-intervallen. Verschil = waargenomen − opgegeven, in punten.",
  },
  weeks: {
    title: "Verwacht tegenover waargenomen, per week",
    sub: "Een register is geluk of meting; zo zie je het verschil.",
    expected: "Verwacht: som van de verzegelde kansen van de meest waarschijnlijke uitkomst",
    observed: "Waargenomen: hoe vaak die uitkomst gebeurde",
    aria: "Verwachte tegenover waargenomen uitkomsten, per ISO-week",
    week: (d: string) => `wk van ${d}`,
    caption: "Snorharen zijn het 95%-interval van het waargenomen aantal. Weken onder 30 wedstrijden: verwachte balk in grijs, n gemarkeerd met *.",
    // final2: why the bars drop, settled/sealed under each week, break and current week
    why: "Lagere balken betekenen minder afgeronde wedstrijden: interlandperiodes leggen de topcompetities stil en deze week loopt nog.",
    counts: "Onder elke week: wedstrijden met uitslag / verzegeld.",
    awaiting: (n) => `${n} wachtend`,
    awaitingKey: "Wachtend: afgetrapt, uitslag nog niet binnen.",
    breakTag: "Pauze",
    breakKey: "Interlandperiode: geen verzegelde wedstrijd van de vijf topcompetities die week.",
    nowTag: "Loopt",
    nowKey: "Deze week: loopt nog, onvolledig.",
  },
  tennis: {
    title: "Tennis, apart gehouden",
    lede: "Bij tennis komt het verzegelde getal van de markt, geen eigen schatting: we tonen alleen uitslagen en het aantal wedstrijden.",
    label: "Marktgebaseerde kans",
    sealed: "Verzegelde wedstrijden",
    settled: "Afgerekend",
    won: "Gewonnen",
    lost: "Verloren",
    void: "Ongeldig",
    awaiting: "Uitslag nog open",
    note: "Gewonnen = de gekozen speler won. Zonder odds bij het zegel staat een getemperde Elo. Geen Brier, geen kalibratie.",
  },
  receipts: {
    title: "Bewijzen, gewonnen en verloren gelijk",
    filter: "Sport",
    all: "Alle",
    football: "Voetbal",
    tennis: "Tennis",
    sealed: "Verzegeld (UTC)",
    match: "Wedstrijd",
    read: "Gelezen uitkomst",
    price: "Odds",
    marketPct: "Markt-%",
    estimatePct: "Schatting-%",
    gap: "Verschil",
    result: "Uitslag",
    fingerprint: "Vingerafdruk",
    draw: "Gelijkspel",
    kickoff: "aftrap",
    top: "topuitkomst · geen pick getoond",
    pick: "pick getoond",
    noMarket: "geen markt bij het zegel",
    isMarket: "is de markt",
    marketBased: "marktgebaseerd",
    paper: "papier",
    corrected: "gecorrigeerd",
    verdict: { in_favour: "in het voordeel", against: "tegen", void: "ongeldig", unresolved: "onbeslist" } as Record<"in_favour" | "against" | "void" | "unresolved", string>,
    // ui2: la pill dell'esito accanto a ogni ricevuta (W/L/V sono la sigla internazionale, la parola è questa)
    outcome: { won: "Gewonnen", lost: "Verloren", void: "Ongeldig", pending: "In afwachting" },
    older: "Oudere bewijzen",
    newer: "Nieuwere",
    page: (p: number) => `Pagina ${p}`,
    scroll: "Scrol opzij voor de volledige rij.",
    recipe: "Vingerafdruk = SHA-256 van v1|table|id|model|sealed at|p home|p draw|p away|price. Bereken hem opnieuw uit de rij.",
    recipeNote: "Het register slaat geen hash op; deze wordt berekend uit de verzegelde velden, niet bij het zegel.",
    noReturn: "Geen rendementscijfer: dat zou niet onafhankelijk van ons zijn.",
    fullHash: "Volledige SHA-256",
    empty: "Nog niets afgerekend. Een verzegelde schatting verschijnt hier zodra haar wedstrijd een uitslag heeft.",
    emptyFilter: "Nog geen afgerekende rijen voor deze sport.",
  },
  corr: {
    title: "Correcties, getoond als correcties",
    lede: (n: string) => `Een uitslag wordt nooit ter plekke gewijzigd: een correctie is een nieuwe rij met haar reden. Tot nu toe ${n}.`,
    when: "Gecorrigeerd",
    match: "Wedstrijd",
    change: "Voor → na",
    reason: "Reden",
    cause: {
      late_result: (src: string) => `Uitslag laat binnengehaald${src ? ` (bron: ${src})` : ""}`,
      postponed: (d: string) => `Uitgesteld met meer dan 48 u${d ? ` (naar ${d})` : ""}: ongeldig`,
      no_pick_shown: () => "Er was geen pick getoond: het label gewonnen/verloren is ongeldig verklaard",
      late_fill: () => "Uitslag laat ingevuld",
      other: () => "Correctie",
    },
    byCause: "Per reden",
    settle: { won: "gewonnen", lost: "verloren", void: "ongeldig", unresolved: "onbeslist" } as Record<string, string>,
    none: "Er is geen uitslag gecorrigeerd.",
    unavailable: "De correcties zijn niet geladen. Het register bewaart ze.",
  },
  state: {
    loading: "Het register lezen",
    errorTitle: "Het register is niet geladen.",
    errorBody: "Het register is intact; deze pagina kon het niet lezen. Probeer het zo opnieuw.",
    retry: "Opnieuw proberen",
    empty: "Nog niets verzegeld.",
    emptyBody: "Het register begint met de eerste schatting die vóór een aftrap is verzegeld.",
  },
  limited: "beperkte steekproef",
};

const PL: V3cRecordCopy = {
  fascia: {
    tab: "Rejestr · tylko z zapieczętowanej księgi",
    title: "Każdy szacunek i jak się rozliczył",
    since: (d: string) => `W rejestrze od ${d}`,
    sealed: (f: string, tn: string) => `Zapieczętowane przed początkiem: piłka nożna ${f} · tenis ${tn}`,
    edit: "Po publikacji niczego tutaj nie można edytować.",
    unavailable: "dane rejestru niedostępne",
  },
  kpi: {
    sealed: "Zapieczętowane szacunki piłkarskie",
    sealedVs: (since: string, last: string, scored: string) => `${since} – ${last} · rozliczone z wynikiem: ${scored}`,
    brier: "Wynik Briera · niższy jest lepszy",
    ours: "Nasz szacunek",
    market: "Rynek, bez marży",
    ci: (lo: string, hi: string) => `przedział 95% ${lo}–${hi}`,
    verdict: {
      market_better: "Rynek jest nieco lepszy od nas. Mimo to publikujemy wynik.",
      tie: "Na tej próbie nie da się ich rozróżnić. Publikujemy wynik tak czy inaczej.",
      ours_lower: "Na tej próbie nasz jest niższy. To próba, nie obietnica.",
    },
    diff: (d: string, lo: string, hi: string, n: string) => `Różnica ${d} (95%: od ${lo} do ${hi}) na ${n} meczach z rynkiem przy pieczęci.`,
    blend: "Szacunek piłkarski = 30% nasz model + 70% rynek, bez marży.",
    coverage: "Pokrycie",
    coverageMain: (paired: string, scored: string) => `${paired} z ${scored}`,
    coverageVs: "rozliczonych meczów ma kurs rynkowy z chwili pieczęci",
    coverageRest: (pending: string, orphans: string, paper: string) => `czeka na wynik: ${pending} · po początku bez wyniku: ${orphans} · zapieczętowane bez rynku (papier): ${paper}`,
  },
  cal: {
    title: "Czy 60% zdarza się 60 razy na 100?",
    lede: "Kalibracja: podane prawdopodobieństwo wobec tego, jak często się zdarzyło. Trafność mierzy wynik Briera powyżej.",
    fig: "Wiarygodność · podane wobec zaobserwowanego",
    figSub: (pairs: string, n: string) => `Wyniki: ${pairs}, z meczów: ${n} · słupki to przedziały 95%`,
    aria: "Wykres wiarygodności naszego szacunku piłkarskiego i rynku wobec przekątnej idealnej kalibracji",
    ours: "nasz szacunek",
    market: "rynek",
    diag: "idealna kalibracja",
    xAxis: "podane prawdopodobieństwo",
    yAxis: "zaobserwowane",
    caption: "Puste znaczniki: mniej niż 30 wyników w przedziale. Wielkość punktu zależy od n.",
    binsTitle: "Według przedziału, z n",
    stated: "Podane",
    observed: "Wynik",
    pm: "±95%",
    n: "n",
    gap: "Różnica",
    limited: "ograniczona próba",
    binsNote: "Przedziały Wilsona 95%. Różnica = zaobserwowane − podane, w punktach.",
  },
  weeks: {
    title: "Oczekiwane wobec zaobserwowanego, tydzień po tygodniu",
    sub: "Rejestr to szczęście albo pomiar; tak to rozróżnisz.",
    expected: "Oczekiwane: suma zapieczętowanych prawdopodobieństw najbardziej prawdopodobnego wyniku",
    observed: "Zaobserwowane: jak często ten wynik się zdarzył",
    aria: "Oczekiwane wobec zaobserwowanych wyników, według tygodnia ISO",
    week: (d: string) => `tydz. od ${d}`,
    caption: "Wąsy to przedział 95% zaobserwowanej liczby. Tygodnie poniżej 30 meczów: słupek oczekiwany na szaro, n oznaczone *.",
    // final2: why the bars drop, settled/sealed under each week, break and current week
    why: "Niższe słupki to mniej zakończonych meczów: przerwy na mecze reprezentacji wstrzymują topowe ligi, a ten tydzień jeszcze trwa.",
    counts: "Pod każdym tygodniem: mecze z wynikiem / zapieczętowane.",
    awaiting: (n) => `bez wyniku: ${n}`,
    awaitingKey: "Bez wyniku: mecz się zaczął, wynik jeszcze nie dotarł.",
    breakTag: "Przerwa",
    breakKey: "Przerwa reprezentacyjna: żadnego zapieczętowanego meczu pięciu topowych lig w tym tygodniu.",
    nowTag: "Trwa",
    nowKey: "Ten tydzień: trwa, niepełny.",
  },
  tennis: {
    title: "Tenis, osobno",
    lede: "W tenisie zapieczętowana liczba pochodzi z rynku, to nie nasz szacunek: pokazujemy tylko wyniki i liczbę meczów.",
    label: "Prawdopodobieństwo rynkowe",
    sealed: "Zapieczętowane mecze",
    settled: "Rozliczone",
    won: "Wygrane",
    lost: "Przegrane",
    void: "Unieważnione",
    awaiting: "Czekają na wynik",
    note: "Wygrana = wygrał wybrany zawodnik. Bez kursu przy pieczęci stoi temperowane Elo. Bez Briera i kalibracji.",
  },
  receipts: {
    title: "Potwierdzenia, trafione i nietrafione",
    filter: "Sport",
    all: "Wszystkie",
    football: "Piłka nożna",
    tennis: "Tenis",
    sealed: "Zapieczętowano (UTC)",
    match: "Mecz",
    read: "Odczytany wynik",
    price: "Kurs",
    marketPct: "% rynku",
    estimatePct: "% szacunku",
    gap: "Różnica",
    result: "Rezultat",
    fingerprint: "Odcisk",
    draw: "Remis",
    kickoff: "początek",
    top: "główny wynik · bez pokazanego typu",
    pick: "typ pokazany",
    noMarket: "brak rynku przy pieczęci",
    isMarket: "to rynek",
    marketBased: "z rynku",
    paper: "papier",
    corrected: "poprawione",
    verdict: { in_favour: "na korzyść", against: "przeciw", void: "anulowane", unresolved: "nierozstrzygnięte" } as Record<"in_favour" | "against" | "void" | "unresolved", string>,
    // ui2: la pill dell'esito accanto a ogni ricevuta (W/L/V sono la sigla internazionale, la parola è questa)
    outcome: { won: "Trafiony", lost: "Nietrafiony", void: "Anulowany", pending: "Oczekuje" },
    older: "Starsze potwierdzenia",
    newer: "Nowsze",
    page: (p: number) => `Strona ${p}`,
    scroll: "Przewiń w bok, by zobaczyć cały wiersz.",
    recipe: "Odcisk = SHA-256 z v1|table|id|model|sealed at|p home|p draw|p away|price. Przelicz go z wiersza.",
    recipeNote: "Księga nie przechowuje hasha; ten liczymy z zapieczętowanych pól, nie w chwili pieczęci.",
    noReturn: "Bez liczby zwrotu: nie byłaby od nas niezależna.",
    fullHash: "Pełny SHA-256",
    empty: "Nic jeszcze nie rozliczono. Zapieczętowany szacunek pojawi się tu, gdy mecz będzie miał wynik.",
    emptyFilter: "Brak rozliczonych wierszy dla tego sportu.",
  },
  corr: {
    title: "Poprawki, pokazane jako poprawki",
    lede: (n: string) => `Wyniku nigdy nie edytujemy w miejscu: poprawka to nowy wiersz z powodem. Dotąd: ${n}.`,
    when: "Poprawiono",
    match: "Mecz",
    change: "Przed → po",
    reason: "Powód",
    cause: {
      late_result: (src: string) => `Wynik odzyskany z opóźnieniem${src ? ` (źródło: ${src})` : ""}`,
      postponed: (d: string) => `Przełożony o ponad 48 h${d ? ` (na ${d})` : ""}: anulowany`,
      no_pick_shown: () => "Nie pokazano typu: etykietę trafiony/nietrafiony anulowano",
      late_fill: () => "Wynik uzupełniony z opóźnieniem",
      other: () => "Poprawka",
    },
    byCause: "Według powodu",
    settle: { won: "trafiony", lost: "nietrafiony", void: "anulowany", unresolved: "nierozstrzygnięty" } as Record<string, string>,
    none: "Żaden wynik nie został poprawiony.",
    unavailable: "Poprawki się nie wczytały. Księga je przechowuje.",
  },
  state: {
    loading: "Czytanie księgi",
    errorTitle: "Rejestr się nie wczytał.",
    errorBody: "Księga jest nienaruszona; ta strona nie mogła jej odczytać. Spróbuj za chwilę.",
    retry: "Spróbuj ponownie",
    empty: "Nic jeszcze nie zapieczętowano.",
    emptyBody: "Rejestr zaczyna się od pierwszego szacunku zapieczętowanego przed początkiem meczu.",
  },
  limited: "ograniczona próba",
};

const PT: V3cRecordCopy = {
  fascia: {
    tab: "Registo · lido só do registo selado",
    title: "Cada estimativa, e como foi liquidada",
    since: (d: string) => `Em registo desde ${d}`,
    sealed: (f: string, tn: string) => `${f} de futebol · ${tn} de ténis selados antes do início`,
    edit: "Nada aqui pode ser editado depois da publicação.",
    unavailable: "dados do registo indisponíveis",
  },
  kpi: {
    sealed: "Estimativas de futebol seladas",
    sealedVs: (since: string, last: string, scored: string) => `${since} – ${last} · ${scored} liquidadas com resultado`,
    brier: "Pontuação Brier · quanto mais baixa, melhor",
    ours: "A nossa estimativa",
    market: "Mercado, sem margem",
    ci: (lo: string, hi: string) => `intervalo de 95% ${lo}–${hi}`,
    verdict: {
      market_better: "O mercado é ligeiramente melhor do que nós. Publicamos na mesma.",
      tie: "Nesta amostra, os dois não se distinguem. Publicamos em qualquer caso.",
      ours_lower: "A nossa é mais baixa nesta amostra. Uma amostra, não uma promessa.",
    },
    diff: (d: string, lo: string, hi: string, n: string) => `Diferença ${d} (95%: ${lo} a ${hi}) em ${n} jogos com o mercado no selo.`,
    blend: "Estimativa de futebol = 30% o nosso modelo + 70% o mercado, sem margem.",
    coverage: "Cobertura",
    coverageMain: (paired: string, scored: string) => `${paired} de ${scored}`,
    coverageVs: "jogos liquidados têm a odd de mercado do momento do selo",
    coverageRest: (pending: string, orphans: string, paper: string) => `${pending} à espera de resultado · ${orphans} já começados sem resultado · ${paper} selados sem mercado (papel)`,
  },
  cal: {
    title: "Um 60% acontece 60 vezes em 100?",
    lede: "Calibração: probabilidade declarada contra a frequência com que aconteceu. A precisão é a pontuação Brier acima.",
    fig: "Fiabilidade · declarado contra observado",
    figSub: (pairs: string, n: string) => `${pairs} resultados de ${n} jogos · as barras são intervalos de 95%`,
    aria: "Diagrama de fiabilidade da nossa estimativa de futebol e do mercado contra a diagonal da calibração perfeita",
    ours: "a nossa estimativa",
    market: "mercado",
    diag: "calibração perfeita",
    xAxis: "probabilidade declarada",
    yAxis: "observado",
    caption: "Marcas vazias: menos de 30 resultados no intervalo. O tamanho do ponto segue n.",
    binsTitle: "Por intervalo, com n",
    stated: "Declarado",
    observed: "Observado",
    pm: "±95%",
    n: "n",
    gap: "Diferença",
    limited: "amostra limitada",
    binsNote: "Intervalos de Wilson a 95%. Diferença = observado − declarado, em pontos.",
  },
  weeks: {
    title: "Esperado contra observado, por semana",
    sub: "Um registo é sorte ou medida; é assim que se distingue.",
    expected: "Esperado: soma das probabilidades seladas do resultado mais provável",
    observed: "Observado: quantas vezes esse resultado aconteceu",
    aria: "Resultados esperados contra observados, por semana ISO",
    week: (d: string) => `sem. de ${d}`,
    caption: "Os bigodes são o intervalo de 95% da contagem observada. Semanas abaixo de 30 jogos: barra esperada a cinzento, n marcado *.",
    // final2: why the bars drop, settled/sealed under each week, break and current week
    why: "Barras mais baixas, menos jogos terminados: as pausas para seleções param as grandes ligas e esta semana ainda decorre.",
    counts: "Sob cada semana: jogos com resultado / selados.",
    awaiting: (n) => `${n} pendentes`,
    awaitingKey: "Pendentes: já começaram, resultado ainda por chegar.",
    breakTag: "Pausa",
    breakKey: "Pausa de seleções: nenhum jogo selado das cinco grandes ligas nessa semana.",
    nowTag: "A decorrer",
    nowKey: "Esta semana: a decorrer, incompleta.",
  },
  tennis: {
    title: "Ténis, à parte",
    lede: "No ténis o número selado vem do mercado, não é uma estimativa nossa: mostramos só resultados e o número de jogos.",
    label: "Probabilidade baseada no mercado",
    sealed: "Jogos selados",
    settled: "Liquidados",
    won: "Ganhos",
    lost: "Perdidos",
    void: "Anulados",
    awaiting: "À espera de resultado",
    note: "Ganho = o jogador escolhido ganhou. Sem odd no selo, fica um Elo temperado. Sem Brier nem calibração.",
  },
  receipts: {
    title: "Comprovativos, ganhos e perdidos por igual",
    filter: "Desporto",
    all: "Todos",
    football: "Futebol",
    tennis: "Ténis",
    sealed: "Selado (UTC)",
    match: "Jogo",
    read: "Resultado lido",
    price: "Odd",
    marketPct: "% de mercado",
    estimatePct: "% estimativa",
    gap: "Diferença",
    result: "Resultado",
    fingerprint: "Impressão digital",
    draw: "Empate",
    kickoff: "início",
    top: "resultado principal · nenhuma escolha mostrada",
    pick: "escolha mostrada",
    noMarket: "sem mercado no selo",
    isMarket: "é o mercado",
    marketBased: "do mercado",
    paper: "papel",
    corrected: "corrigido",
    verdict: { in_favour: "a favor", against: "contra", void: "anulado", unresolved: "por resolver" } as Record<"in_favour" | "against" | "void" | "unresolved", string>,
    // ui2: la pill dell'esito accanto a ogni ricevuta (W/L/V sono la sigla internazionale, la parola è questa)
    outcome: { won: "Ganho", lost: "Perdido", void: "Anulado", pending: "Pendente" },
    older: "Comprovativos anteriores",
    newer: "Mais recentes",
    page: (p: number) => `Página ${p}`,
    scroll: "Desliza para o lado para ver a linha inteira.",
    recipe: "Impressão digital = SHA-256 de v1|table|id|model|sealed at|p home|p draw|p away|price. Recalcula-a a partir da linha.",
    recipeNote: "O registo não guarda hash; este é calculado a partir dos campos selados, não no momento do selo.",
    noReturn: "Nenhum valor de retorno: não seria independente de nós.",
    fullHash: "SHA-256 completo",
    empty: "Ainda nada liquidado. Uma estimativa selada aparece aqui quando o seu jogo tiver resultado.",
    emptyFilter: "Ainda não há linhas liquidadas para este desporto.",
  },
  corr: {
    title: "Correções, mostradas como correções",
    lede: (n: string) => `Um resultado nunca é editado no lugar: uma correção é uma nova linha com o seu motivo. ${n} até agora.`,
    when: "Corrigido",
    match: "Jogo",
    change: "Antes → depois",
    reason: "Motivo",
    cause: {
      late_result: (src: string) => `Resultado recuperado tarde${src ? ` (fonte: ${src})` : ""}`,
      postponed: (d: string) => `Adiado para além de 48 h${d ? ` (para ${d})` : ""}: anulado`,
      no_pick_shown: () => "Nenhuma escolha foi mostrada: o rótulo ganho/perdido foi anulado",
      late_fill: () => "Resultado preenchido tarde",
      other: () => "Correção",
    },
    byCause: "Por motivo",
    settle: { won: "ganho", lost: "perdido", void: "anulado", unresolved: "por resolver" } as Record<string, string>,
    none: "Nenhum resultado foi corrigido.",
    unavailable: "As correções não carregaram. O registo guarda-as.",
  },
  state: {
    loading: "A ler o registo",
    errorTitle: "O registo não carregou.",
    errorBody: "O registo está intacto; esta página não o conseguiu ler. Tenta de novo daqui a pouco.",
    retry: "Tentar de novo",
    empty: "Ainda nada selado.",
    emptyBody: "O registo começa com a primeira estimativa selada antes de um início de jogo.",
  },
  limited: "amostra limitada",
};

const RU: V3cRecordCopy = {
  fascia: {
    tab: "Реестр · только из зафиксированных записей",
    title: "Каждая оценка и её итог",
    since: (d) => `В реестре с ${d}`,
    sealed: (f, tn) => `Футбол: ${f} · теннис: ${tn} — зафиксировано до начала`,
    edit: "После публикации здесь ничего нельзя изменить.",
    unavailable: "данные реестра недоступны",
  },
  kpi: {
    sealed: "Зафиксированные оценки по футболу",
    sealedVs: (since, last, scored) => `${since} – ${last} · с результатом: ${scored}`,
    brier: "Показатель Brier · чем ниже, тем лучше",
    ours: "Наша оценка",
    market: "Рынок, без маржи",
    ci: (lo, hi) => `95% интервал ${lo}–${hi}`,
    verdict: {
      market_better: "Рынок немного лучше нашей оценки. Мы всё равно это публикуем.",
      tie: "На этой выборке их не различить. Мы публикуем это в любом случае.",
      ours_lower: "На этой выборке наша ниже. Это выборка, а не обещание.",
    },
    diff: (d, lo, hi, n) => `Разница ${d} (95%: от ${lo} до ${hi}) на матчах с рынком при фиксации: ${n}.`,
    blend: "Оценка по футболу = 30% наша модель + 70% рынок без маржи.",
    coverage: "Покрытие",
    coverageMain: (paired, scored) => `${paired} из ${scored}`,
    coverageVs: "рассчитанных матчей имеют рыночный коэффициент на момент фиксации",
    coverageRest: (pending, orphans, paper) => `ждут результата: ${pending} · после начала без результата: ${orphans} · зафиксированы без рынка (бумажные): ${paper}`,
  },
  cal: {
    title: "Случаются ли 60% в 60 случаях из 100?",
    lede: "Калибровка: заявленная вероятность против того, как часто это происходило. Точность — это показатель Brier выше.",
    fig: "Надёжность · заявленное против наблюдаемого",
    figSub: (pairs, n) => `исходов: ${pairs}, матчей: ${n} · полосы — 95% интервалы`,
    aria: "Диаграмма надёжности нашей оценки по футболу и рынка относительно диагонали идеальной калибровки",
    ours: "наша оценка",
    market: "рынок",
    diag: "идеальная калибровка",
    xAxis: "заявленная вероятность",
    yAxis: "наблюдаемое",
    caption: "Пустые метки: в корзине меньше 30 исходов. Размер точки зависит от n.",
    binsTitle: "По корзинам, с n",
    stated: "Заявлено",
    observed: "Наблюдаемо",
    pm: "±95%",
    n: "n",
    gap: "Разрыв",
    limited: "ограниченная выборка",
    binsNote: "95% интервалы Уилсона. Разрыв = наблюдаемое − заявленное, в пунктах.",
  },
  weeks: {
    title: "Ожидаемое против наблюдаемого, по неделям",
    sub: "Реестр — это либо удача, либо измерение; так их различают.",
    expected: "Ожидаемое: сумма зафиксированных вероятностей самого вероятного исхода",
    observed: "Наблюдаемое: как часто этот исход случался",
    aria: "Ожидаемые и наблюдаемые исходы по неделям ISO",
    week: (d) => `нед. с ${d}`,
    caption: "Усы — 95% интервал наблюдаемого количества. Недели меньше чем с 30 матчами: ожидаемый столбец серый, n отмечено *.",
    // final2: why the bars drop, settled/sealed under each week, break and current week
    why: "Низкие столбцы — меньше завершённых матчей: паузы на сборные останавливают топ-лиги, а эта неделя ещё идёт.",
    counts: "Под каждой неделей: матчи с итогом / зафиксированные.",
    awaiting: (n) => `без итога: ${n}`,
    awaitingKey: "Без итога: матч начался, результата ещё нет.",
    breakTag: "Пауза",
    breakKey: "Пауза на сборные: ни одного зафиксированного матча пяти топ-лиг за эту неделю.",
    nowTag: "Идёт",
    nowKey: "Эта неделя: ещё идёт, неполная.",
  },
  tennis: {
    title: "Теннис — отдельно",
    lede: "В теннисе зафиксированное число основано на рынке, это не наша оценка: показываем только исходы и число матчей.",
    label: "Вероятность по рынку",
    sealed: "Зафиксировано матчей",
    settled: "Рассчитано",
    won: "Выигрыши",
    lost: "Проигрыши",
    void: "Аннулировано",
    awaiting: "Ждут результата",
    note: "Выигрыш = выбранный игрок победил. Без коэффициента при фиксации стоит смягчённый Elo. Ни Brier, ни калибровки.",
  },
  receipts: {
    title: "Квитанции — и выигрыши, и проигрыши",
    filter: "Спорт",
    all: "Все",
    football: "Футбол",
    tennis: "Теннис",
    sealed: "Зафиксировано (UTC)",
    match: "Матч",
    read: "Прочитанный исход",
    price: "Коэфф.",
    marketPct: "% рынка",
    estimatePct: "% оценки",
    gap: "Разрыв",
    result: "Результат",
    fingerprint: "Отпечаток",
    draw: "Ничья",
    kickoff: "начало",
    top: "главный исход · выбор не показан",
    pick: "выбор показан",
    noMarket: "нет рынка при фиксации",
    isMarket: "это рынок",
    marketBased: "по рынку",
    paper: "бумажная",
    corrected: "исправлено",
    verdict: { in_favour: "в пользу", against: "против", void: "возврат", unresolved: "не решено" },
    // ui2: la pill dell'esito accanto a ogni ricevuta (W/L/V sono la sigla internazionale, la parola è questa)
    outcome: { won: "Выигрыш", lost: "Проигрыш", void: "Возврат", pending: "Ожидает" },
    older: "Более старые квитанции",
    newer: "Новее",
    page: (p) => `Страница ${p}`,
    scroll: "Прокрутите вбок, чтобы увидеть всю строку.",
    recipe: "Отпечаток = SHA-256 от v1|table|id|model|sealed at|p home|p draw|p away|price. Пересчитайте его по строке.",
    recipeNote: "Реестр не хранит хеш; этот вычислен из зафиксированных полей, а не в момент фиксации.",
    noReturn: "Цифры доходности нет: она не была бы независимой от нас.",
    fullHash: "Полный SHA-256",
    empty: "Пока ничего не рассчитано. Зафиксированная оценка появится здесь, когда у матча будет результат.",
    emptyFilter: "Для этого вида спорта рассчитанных строк пока нет.",
  },
  corr: {
    title: "Исправления — как исправления",
    lede: (n) => `Результат никогда не правится на месте: исправление — новая строка с причиной. Пока исправлений: ${n}.`,
    when: "Исправлено",
    match: "Матч",
    change: "До → после",
    reason: "Причина",
    cause: {
      late_result: (src) => `Результат получен поздно${src ? ` (источник: ${src})` : ""}`,
      postponed: (d) => `Перенесён более чем на 48 ч${d ? ` (на ${d})` : ""}: возврат`,
      no_pick_shown: () => "Выбор не был показан: метка выигрыш/проигрыш аннулирована",
      late_fill: () => "Результат внесён поздно",
      other: () => "Исправление",
    },
    byCause: "По причине",
    settle: { won: "выигрыш", lost: "проигрыш", void: "возврат", unresolved: "не решено" },
    none: "Ни один результат не исправлялся.",
    unavailable: "Исправления не загрузились. Реестр их хранит.",
  },
  state: {
    loading: "Читаем реестр",
    errorTitle: "Реестр не загрузился.",
    errorBody: "Реестр цел; эта страница не смогла его прочитать. Попробуйте ещё раз через минуту.",
    retry: "Повторить",
    empty: "Пока ничего не зафиксировано.",
    emptyBody: "Реестр начинается с первой оценки, зафиксированной до начала матча.",
  },
  limited: "ограниченная выборка",
};

const SV: V3cRecordCopy = {
  fascia: {
    tab: "Register · bara från förseglat register",
    title: "Varje uppskattning, och hur den avgjordes",
    since: (d: string) => `I registret sedan ${d}`,
    sealed: (f: string, tn: string) => `${f} fotboll · ${tn} tennis förseglade före avspark`,
    edit: "Inget här kan ändras efter publicering.",
    unavailable: "registerdata inte tillgänglig",
  },
  kpi: {
    sealed: "Förseglade fotbollsuppskattningar",
    sealedVs: (since: string, last: string, scored: string) => `${since} – ${last} · ${scored} avgjorda med ett resultat`,
    brier: "Brier-poäng · lägre är bättre",
    ours: "Vår uppskattning",
    market: "Marknad, utan marginal",
    ci: (lo: string, hi: string) => `95 %-intervall ${lo}–${hi}`,
    verdict: {
      market_better: "Marknaden är något bättre än vår. Vi publicerar det ändå.",
      tie: "På det här urvalet går de två inte att skilja åt. Vi publicerar det oavsett.",
      ours_lower: "Vår är lägre på det här urvalet. Ett urval, inget löfte.",
    },
    diff: (d: string, lo: string, hi: string, n: string) => `Skillnad ${d} (95 %: ${lo} till ${hi}) på ${n} matcher med marknaden vid förseglingen.`,
    blend: "Fotbollsuppskattning = 30 % vår modell + 70 % marknaden, utan marginal.",
    coverage: "Täckning",
    coverageMain: (paired: string, scored: string) => `${paired} av ${scored}`,
    coverageVs: "avgjorda matcher har marknadsoddset från förseglingsögonblicket",
    coverageRest: (pending: string, orphans: string, paper: string) => `${pending} väntar på resultat · ${orphans} efter avspark utan resultat · ${paper} förseglade utan marknad (papper)`,
  },
  cal: {
    title: "Händer 60 % 60 gånger av 100?",
    lede: "Kalibrering: angiven sannolikhet mot hur ofta det hände. Träffsäkerheten är Brier-poängen ovan.",
    fig: "Tillförlitlighet · angiven mot observerad",
    figSub: (pairs: string, n: string) => `${pairs} utfall från ${n} matcher · staplarna är 95 %-intervall`,
    aria: "Tillförlitlighetsdiagram för vår fotbollsuppskattning och för marknaden mot diagonalen för perfekt kalibrering",
    ours: "vår uppskattning",
    market: "marknad",
    diag: "perfekt kalibrering",
    xAxis: "angiven sannolikhet",
    yAxis: "observerad",
    caption: "Ihåliga markeringar: färre än 30 utfall i gruppen. Punktens storlek följer n.",
    binsTitle: "Per grupp, med n",
    stated: "Angiven",
    observed: "Observerad",
    pm: "±95 %",
    n: "n",
    gap: "Skillnad",
    limited: "begränsat urval",
    binsNote: "Wilson 95 %-intervall. Skillnad = observerad − angiven, i punkter.",
  },
  weeks: {
    title: "Förväntat mot observerat, per vecka",
    sub: "Ett register är tur eller mätning; så här ser du skillnaden.",
    expected: "Förväntat: summan av förseglade sannolikheter för det mest troliga utfallet",
    observed: "Observerat: hur ofta det utfallet inträffade",
    aria: "Förväntade mot observerade utfall, per ISO-vecka",
    week: (d: string) => `v. från ${d}`,
    caption: "Morrhåren är 95 %-intervallet för observerat antal. Veckor under 30 matcher: förväntad stapel i grått, n markerat *.",
    // final2: why the bars drop, settled/sealed under each week, break and current week
    why: "Lägre staplar betyder färre avgjorda matcher: landslagsuppehåll pausar toppligorna och den här veckan pågår fortfarande.",
    counts: "Under varje vecka: matcher med resultat / förseglade.",
    awaiting: (n) => `${n} väntar`,
    awaitingKey: "Väntar: avspark gjord, resultatet har inte kommit än.",
    breakTag: "Uppehåll",
    breakKey: "Landslagsuppehåll: ingen förseglad match från de fem toppligorna den veckan.",
    nowTag: "Pågår",
    nowKey: "Den här veckan: pågår, ofullständig.",
  },
  tennis: {
    title: "Tennis, för sig",
    lede: "I tennis kommer den förseglade siffran från marknaden, ingen egen uppskattning: vi visar bara utfall och antal matcher.",
    label: "Marknadsbaserad sannolikhet",
    sealed: "Förseglade matcher",
    settled: "Avgjorda",
    won: "Vunna",
    lost: "Förlorade",
    void: "Ogiltiga",
    awaiting: "Väntar på resultat",
    note: "Vunnen = den valda spelaren vann. Utan odds vid förseglingen står en tempererad Elo. Ingen Brier, ingen kalibrering.",
  },
  receipts: {
    title: "Kvitton, vunna som förlorade",
    filter: "Sport",
    all: "Alla",
    football: "Fotboll",
    tennis: "Tennis",
    sealed: "Förseglad (UTC)",
    match: "Match",
    read: "Läst utfall",
    price: "Odds",
    marketPct: "Marknad %",
    estimatePct: "Uppskattning %",
    gap: "Skillnad",
    result: "Resultat",
    fingerprint: "Fingeravtryck",
    draw: "Oavgjort",
    kickoff: "avspark",
    top: "mest troliga utfall · inget val visat",
    pick: "val visat",
    noMarket: "ingen marknad vid försegling",
    isMarket: "är marknaden",
    marketBased: "marknadsbaserad",
    paper: "papper",
    corrected: "korrigerad",
    verdict: { in_favour: "till fördel", against: "emot", void: "ogiltig", unresolved: "ej avgjord" } as Record<"in_favour" | "against" | "void" | "unresolved", string>,
    // ui2: la pill dell'esito accanto a ogni ricevuta (W/L/V sono la sigla internazionale, la parola è questa)
    outcome: { won: "Vunnen", lost: "Förlorad", void: "Ogiltig", pending: "Väntar" },
    older: "Äldre kvitton",
    newer: "Nyare",
    page: (p: number) => `Sida ${p}`,
    scroll: "Scrolla i sidled för hela raden.",
    recipe: "Fingeravtryck = SHA-256 av v1|table|id|model|sealed at|p home|p draw|p away|price. Räkna om det från raden.",
    recipeNote: "Registret lagrar ingen hash; den här räknas fram ur de förseglade fälten, inte vid förseglingen.",
    noReturn: "Ingen avkastningssiffra: den vore inte oberoende av oss.",
    fullHash: "Hela SHA-256",
    empty: "Inget avgjort än. En förseglad uppskattning visas här när matchen har ett resultat.",
    emptyFilter: "Inga avgjorda rader för den här sporten än.",
  },
  corr: {
    title: "Korrigeringar, visade som korrigeringar",
    lede: (n: string) => `Ett resultat ändras aldrig på plats: en korrigering är en ny rad med sitt skäl. ${n} hittills.`,
    when: "Korrigerad",
    match: "Match",
    change: "Före → efter",
    reason: "Skäl",
    cause: {
      late_result: (src: string) => `Resultat hämtat i efterhand${src ? ` (källa: ${src})` : ""}`,
      postponed: (d: string) => `Uppskjuten mer än 48 h${d ? ` (till ${d})` : ""}: ogiltig`,
      no_pick_shown: () => "Inget val visades: etiketten vunnen/förlorad ogiltigförklarades",
      late_fill: () => "Resultat ifyllt i efterhand",
      other: () => "Korrigering",
    },
    byCause: "Per skäl",
    settle: { won: "vunnen", lost: "förlorad", void: "ogiltig", unresolved: "ej avgjord" } as Record<string, string>,
    none: "Inget resultat har korrigerats.",
    unavailable: "Korrigeringarna laddades inte. Registret sparar dem.",
  },
  state: {
    loading: "Läser registret",
    errorTitle: "Registret laddades inte.",
    errorBody: "Registret är intakt; sidan kunde inte läsa det. Försök igen om en stund.",
    retry: "Försök igen",
    empty: "Inget förseglat än.",
    emptyBody: "Registret börjar med den första uppskattningen som förseglas före en avspark.",
  },
  limited: "begränsat urval",
};

const TR: V3cRecordCopy = {
  fascia: {
    tab: "Kayıt defteri · sadece mühürlü kayıtlar",
    title: "Her tahmin ve nasıl sonuçlandığı",
    since: (d: string) => `${d} tarihinden beri kayıtta`,
    sealed: (f: string, tn: string) => `${f} futbol · ${tn} tenis, başlamadan önce mühürlendi`,
    edit: "Burada hiçbir şey yayından sonra düzenlenemez.",
    unavailable: "kayıt verisi kullanılamıyor",
  },
  kpi: {
    sealed: "Mühürlenen futbol tahminleri",
    sealedVs: (since: string, last: string, scored: string) => `${since} – ${last} · ${scored} tanesi bir sonuçla kapandı`,
    brier: "Brier skoru · düşük olan daha iyi",
    ours: "Tahminimiz",
    market: "Piyasa, marj hariç",
    ci: (lo: string, hi: string) => `%95 aralık ${lo}–${hi}`,
    verdict: {
      market_better: "Piyasa bizimkinden biraz daha iyi. Yine de yayınlıyoruz.",
      tie: "Bu örneklemde ikisi ayırt edilemiyor. Her durumda yayınlıyoruz.",
      ours_lower: "Bu örneklemde bizimki daha düşük. Bir örneklem, vaat değil.",
    },
    diff: (d: string, lo: string, hi: string, n: string) => `Mühürde piyasa oranı olan ${n} maçta fark ${d} (%95: ${lo} ile ${hi} arası).`,
    blend: "Futbol tahmini = %30 modelimiz + %70 piyasa, marj hariç.",
    coverage: "Kapsam",
    coverageMain: (paired: string, scored: string) => `${scored} maçın ${paired} tanesi`,
    coverageVs: "sonuçlanan maçlar mühür anındaki piyasa oranını taşır",
    coverageRest: (pending: string, orphans: string, paper: string) => `${pending} sonuç bekliyor · ${orphans} başladı ama sonucu yok · ${paper} piyasasız mühürlendi (kâğıt)`,
  },
  cal: {
    title: "%60, 100'de 60 kez gerçekleşiyor mu?",
    lede: "Kalibrasyon: belirtilen olasılık ile gerçekleşme sıklığı. İsabet, yukarıdaki Brier skorudur.",
    fig: "Güvenilirlik · belirtilen ve gözlenen",
    figSub: (pairs: string, n: string) => `${n} maçtan ${pairs} sonuç · çubuklar %95 aralıklardır`,
    aria: "Futbol tahminimizin ve piyasanın, mükemmel kalibrasyon köşegenine karşı güvenilirlik diyagramı",
    ours: "tahminimiz",
    market: "piyasa",
    diag: "mükemmel kalibrasyon",
    xAxis: "belirtilen olasılık",
    yAxis: "gözlenen",
    caption: "İçi boş işaretler: dilimde 30'dan az sonuç. Nokta boyutu n'yi izler.",
    binsTitle: "Dilime göre, n ile",
    stated: "Belirtilen",
    observed: "Gözlenen",
    pm: "±%95",
    n: "n",
    gap: "Fark",
    limited: "sınırlı örneklem",
    binsNote: "Wilson %95 aralıkları. Fark = gözlenen − belirtilen, puan olarak.",
  },
  weeks: {
    title: "Haftaya göre beklenen ve gözlenen",
    sub: "Bir kayıt ya şanstır ya ölçüm; ayırt etmenin yolu bu.",
    expected: "Beklenen: en olası sonucun mühürlü olasılıklarının toplamı",
    observed: "Gözlenen: o sonucun ne sıklıkla gerçekleştiği",
    aria: "ISO haftasına göre beklenen ve gözlenen sonuçlar",
    week: (d: string) => `${d} haftası`,
    caption: "Bıyıklar, gözlenen sayının %95 aralığıdır. 30 maçtan az haftalar: beklenen çubuk gri, n * ile işaretli.",
    // final2: why the bars drop, settled/sealed under each week, break and current week
    why: "Kısa çubuklar daha az sonuçlanmış maç demek: milli maç araları büyük ligleri durdurur ve bu hafta hâlâ oynanıyor.",
    counts: "Her haftanın altında: sonucu olan maçlar / mühürlü.",
    awaiting: (n) => `${n} bekliyor`,
    awaitingKey: "Bekliyor: maç başladı, sonuç henüz gelmedi.",
    breakTag: "Ara",
    breakKey: "Milli maç arası: o hafta beş büyük ligden mühürlü maç yok.",
    nowTag: "Sürüyor",
    nowKey: "Bu hafta: sürüyor, eksik.",
  },
  tennis: {
    title: "Tenis, ayrı tutuldu",
    lede: "Teniste mühürlü sayı piyasaya dayanır, kendi tahminimiz değildir: yalnızca sonuçları ve maç sayısını gösteriyoruz.",
    label: "Piyasaya dayalı olasılık",
    sealed: "Mühürlü maçlar",
    settled: "Sonuçlanan",
    won: "Kazanılan",
    lost: "Kaybedilen",
    void: "Geçersiz",
    awaiting: "Sonuç bekleyen",
    note: "Kazanılan = seçilen oyuncu kazandı. Mühürde oran yoksa ılımlaştırılmış Elo durur. Brier ve kalibrasyon yok.",
  },
  receipts: {
    title: "Makbuzlar, kazanan ve kaybeden aynı şekilde",
    filter: "Spor",
    all: "Tümü",
    football: "Futbol",
    tennis: "Tenis",
    sealed: "Mühürlendi (UTC)",
    match: "Maç",
    read: "Okunan sonuç",
    price: "Oran",
    marketPct: "Piyasa %",
    estimatePct: "Tahmin %",
    gap: "Fark",
    result: "Sonuç",
    fingerprint: "Parmak izi",
    draw: "Beraberlik",
    kickoff: "başlama",
    top: "en olası sonuç · seçim gösterilmedi",
    pick: "seçim gösterildi",
    noMarket: "mühürde piyasa yok",
    isMarket: "piyasanın kendisi",
    marketBased: "piyasaya dayalı",
    paper: "kâğıt",
    corrected: "düzeltildi",
    verdict: { in_favour: "lehte", against: "aleyhte", void: "geçersiz", unresolved: "belirsiz" },
    // ui2: la pill dell'esito accanto a ogni ricevuta (W/L/V sono la sigla internazionale, la parola è questa)
    outcome: { won: "Kazandı", lost: "Kaybetti", void: "Geçersiz", pending: "Bekliyor" },
    older: "Eski makbuzlar",
    newer: "Yeni",
    page: (p: number) => `Sayfa ${p}`,
    scroll: "Satırın tamamı için yana kaydır.",
    recipe: "Parmak izi = v1|table|id|model|sealed at|p home|p draw|p away|price değerinin SHA-256'sı. Satırdan yeniden hesapla.",
    recipeNote: "Defter hash saklamaz; bu, mühür anında değil, mühürlü alanlardan hesaplanır.",
    noReturn: "Getiri rakamı yok: bizden bağımsız olmazdı.",
    fullHash: "Tam SHA-256",
    empty: "Henüz sonuçlanan yok. Mühürlü bir tahmin, maçı sonuçlanınca burada görünür.",
    emptyFilter: "Bu spor için henüz sonuçlanan satır yok.",
  },
  corr: {
    title: "Düzeltmeler, düzeltme olarak gösterilir",
    lede: (n: string) => `Bir sonuç asla yerinde düzenlenmez: düzeltme, gerekçesiyle yeni bir satırdır. Şimdiye kadar ${n}.`,
    when: "Düzeltildi",
    match: "Maç",
    change: "Önce → sonra",
    reason: "Gerekçe",
    cause: {
      late_result: (src: string) => `Sonuç geç alındı${src ? ` (kaynak: ${src})` : ""}`,
      postponed: (d: string) => `48 saatten fazla ertelendi${d ? ` (${d} tarihine)` : ""}: geçersiz`,
      no_pick_shown: () => "Seçim gösterilmemişti: kazandı/kaybetti etiketi geçersiz sayıldı",
      late_fill: () => "Sonuç geç girildi",
      other: () => "Düzeltme",
    },
    byCause: "Gerekçeye göre",
    settle: { won: "kazandı", lost: "kaybetti", void: "geçersiz", unresolved: "belirsiz" },
    none: "Hiçbir sonuç düzeltilmedi.",
    unavailable: "Düzeltmeler yüklenmedi. Defter onları saklıyor.",
  },
  state: {
    loading: "Defter okunuyor",
    errorTitle: "Kayıt defteri yüklenmedi.",
    errorBody: "Defter sağlam; bu sayfa onu okuyamadı. Birazdan tekrar dene.",
    retry: "Tekrar dene",
    empty: "Henüz mühürlü bir şey yok.",
    emptyBody: "Kayıt, başlamadan önce mühürlenen ilk tahminle başlar.",
  },
  limited: "sınırlı örneklem",
};

export function recordCopyFor(lang: string | null | undefined): V3cRecordCopy {
  return V3C_RECORD_COPY[v3cLang(lang)];
}

export const V3C_RECORD_COPY: Record<V3cLang, V3cRecordCopy> = { en: EN, it: IT, de: DE, es: ES, fr: FR, nl: NL, pl: PL, pt: PT, ru: RU, sv: SV, tr: TR };

/**
 * The honest sentence is chosen by the data: the 95% interval of
 * (ours − market) on the paired rows. Entirely above 0 → the market is better;
 * across 0 → indistinguishable; entirely below 0 → ours lower «on this sample».
 */
export function brierVerdict(ci: { low: number; high: number } | null | undefined): BrierVerdict | null {
  if (!ci) return null;
  if (ci.low > 0) return "market_better";
  if (ci.high < 0) return "ours_lower";
  return "tie";
}
