// lib/v3c/copy-record.ts (#REDESIGN-V3C F6) — the copy of /record, EN source,
// IT complete, the other nine languages fall back to EN key by key (F10; keys
// listed in docs/v3c-i18n-keys.md). Own file so the parallel filoni do not
// collide on copy.ts.
// Lexicon: estimate · market · gap (pp) · sealed · receipt · record. Never ROI,
// CLV, hit-rate, win rate, «beat the market», guaranteed. Every claim here is
// a sentence the DATA picks (brierVerdict), not a fixed boast.

export type BrierVerdict = "market_better" | "tie" | "ours_lower";

const EN = {
  fascia: {
    tab: "Record · read only from the sealed ledger",
    title: "Every estimate, and how it settled",
    since: (d: string) => `On record since ${d}`,
    sealed: (f: string, tn: string) => `${f} football · ${tn} tennis sealed before kick-off`,
    edit: "Nothing here can be edited after publication.",
    unavailable: "record data unavailable",
  },
  kpi: {
    sealed: "Football estimates sealed",
    sealedVs: (since: string, last: string, scored: string) => `${since} – ${last} · ${scored} settled with a result`,
    brier: "Brier score · lower is better",
    ours: "Our estimate",
    market: "Market, margin removed",
    ci: (lo: string, hi: string) => `95% interval ${lo}–${hi}`,
    verdict: {
      market_better: "The market is slightly better than ours. We publish it anyway.",
      tie: "On this sample the two cannot be told apart. We publish it either way.",
      ours_lower: "Ours is lower on this sample. A sample, not a promise.",
    } as Record<BrierVerdict, string>,
    diff: (d: string, lo: string, hi: string, n: string) => `Difference ${d} (95%: ${lo} to ${hi}) on ${n} matches with the market at seal.`,
    blend: "Football estimate = 30% our model + 70% the market, margin removed.",
    coverage: "Coverage",
    coverageMain: (paired: string, scored: string) => `${paired} of ${scored}`,
    coverageVs: "settled matches carry the market price at the moment of the seal",
    coverageRest: (pending: string, orphans: string, paper: string) => `${pending} awaiting a result · ${orphans} past kick-off without one · ${paper} sealed with no market (paper)`,
  },
  cal: {
    title: "Does a 60% happen 60 times in 100?",
    lede: "Calibration: stated probability against how often it happened. Accuracy is the Brier score above.",
    fig: "Reliability · stated against observed",
    figSub: (pairs: string, n: string) => `${pairs} outcomes from ${n} matches · bars are 95% intervals`,
    aria: "Reliability diagram of our football estimate and of the market against the diagonal of perfect calibration",
    ours: "our estimate",
    market: "market",
    diag: "perfect calibration",
    xAxis: "stated probability",
    yAxis: "observed",
    caption: "Hollow marks: fewer than 30 outcomes in the bin. Dot size follows n.",
    binsTitle: "By bin, with n",
    stated: "Stated",
    observed: "Observed",
    pm: "±95%",
    n: "n",
    gap: "Gap",
    limited: "limited sample",
    binsNote: "Wilson 95% intervals. Gap = observed − stated, in points.",
  },
  weeks: {
    title: "Expected against observed, by week",
    sub: "A record is luck or measurement; this is how you tell.",
    expected: "Expected: sum of sealed probabilities of the most likely outcome",
    observed: "Observed: how often that outcome happened",
    aria: "Expected against observed outcomes, by ISO week",
    week: (d: string) => `wk of ${d}`,
    caption: "Whiskers are the 95% interval of the observed count. Weeks under 30 matches are marked.",
  },
  tennis: {
    title: "Tennis, kept apart",
    lede: "Most sealed tennis numbers are the market price, tempered. They are shown, never counted as ours.",
    group: "Group",
    what: "What the number is",
    settled: "Settled",
    expected: "Expected wins",
    observed: "Observed",
    brier: "Brier",
    vsMarket: "Against the market",
    isMarket: "is the market",
    ours: "our Elo",
    kindModel: "Our Elo model",
    kindModelTempered: "Our Elo, tempered (no price when sealed)",
    kindMarket: "Market price, margin removed, tempered",
    paired: (n: string, bp: string, bm: string) => `${n} with a price before the seal: ours ${bp}, market ${bm}`,
    pairedDiff: (d: string, lo: string, hi: string) => `difference ${d} (95%: ${lo} to ${hi})`,
    noPaired: "no book price before any seal",
    calInsufficient: (n: string, k: string) => `Too few of our own tennis estimates for a calibration curve: ${n} settled, ${k} bins with 30 or more.`,
    calSufficient: "Enough of our own tennis estimates for a calibration curve.",
    binary: "Binary Brier on the picked player: 0 perfect, 1 always wrong. Sealed values are whole percentages.",
  },
  receipts: {
    title: "Receipts, won and lost alike",
    filter: "Sport",
    all: "All",
    football: "Football",
    tennis: "Tennis",
    sealed: "Sealed (UTC)",
    match: "Match",
    read: "Outcome read",
    price: "Price",
    marketPct: "Market %",
    estimatePct: "Estimate %",
    gap: "Gap",
    result: "Result",
    fingerprint: "Fingerprint",
    draw: "Draw",
    kickoff: "kick-off",
    top: "top outcome · no pick shown",
    pick: "pick shown",
    noMarket: "no market at seal",
    isMarket: "is the market",
    paper: "paper",
    corrected: "corrected",
    verdict: { in_favour: "in favour", against: "against", void: "void", unresolved: "unresolved" } as Record<"in_favour" | "against" | "void" | "unresolved", string>,
    older: "Older receipts",
    newer: "Newer",
    page: (p: number) => `Page ${p}`,
    scroll: "Scroll sideways for the full row.",
    recipe: "Fingerprint = SHA-256 of v1|table|id|model|sealed at|p home|p draw|p away|price. Recompute it from the row.",
    recipeNote: "The ledger stores no hash; this one is computed from the sealed fields, not at the seal.",
    noReturn: "No return figure: it would not be independent of us.",
    fullHash: "Full SHA-256",
    empty: "Nothing settled yet. A sealed estimate appears here once its match has a result.",
    emptyFilter: "No settled rows for this sport yet.",
  },
  corr: {
    title: "Corrections, shown as corrections",
    lede: (n: string) => `A result is never edited in place: a correction is a new row with its reason. ${n} so far.`,
    when: "Corrected",
    match: "Match",
    change: "Before → after",
    reason: "Reason",
    cause: {
      late_result: (src: string) => `Result recovered late${src ? ` (source: ${src})` : ""}`,
      postponed: (d: string) => `Postponed beyond 48 h${d ? ` (to ${d})` : ""}: void`,
      no_pick_shown: () => "No pick was shown: the won/lost label was voided",
      late_fill: () => "Result filled in late",
      other: () => "Correction",
    },
    byCause: "By reason",
    settle: { won: "won", lost: "lost", void: "void", unresolved: "unresolved" } as Record<string, string>,
    none: "No result has been corrected.",
    unavailable: "Corrections didn’t load. The ledger keeps them.",
  },
  state: {
    loading: "Reading the ledger",
    errorTitle: "The record didn’t load.",
    errorBody: "The ledger is intact; this page couldn’t read it. Try again in a moment.",
    retry: "Try again",
    empty: "Nothing sealed yet.",
    emptyBody: "The record starts with the first estimate sealed before a kick-off.",
  },
  limited: "limited sample",
};

export type V3cRecordCopy = typeof EN;

const IT: V3cRecordCopy = {
  fascia: {
    tab: "Registro · letto solo dal registro sigillato",
    title: "Ogni stima, e come è finita",
    since: (d) => `Nel registro dal ${d}`,
    sealed: (f, tn) => `${f} calcio · ${tn} tennis sigillate prima del fischio`,
    edit: "Niente qui si può modificare dopo la pubblicazione.",
    unavailable: "dati del registro non disponibili",
  },
  kpi: {
    sealed: "Stime calcio sigillate",
    sealedVs: (since, last, scored) => `${since} – ${last} · ${scored} concluse con un esito`,
    brier: "Brier score · più basso è meglio",
    ours: "La nostra stima",
    market: "Mercato, senza margine",
    ci: (lo, hi) => `intervallo 95% ${lo}–${hi}`,
    verdict: {
      market_better: "Il mercato è leggermente meglio di noi. Lo pubblichiamo lo stesso.",
      tie: "Su questo campione i due non si distinguono. Lo pubblichiamo comunque.",
      ours_lower: "Il nostro è più basso su questo campione. Un campione, non una promessa.",
    },
    diff: (d, lo, hi, n) => `Differenza ${d} (95%: da ${lo} a ${hi}) su ${n} partite con il mercato al sigillo.`,
    blend: "Stima calcio = 30% il nostro modello + 70% il mercato senza margine.",
    coverage: "Copertura",
    coverageMain: (paired, scored) => `${paired} su ${scored}`,
    coverageVs: "partite concluse hanno il prezzo di mercato del momento del sigillo",
    coverageRest: (pending, orphans, paper) => `${pending} in attesa dell’esito · ${orphans} oltre il fischio senza esito · ${paper} sigillate senza mercato (paper)`,
  },
  cal: {
    title: "Un 60% succede 60 volte su 100?",
    lede: "Calibrazione: probabilità dichiarata contro quante volte è successo. L’accuratezza è il Brier qui sopra.",
    fig: "Affidabilità · dichiarato contro osservato",
    figSub: (pairs, n) => `${pairs} esiti da ${n} partite · le barre sono intervalli al 95%`,
    aria: "Diagramma di affidabilità della nostra stima calcio e del mercato rispetto alla diagonale della calibrazione perfetta",
    ours: "la nostra stima",
    market: "mercato",
    diag: "calibrazione perfetta",
    xAxis: "probabilità dichiarata",
    yAxis: "osservato",
    caption: "Segni vuoti: meno di 30 esiti nella fascia. La dimensione del punto segue n.",
    binsTitle: "Per fascia, con n",
    stated: "Dichiarato",
    observed: "Osservato",
    pm: "±95%",
    n: "n",
    gap: "Scarto",
    limited: "campione limitato",
    binsNote: "Intervalli di Wilson al 95%. Scarto = osservato − dichiarato, in punti.",
  },
  weeks: {
    title: "Atteso contro osservato, settimana per settimana",
    sub: "Un registro è fortuna o misura: così si distingue.",
    expected: "Atteso: somma delle probabilità sigillate dell’esito più probabile",
    observed: "Osservato: quante volte quell’esito è successo",
    aria: "Esiti attesi contro osservati, per settimana ISO",
    week: (d) => `sett. del ${d}`,
    caption: "I baffi sono l’intervallo al 95% del conteggio osservato. Le settimane sotto le 30 partite sono segnate.",
  },
  tennis: {
    title: "Il tennis, a parte",
    lede: "Quasi tutti i numeri tennis sigillati sono il prezzo di mercato, temperato. Li mostriamo, non li contiamo come nostri.",
    group: "Gruppo",
    what: "Cos’è il numero",
    settled: "Concluse",
    expected: "Vittorie attese",
    observed: "Osservate",
    brier: "Brier",
    vsMarket: "Contro il mercato",
    isMarket: "è il mercato",
    ours: "il nostro Elo",
    kindModel: "Il nostro modello Elo",
    kindModelTempered: "Il nostro Elo, temperato (nessun prezzo al sigillo)",
    kindMarket: "Prezzo di mercato senza margine, temperato",
    paired: (n, bp, bm) => `${n} con un prezzo prima del sigillo: noi ${bp}, mercato ${bm}`,
    pairedDiff: (d, lo, hi) => `differenza ${d} (95%: da ${lo} a ${hi})`,
    noPaired: "nessun prezzo dei book prima di un sigillo",
    calInsufficient: (n, k) => `Troppe poche stime tennis nostre per una curva di calibrazione: ${n} concluse, ${k} fasce con almeno 30.`,
    calSufficient: "Abbastanza stime tennis nostre per una curva di calibrazione.",
    binary: "Brier binario sul giocatore scelto: 0 perfetto, 1 sempre sbagliato. I valori sigillati sono percentuali intere.",
  },
  receipts: {
    title: "Le ricevute, vinte e perse",
    filter: "Sport",
    all: "Tutti",
    football: "Calcio",
    tennis: "Tennis",
    sealed: "Sigillo (UTC)",
    match: "Partita",
    read: "Esito letto",
    price: "Quota",
    marketPct: "Mercato %",
    estimatePct: "Stima %",
    gap: "Scarto",
    result: "Esito",
    fingerprint: "Impronta",
    draw: "Pareggio",
    kickoff: "inizio",
    top: "esito più probabile · nessuna pick mostrata",
    pick: "pick mostrata",
    noMarket: "nessun mercato al sigillo",
    isMarket: "è il mercato",
    paper: "paper",
    corrected: "corretta",
    verdict: { in_favour: "a favore", against: "contro", void: "annullata", unresolved: "non risolta" },
    older: "Ricevute più vecchie",
    newer: "Più recenti",
    page: (p) => `Pagina ${p}`,
    scroll: "Scorri di lato per la riga intera.",
    recipe: "Impronta = SHA-256 di v1|tabella|id|modello|sigillo|p casa|p pari|p trasferta|quota. Ricalcolabile dalla riga.",
    recipeNote: "Il registro non salva un hash: questo è calcolato dai campi sigillati, non al momento del sigillo.",
    noReturn: "Nessuna cifra di rendimento: non sarebbe indipendente da noi.",
    fullHash: "SHA-256 completo",
    empty: "Ancora niente di concluso. Una stima sigillata compare qui quando la sua partita ha un esito.",
    emptyFilter: "Ancora nessuna riga conclusa per questo sport.",
  },
  corr: {
    title: "Le correzioni, mostrate come correzioni",
    lede: (n) => `Un esito non si modifica mai sul posto: una correzione è una riga nuova con il suo motivo. Finora ${n}.`,
    when: "Corretta",
    match: "Partita",
    change: "Prima → dopo",
    reason: "Motivo",
    cause: {
      late_result: (src) => `Esito recuperato in ritardo${src ? ` (fonte: ${src})` : ""}`,
      postponed: (d) => `Rinviata oltre 48 h${d ? ` (al ${d})` : ""}: annullata`,
      no_pick_shown: () => "Nessuna pick mostrata: l’etichetta vinta/persa è stata annullata",
      late_fill: () => "Esito inserito in ritardo",
      other: () => "Correzione",
    },
    byCause: "Per motivo",
    settle: { won: "vinta", lost: "persa", void: "annullata", unresolved: "non risolta" },
    none: "Nessun esito è stato corretto.",
    unavailable: "Le correzioni non si sono caricate. Il registro le conserva.",
  },
  state: {
    loading: "Lettura del registro",
    errorTitle: "Il registro non si è caricato.",
    errorBody: "Il registro è integro; questa pagina non è riuscita a leggerlo. Riprova fra un momento.",
    retry: "Riprova",
    empty: "Ancora niente di sigillato.",
    emptyBody: "Il registro parte dalla prima stima sigillata prima di un fischio d’inizio.",
  },
  limited: "campione limitato",
};

export function recordCopyFor(lang: string | null | undefined): V3cRecordCopy {
  return lang === "it" ? IT : EN;
}

export const V3C_RECORD_COPY = { en: EN, it: IT };

/**
 * The honest sentence is chosen by the data: the 95% interval of
 * (ours − market) on the paired rows. Entirely above 0 → the market is better;
 * across 0 → indistinguishable; entirely below 0 → ours lower «on this sample».
 */
export function brierVerdict(ci: { low: number; high: number } | null | undefined): BrierVerdict | null {
  if (!ci) return null;
  if (ci.low > 0) return "market_better";
  if (ci.high < 0) return "ours_lower";
  return "tie";
}
