// lib/v3c/live-copy.ts (#V3C-LIVESCORES) — the words of the live scores, 11
// languages (glossary: docs/redesign/i18n-glossary.md). Checked by
// lib/v3c/i18n-parity.test.ts like every other v3c dictionary.
import { v3cLang, type V3cLang } from "./copy";

const EN = {
  live: "Live",
  /** football half-time, short (row badge) */
  ht: "HT",
  htLong: "Half-time",
  /** a break that is not half-time (end of regulation) */
  breakShort: "Break",
  ft: "FT",
  aet: "AET",
  pens: (h: number, a: number) => `Pens ${h}–${a}`,
  finished: "Finished",
  /** the same, short enough for the 44 px time column on a phone */
  finishedShort: "End",
  finishedNote: "Final score. The record updates when the result is settled.",
  notStarted: "Not started",
  off: "Suspended",
  unavailable: "Score n/a",
  unavailableLong: "Live score unavailable for this match right now.",
  set: (n: number) => `Set ${n}`,
  tb: "TB",
  ret: "Ret.",
  serving: (name: string) => `${name} serving`,
  goal: "Goal",
  ownGoal: "Own goal",
  penGoal: "Penalty",
  red: "Red card",
  liveNow: "Live now",
  liveNowCount: (n: number) => (n === 1 ? "1 match in play" : `${n} matches in play`),
  updated: (time: string) => `Updated ${time}`,
  source: "Scores from ESPN, refreshed while this page is open. Information only: not part of the record or estimates.",
  announceScore: (home: string, h: number, away: string, a: number) => `Score update: ${home} ${h}, ${away} ${a}`,
  announceFinal: (home: string, h: number, away: string, a: number) => `Final score: ${home} ${h}, ${away} ${a}`,
  setsAria: (sets: string) => `Sets ${sets}`,
  seeBoard: "All live matches",
};

export type V3cLiveCopy = typeof EN;

const IT: V3cLiveCopy = {
  live: "Live",
  ht: "Int.",
  htLong: "Intervallo",
  breakShort: "Pausa",
  ft: "Finale",
  aet: "dts",
  pens: (h, a) => `Rigori ${h}–${a}`,
  finished: "Finita",
  finishedShort: "Fine",
  finishedNote: "Risultato finale. Il registro si aggiorna quando l'esito è regolato.",
  notStarted: "Non iniziata",
  off: "Sospesa",
  unavailable: "Punteggio n.d.",
  unavailableLong: "Punteggio live non disponibile per questa partita adesso.",
  set: (n) => `Set ${n}`,
  tb: "TB",
  ret: "Rit.",
  serving: (name) => `Al servizio: ${name}`,
  goal: "Gol",
  ownGoal: "Autogol",
  penGoal: "Rigore",
  red: "Cartellino rosso",
  liveNow: "Live adesso",
  liveNowCount: (n) => (n === 1 ? "1 partita in corso" : `${n} partite in corso`),
  updated: (time) => `Aggiornato alle ${time}`,
  source: "Punteggi da ESPN, aggiornati finché la pagina è aperta. Solo informazione: non entrano nel registro né nelle stime.",
  announceScore: (home, h, away, a) => `Punteggio aggiornato: ${home} ${h}, ${away} ${a}`,
  announceFinal: (home, h, away, a) => `Risultato finale: ${home} ${h}, ${away} ${a}`,
  setsAria: (sets) => `Set ${sets}`,
  seeBoard: "Tutte le partite live",
};

const DE: V3cLiveCopy = {
  live: "Live",
  ht: "HZ",
  htLong: "Halbzeit",
  breakShort: "Pause",
  ft: "Ende",
  aet: "n.V.",
  pens: (h, a) => `i.E. ${h}–${a}`,
  finished: "Beendet",
  finishedShort: "Ende",
  finishedNote: "Endstand. Das Register wird aktualisiert, sobald das Ergebnis abgerechnet ist.",
  notStarted: "Noch nicht begonnen",
  off: "Unterbrochen",
  unavailable: "Kein Spielstand",
  unavailableLong: "Live-Spielstand für dieses Spiel gerade nicht verfügbar.",
  set: (n) => `Satz ${n}`,
  tb: "TB",
  ret: "Aufg.",
  serving: (name) => `${name} schlägt auf`,
  goal: "Tor",
  ownGoal: "Eigentor",
  penGoal: "Elfmeter",
  red: "Rote Karte",
  liveNow: "Jetzt live",
  liveNowCount: (n) => (n === 1 ? "1 Spiel läuft" : `${n} Spiele laufen`),
  updated: (time) => `Aktualisiert ${time}`,
  source: "Spielstände von ESPN, aktualisiert solange die Seite offen ist. Nur zur Information: nicht Teil von Register oder Schätzungen.",
  announceScore: (home, h, away, a) => `Neuer Spielstand: ${home} ${h}, ${away} ${a}`,
  announceFinal: (home, h, away, a) => `Endstand: ${home} ${h}, ${away} ${a}`,
  setsAria: (sets) => `Sätze ${sets}`,
  seeBoard: "Alle Live-Spiele",
};

const ES: V3cLiveCopy = {
  live: "En directo",
  ht: "Desc.",
  htLong: "Descanso",
  breakShort: "Pausa",
  ft: "Final",
  aet: "Prór.",
  pens: (h, a) => `Pen. ${h}–${a}`,
  finished: "Finalizado",
  finishedShort: "Fin",
  finishedNote: "Resultado final. El registro se actualiza cuando se liquida el resultado.",
  notStarted: "Sin empezar",
  off: "Suspendido",
  unavailable: "Marcador n/d",
  unavailableLong: "Marcador en directo no disponible ahora para este partido.",
  set: (n) => `Set ${n}`,
  tb: "TB",
  ret: "Ret.",
  serving: (name) => `Saca ${name}`,
  goal: "Gol",
  ownGoal: "Gol en propia",
  penGoal: "Penalti",
  red: "Tarjeta roja",
  liveNow: "En directo ahora",
  liveNowCount: (n) => (n === 1 ? "1 partido en juego" : `${n} partidos en juego`),
  updated: (time) => `Actualizado ${time}`,
  source: "Marcadores de ESPN, actualizados mientras la página está abierta. Solo información: fuera del registro y de las estimaciones.",
  announceScore: (home, h, away, a) => `Marcador actualizado: ${home} ${h}, ${away} ${a}`,
  announceFinal: (home, h, away, a) => `Resultado final: ${home} ${h}, ${away} ${a}`,
  setsAria: (sets) => `Sets ${sets}`,
  seeBoard: "Todos los partidos en directo",
};

const FR: V3cLiveCopy = {
  live: "En direct",
  ht: "MT",
  htLong: "Mi-temps",
  breakShort: "Pause",
  ft: "Fin",
  aet: "a.p.",
  pens: (h, a) => `t.a.b. ${h}–${a}`,
  finished: "Terminé",
  finishedShort: "Fin",
  finishedNote: "Score final. Le registre se met à jour quand le résultat est réglé.",
  notStarted: "Pas encore commencé",
  off: "Suspendu",
  unavailable: "Score indisp.",
  unavailableLong: "Score en direct indisponible pour ce match pour le moment.",
  set: (n) => `Set ${n}`,
  tb: "JD",
  ret: "Ab.",
  serving: (name) => `${name} au service`,
  goal: "But",
  ownGoal: "But contre son camp",
  penGoal: "Penalty",
  red: "Carton rouge",
  liveNow: "En direct maintenant",
  liveNowCount: (n) => (n === 1 ? "1 match en cours" : `${n} matchs en cours`),
  updated: (time) => `Mis à jour ${time}`,
  source: "Scores ESPN, actualisés tant que la page est ouverte. Information seulement : hors du registre et des estimations.",
  announceScore: (home, h, away, a) => `Nouveau score : ${home} ${h}, ${away} ${a}`,
  announceFinal: (home, h, away, a) => `Score final : ${home} ${h}, ${away} ${a}`,
  setsAria: (sets) => `Manches ${sets}`,
  seeBoard: "Tous les matchs en direct",
};

const NL: V3cLiveCopy = {
  live: "Live",
  ht: "Rust",
  htLong: "Rust",
  breakShort: "Pauze",
  ft: "Einde",
  aet: "n.v.",
  pens: (h, a) => `Pen. ${h}–${a}`,
  finished: "Afgelopen",
  finishedShort: "Einde",
  finishedNote: "Eindstand. Het register wordt bijgewerkt zodra de uitslag is verrekend.",
  notStarted: "Nog niet begonnen",
  off: "Gestaakt",
  unavailable: "Geen stand",
  unavailableLong: "Live stand voor deze wedstrijd nu niet beschikbaar.",
  set: (n) => `Set ${n}`,
  tb: "TB",
  ret: "Opg.",
  serving: (name) => `${name} serveert`,
  goal: "Doelpunt",
  ownGoal: "Eigen doelpunt",
  penGoal: "Strafschop",
  red: "Rode kaart",
  liveNow: "Nu live",
  liveNowCount: (n) => (n === 1 ? "1 wedstrijd bezig" : `${n} wedstrijden bezig`),
  updated: (time) => `Bijgewerkt ${time}`,
  source: "Standen van ESPN, ververst zolang de pagina open is. Alleen informatie: geen deel van het register of de schattingen.",
  announceScore: (home, h, away, a) => `Nieuwe stand: ${home} ${h}, ${away} ${a}`,
  announceFinal: (home, h, away, a) => `Eindstand: ${home} ${h}, ${away} ${a}`,
  setsAria: (sets) => `Sets ${sets}`,
  seeBoard: "Alle live wedstrijden",
};

const plPl = (n: number) => (n % 10 >= 2 && n % 10 <= 4 && (n % 100 < 12 || n % 100 > 14) ? `${n} mecze trwają` : `${n} meczów trwa`);
const PL: V3cLiveCopy = {
  live: "Na żywo",
  ht: "Przerwa",
  htLong: "Przerwa",
  breakShort: "Pauza",
  ft: "Koniec",
  aet: "Po dogr.",
  pens: (h, a) => `Karne ${h}–${a}`,
  finished: "Zakończony",
  finishedShort: "Kon.",
  finishedNote: "Wynik końcowy. Rejestr zaktualizuje się po rozliczeniu wyniku.",
  notStarted: "Nie rozpoczęty",
  off: "Przerwany",
  unavailable: "Brak wyniku",
  unavailableLong: "Wynik na żywo dla tego meczu jest teraz niedostępny.",
  set: (n) => `Set ${n}`,
  tb: "TB",
  ret: "Krecz",
  serving: (name) => `Serwuje ${name}`,
  goal: "Gol",
  ownGoal: "Samobój",
  penGoal: "Karny",
  red: "Czerwona kartka",
  liveNow: "Teraz na żywo",
  liveNowCount: (n) => (n === 1 ? "1 mecz trwa" : plPl(n)),
  updated: (time) => `Zaktualizowano ${time}`,
  source: "Wyniki z ESPN, odświeżane, gdy strona jest otwarta. Tylko informacja: nie wchodzą do rejestru ani szacunków.",
  announceScore: (home, h, away, a) => `Nowy wynik: ${home} ${h}, ${away} ${a}`,
  announceFinal: (home, h, away, a) => `Wynik końcowy: ${home} ${h}, ${away} ${a}`,
  setsAria: (sets) => `Sety ${sets}`,
  seeBoard: "Wszystkie mecze na żywo",
};

const PT: V3cLiveCopy = {
  live: "Ao vivo",
  ht: "Int.",
  htLong: "Intervalo",
  breakShort: "Pausa",
  ft: "Fim",
  aet: "Prol.",
  pens: (h, a) => `Pen. ${h}–${a}`,
  finished: "Terminado",
  finishedShort: "Fim",
  finishedNote: "Resultado final. O registo atualiza quando o resultado for liquidado.",
  notStarted: "Por começar",
  off: "Suspenso",
  unavailable: "Resultado n/d",
  unavailableLong: "Resultado ao vivo indisponível para este jogo neste momento.",
  set: (n) => `Set ${n}`,
  tb: "TB",
  ret: "Desist.",
  serving: (name) => `${name} a servir`,
  goal: "Golo",
  ownGoal: "Autogolo",
  penGoal: "Penálti",
  red: "Cartão vermelho",
  liveNow: "Ao vivo agora",
  liveNowCount: (n) => (n === 1 ? "1 jogo a decorrer" : `${n} jogos a decorrer`),
  updated: (time) => `Atualizado ${time}`,
  source: "Resultados da ESPN, atualizados enquanto a página está aberta. Só informação: fora do registo e das estimativas.",
  announceScore: (home, h, away, a) => `Resultado atualizado: ${home} ${h}, ${away} ${a}`,
  announceFinal: (home, h, away, a) => `Resultado final: ${home} ${h}, ${away} ${a}`,
  setsAria: (sets) => `Sets ${sets}`,
  seeBoard: "Todos os jogos ao vivo",
};

const ruCount = (n: number) => {
  const d = n % 10;
  const h = n % 100;
  if (d === 1 && h !== 11) return `${n} матч идёт`;
  if (d >= 2 && d <= 4 && (h < 12 || h > 14)) return `${n} матча идут`;
  return `${n} матчей идут`;
};
const RU: V3cLiveCopy = {
  live: "Live",
  ht: "Пер.",
  htLong: "Перерыв",
  breakShort: "Пауза",
  ft: "Конец",
  aet: "Доп. вр.",
  pens: (h, a) => `Пен. ${h}–${a}`,
  finished: "Завершён",
  finishedShort: "Конец",
  finishedNote: "Итоговый счёт. Реестр обновится после расчёта результата.",
  notStarted: "Не начался",
  off: "Прерван",
  unavailable: "Счёт н/д",
  unavailableLong: "Счёт в реальном времени сейчас недоступен для этого матча.",
  set: (n) => `Сет ${n}`,
  tb: "ТБ",
  ret: "Отказ",
  serving: (name) => `Подаёт ${name}`,
  goal: "Гол",
  ownGoal: "Автогол",
  penGoal: "Пенальти",
  red: "Красная карточка",
  liveNow: "Сейчас в эфире",
  liveNowCount: (n) => (n === 1 ? "1 матч идёт" : ruCount(n)),
  updated: (time) => `Обновлено ${time}`,
  source: "Счёт от ESPN, обновляется, пока страница открыта. Только информация: не входит в реестр и оценки.",
  announceScore: (home, h, away, a) => `Счёт изменился: ${home} ${h}, ${away} ${a}`,
  announceFinal: (home, h, away, a) => `Итоговый счёт: ${home} ${h}, ${away} ${a}`,
  setsAria: (sets) => `Сеты ${sets}`,
  seeBoard: "Все матчи в эфире",
};

const SV: V3cLiveCopy = {
  live: "Live",
  ht: "Paus",
  htLong: "Halvtid",
  breakShort: "Paus",
  ft: "Slut",
  aet: "e. förl.",
  pens: (h, a) => `Straffar ${h}–${a}`,
  finished: "Avslutad",
  finishedShort: "Slut",
  finishedNote: "Slutresultat. Registret uppdateras när resultatet är avräknat.",
  notStarted: "Ej startad",
  off: "Avbruten",
  unavailable: "Ingen ställning",
  unavailableLong: "Liveställning för matchen är inte tillgänglig just nu.",
  set: (n) => `Set ${n}`,
  tb: "TB",
  ret: "Utg.",
  serving: (name) => `${name} servar`,
  goal: "Mål",
  ownGoal: "Självmål",
  penGoal: "Straff",
  red: "Rött kort",
  liveNow: "Live nu",
  liveNowCount: (n) => (n === 1 ? "1 match pågår" : `${n} matcher pågår`),
  updated: (time) => `Uppdaterad ${time}`,
  source: "Ställningar från ESPN, uppdateras medan sidan är öppen. Endast information: ingår inte i registret eller uppskattningarna.",
  announceScore: (home, h, away, a) => `Ny ställning: ${home} ${h}, ${away} ${a}`,
  announceFinal: (home, h, away, a) => `Slutresultat: ${home} ${h}, ${away} ${a}`,
  setsAria: (sets) => `Set ${sets}`,
  seeBoard: "Alla livematcher",
};

const TR: V3cLiveCopy = {
  live: "Canlı",
  ht: "İY",
  htLong: "Devre arası",
  breakShort: "Ara",
  ft: "MS",
  aet: "UZ",
  pens: (h, a) => `Pen. ${h}–${a}`,
  finished: "Bitti",
  finishedShort: "Bitti",
  finishedNote: "Son skor. Kayıt defteri sonuç kesinleşince güncellenir.",
  notStarted: "Başlamadı",
  off: "Durduruldu",
  unavailable: "Skor yok",
  unavailableLong: "Bu maçın canlı skoru şu an mevcut değil.",
  set: (n) => `${n}. set`,
  tb: "TB",
  ret: "Çekildi",
  serving: (name) => `Servis: ${name}`,
  goal: "Gol",
  ownGoal: "Kendi kalesine",
  penGoal: "Penaltı",
  red: "Kırmızı kart",
  liveNow: "Şimdi canlı",
  liveNowCount: (n) => (n === 1 ? "1 maç oynanıyor" : `${n} maç oynanıyor`),
  updated: (time) => `Güncellendi ${time}`,
  source: "Skorlar ESPN'den, sayfa açıkken yenilenir. Yalnızca bilgi: kayıt defterine ve tahminlere girmez.",
  announceScore: (home, h, away, a) => `Skor güncellendi: ${home} ${h}, ${away} ${a}`,
  announceFinal: (home, h, away, a) => `Son skor: ${home} ${h}, ${away} ${a}`,
  setsAria: (sets) => `Setler ${sets}`,
  seeBoard: "Tüm canlı maçlar",
};

export const V3C_LIVE_COPY: Record<V3cLang, V3cLiveCopy> = { en: EN, it: IT, de: DE, es: ES, fr: FR, nl: NL, pl: PL, pt: PT, ru: RU, sv: SV, tr: TR };

export function liveCopyFor(lang: string | null | undefined): V3cLiveCopy {
  return V3C_LIVE_COPY[v3cLang(lang)];
}
