// lib/v3c/match-copy.ts (#REDESIGN-V3C F4)
// La copy della pagina partita e del price check. File del filone `match`,
// separato da lib/v3c/copy.ts per non scontrarsi con gli altri filoni. EN è la
// fonte, IT è completa, le altre nove lingue ricadono sull'inglese (F10: le
// chiavi sono in docs/v3c-i18n-keys-match.md). Lessico: market · estimate · gap
// in points · sealed · price · record — mai tip, lock, hot, guaranteed.

export type GapDir = "longer" | "shorter" | "flat";

const EN = {
  crumbsBoard: "Board",
  tabFootball: "Match · football",
  tabTennis: "Match · tennis",
  kickoffUtc: "UTC",
  s1: "Market against our estimate",
  market: "Market",
  marketSub: (label: string, price: string) => `${label} ${price} · margin removed`,
  estimate: "Estimate",
  estimateBlend: "70% market · 30% model",
  estimateModel: "model only · no market",
  gap: "Gap",
  gapSub: "estimate − market",
  explain: (label: string, price: string, m: number, e: number, n: string, dir: GapDir) =>
    dir === "flat"
      ? `${label} at ${price} implies ${m}%, margin removed. Our estimate: ${e}%. The price is in line with our number.`
      : `${label} at ${price} implies ${m}%, margin removed. Our estimate: ${e}%. The price is ${n} points ${dir} than our number.`,
  outcome: "Outcome",
  price: "Price",
  largest: "largest gap on this market",
  fair: (p: string) => `fair price ${p}`,
  wrongN: (e: number) => `A ${e}% estimate expects to be wrong ${100 - e} times in 100: the gap is about the price, not the match.`,
  noMarketLong: "No market price stored: the estimate is the model alone and there is no gap to show.",
  s2: "Why they differ, and what you can check",
  tapeCap: (label: string) => `${label} price · since our first capture`,
  tapeSub: (books: string, every: string | null) => `Decimal odds · ${books}${every ? ` · a capture every ${every}` : ""} · local time`,
  legendBook: (book: string) => `${book} price`,
  legendFair: (price: string, at: string) => `Our estimate as a fair price, ${price}, as of ${at}`,
  legendNews: "News, with its time",
  firstCapture: "First capture",
  newsAt: (time: string, label: string) => `News at ${time} · ${label}`,
  moved: (from: string, to: string) => `Price moved from ${from} to ${to}`,
  unchanged: (p: string) => `Price unchanged at ${p}`,
  single: (p: string) => `One price so far: ${p}`,
  movedBody: (n: number, since: string) => `${n} ${n === 1 ? "capture" : "captures"} since ${since}, connected books only. A move alone does not explain the gap.`,
  blendTitle: "Estimate = 70% market + 30% model",
  blendBody: "The model can move the number by 30% at most: most of the estimate is the market itself.",
  modelTitle: "Estimate = our model alone",
  modelBody: "No market price stored for this match, so nothing is blended and no gap is drawn.",
  sealTitle: "Sealed before kick-off",
  sealBody: (t: string) => `In the public ledger since ${t}. The latest estimate shown can differ from the sealed one.`,
  notSealed: "Not sealed yet",
  notSealedBody: "This match is not in the public ledger yet: there is nothing to verify against.",
  record: "View in the record",
  noTape: "No stored price history for this match yet: no chart, no line.",
  onePoint: (p: string, at: string) => `One capture so far: ${p} at ${at}. A line needs a second reading.`,
  tapeError: "The price history didn’t load. The numbers above are unaffected.",
  tapeAria: (label: string, from: string, to: string, n: number) => `${label} price from ${from} to ${to}, ${n} captures`,
  every: (min: number) => (min >= 60 ? `${Math.round(min / 6) / 10} h` : `${Math.round(min)} min`),
  outcomeChips: "Outcome shown in the chart",
  strip: (label: string, price: string) => `Check it yourself · prefilled with ${label} ${price}`,
  stripTennis: "Check the price yourself",
  allTools: "All 11 tools →",
  s3: "Where the price is best",
  bestAmong: (n: number) => (n === 0 ? "Connected books" : n === 1 ? "Price from 1 connected book" : `Best price among ${n} connected books`),
  partnerMeta: (label: string, n: number, at: string | null) => `${label} · ${n === 1 ? "1 book" : `${n} books`}${at ? ` · checked ${at}` : ""}`,
  bestLab: (book: string) => `Best price · ${book}`,
  cta: (book: string) => `Go to ${book}`,
  book: "Book",
  vsBest: "vs best",
  best: "best",
  oddsOnSite: "Odds on site",
  open: "Open",
  partnerFine: (at: string | null) => `Highest price among connected books${at ? ` at ${at}` : ""}. The book’s price at click is what counts.`,
  affiliates: "Affiliate links.",
  noBooks: "No connected book has a price for this outcome yet.",
  blocked: "Partner prices are not shown in your region.",
  pcBridge: "Your book shows another price? Check it →",
  more: "More on today’s board",
  allMatches: "The whole board →",
  loading: "Loading the match",
  errorTitle: "The match didn’t load.",
  errorBody: "The data source did not answer. A retry asks again.",
  retry: "Try again",
  notFoundTab: "Match · not found",
  notFoundTitle: "No match here",
  notFoundBody: "This link points to no match we price. It may be mistyped, or the fixture was never on the board.",
  backToBoard: "Back to the board",
  offBoard: "This match has left the board: it started over 150 minutes ago or sits outside the ten-day window. The price history stays.",
  tennisSealed: "Sealed",
  tennisMarketAtSeal: "Market at seal",
  tennisSealedEstimate: "Sealed estimate",
  tennisGapAtSeal: "gap at seal",
  tennisMarketOnlyBig: "Market, margin removed",
  tennisModelBig: "Our estimate",
  tennisSub: (kind: string) => kind,
  tnMarketOnly: "No model of ours here: the percentage is the book’s price, margin removed. A gap against itself is zero.",
  tnNotSealed: "Not sealed yet: the gap appears once our estimate is in the ledger.",
  tnNoMarketAtSeal: "No connected-book price in the 150 minutes before the seal, so no gap.",
  tnAnchored: "The sealed number is the market price itself, so a gap would be zero.",
  tnComing: "The gap arrives once a market/model split is stored for this match.",
  pc: {
    tab: "Price check · free",
    title: "What does this price claim?",
    choose: "Match",
    noMatch: "No match · just the maths",
    hint: "type your book’s prices",
    useBook: (b: string) => `${b}’s prices`,
    useMarket: "Market price",
    fill: "Fill with",
    verdict: (label: string, price: string, m: string, e: number, n: string, dir: GapDir) =>
      dir === "flat"
        ? { lead: `${label} at ${price}`, body: [` implies `, `${m}%`, `, margin removed. Our estimate: `, `${e}%`, `. The price is in line with our number.`] }
        : { lead: `${label} at ${price}`, body: [` implies `, `${m}%`, `, margin removed. Our estimate: `, `${e}%`, `. The price is ${n} points ${dir} than our number.`] },
    verdictNoEst: (sum: string, margin: string) => `These prices add up to ${sum}: the book keeps ${margin} of every stake.`,
    yourPrice: "Your price",
    implied: "Implied",
    noVig: "Margin removed",
    total: "Book margin",
    kept: (x: string) => `${x} kept`,
    under: "under 100%: no margin",
    invalid: "Type a decimal price above 1.00 in every box.",
    fine: "Implied = 1 ÷ price. Margin removed = implied ÷ the sum. Estimate: 70% market, 30% model.",
    fineNoEst: "Implied = 1 ÷ price. Margin removed = implied ÷ the sum. Pick a match to see our estimate next to it.",
    strip: "Go further with these prices",
    partnerTitle: "Does another book pay more?",
    youBeat: (price: string) => `Your ${price} is already at or above every connected book’s price.`,
    whyTitle: "Why the margin matters",
    whyBody: "Prices adding up past 100% hide the book’s fee. Removed, they show what the book believes; our estimate sits beside it.",
    outcomes: ["1", "X", "2"] as [string, string, string],
    openMatch: "Open the match →",
    loading: "Loading today’s matches",
  },
};

export type V3cMatchCopy = typeof EN;

const IT: V3cMatchCopy = {
  crumbsBoard: "Board",
  tabFootball: "Partita · calcio",
  tabTennis: "Partita · tennis",
  kickoffUtc: "UTC",
  s1: "Il mercato contro la nostra stima",
  market: "Mercato",
  marketSub: (label, price) => `${label} ${price} · margine tolto`,
  estimate: "Stima",
  estimateBlend: "70% mercato · 30% modello",
  estimateModel: "solo modello · senza mercato",
  gap: "Gap",
  gapSub: "stima − mercato",
  explain: (label, price, m, e, n, dir) =>
    dir === "flat"
      ? `${label} a ${price} vale ${m}%, margine tolto. La nostra stima: ${e}%. Il prezzo è in linea con il nostro numero.`
      : `${label} a ${price} vale ${m}%, margine tolto. La nostra stima: ${e}%. Il prezzo è ${n} punti più ${dir === "longer" ? "lungo" : "corto"} del nostro numero.`,
  outcome: "Esito",
  price: "Prezzo",
  largest: "il gap più ampio su questo mercato",
  fair: (p) => `prezzo equo ${p}`,
  wrongN: (e) => `Una stima del ${e}% si aspetta di sbagliare ${100 - e} volte su 100: il gap riguarda il prezzo, non la partita.`,
  noMarketLong: "Nessun prezzo di mercato archiviato: la stima è il solo modello e non c’è un gap da mostrare.",
  s2: "Perché differiscono, e cosa puoi verificare",
  tapeCap: (label) => `Prezzo ${label} · dalla prima cattura`,
  tapeSub: (books, every) => `Quote decimali · ${books}${every ? ` · una cattura ogni ${every}` : ""} · ora locale`,
  legendBook: (book) => `Prezzo ${book}`,
  legendFair: (price, at) => `La nostra stima come prezzo equo, ${price}, alle ${at}`,
  legendNews: "Notizia, con la sua ora",
  firstCapture: "Prima cattura",
  newsAt: (time, label) => `Notizia alle ${time} · ${label}`,
  moved: (from, to) => `Il prezzo è passato da ${from} a ${to}`,
  unchanged: (p) => `Prezzo fermo a ${p}`,
  single: (p) => `Un solo prezzo finora: ${p}`,
  movedBody: (n, since) => `${n} ${n === 1 ? "cattura" : "catture"} dal ${since}, solo book connessi. Un movimento da solo non spiega il gap.`,
  blendTitle: "Stima = 70% mercato + 30% modello",
  blendBody: "Il modello può spostare il numero al massimo del 30%: gran parte della stima è il mercato stesso.",
  modelTitle: "Stima = solo il nostro modello",
  modelBody: "Nessun prezzo di mercato archiviato per questa partita: niente blend e nessun gap disegnato.",
  sealTitle: "Sigillata prima del fischio",
  sealBody: (t) => `Nel registro pubblico dal ${t}. L’ultima stima mostrata può differire da quella sigillata.`,
  notSealed: "Non ancora sigillata",
  notSealedBody: "Questa partita non è ancora nel registro pubblico: non c’è nulla con cui verificarla.",
  record: "Vedi nel registro",
  noTape: "Nessuno storico prezzi archiviato per questa partita: niente grafico, niente linea.",
  onePoint: (p, at) => `Una sola cattura finora: ${p} alle ${at}. Per una linea serve una seconda lettura.`,
  tapeError: "Lo storico prezzi non si è caricato. I numeri sopra non cambiano.",
  tapeAria: (label, from, to, n) => `Prezzo ${label} da ${from} a ${to}, ${n} catture`,
  every: (min) => (min >= 60 ? `${String(Math.round(min / 6) / 10).replace(".", ",")} h` : `${Math.round(min)} min`),
  outcomeChips: "Esito mostrato nel grafico",
  strip: (label, price) => `Verifica tu · precompilato con ${label} ${price}`,
  stripTennis: "Verifica tu il prezzo",
  allTools: "Tutti gli 11 strumenti →",
  s3: "Dove il prezzo è migliore",
  bestAmong: (n) => (n === 0 ? "Book connessi" : n === 1 ? "Prezzo da 1 book connesso" : `Miglior prezzo fra ${n} book connessi`),
  partnerMeta: (label, n, at) => `${label} · ${n === 1 ? "1 book" : `${n} book`}${at ? ` · controllato alle ${at}` : ""}`,
  bestLab: (book) => `Miglior prezzo · ${book}`,
  cta: (book) => `Vai su ${book}`,
  book: "Book",
  vsBest: "vs migliore",
  best: "migliore",
  oddsOnSite: "Quote sul sito",
  open: "Apri",
  partnerFine: (at) => `Il prezzo più alto fra i book connessi${at ? ` alle ${at}` : ""}. Conta il prezzo del book al clic.`,
  affiliates: "Link affiliati.",
  noBooks: "Nessun book connesso ha ancora un prezzo per questo esito.",
  blocked: "I prezzi dei partner non si mostrano nella tua regione.",
  pcBridge: "Il tuo book ha un altro prezzo? Controllalo →",
  more: "Altro sulla board di oggi",
  allMatches: "Tutta la board →",
  loading: "Caricamento della partita",
  errorTitle: "La partita non si è caricata.",
  errorBody: "La fonte dati non ha risposto. Un nuovo tentativo richiede di nuovo.",
  retry: "Riprova",
  notFoundTab: "Partita · non trovata",
  notFoundTitle: "Nessuna partita qui",
  notFoundBody: "Questo link non porta a nessuna partita che prezziamo. Forse è scritto male, o la partita non è mai stata sulla board.",
  backToBoard: "Torna alla board",
  offBoard: "Questa partita è uscita dalla board: è iniziata da oltre 150 minuti o è fuori dalla finestra di dieci giorni. Lo storico prezzi resta.",
  tennisSealed: "Sigillata",
  tennisMarketAtSeal: "Mercato al sigillo",
  tennisSealedEstimate: "Stima sigillata",
  tennisGapAtSeal: "gap al sigillo",
  tennisMarketOnlyBig: "Mercato, margine tolto",
  tennisModelBig: "La nostra stima",
  tennisSub: (kind) => kind,
  tnMarketOnly: "Nessun nostro modello qui: la percentuale è il prezzo del book, margine tolto. Un gap contro sé stesso è zero.",
  tnNotSealed: "Non ancora sigillata: il gap compare quando la nostra stima entra nel registro.",
  tnNoMarketAtSeal: "Nessun prezzo dei book connessi nei 150 minuti prima del sigillo: niente gap.",
  tnAnchored: "Il numero sigillato è il prezzo di mercato stesso: il gap sarebbe zero.",
  tnComing: "Il gap arriva quando la separazione mercato/modello sarà archiviata per questa partita.",
  pc: {
    tab: "Controllo prezzo · gratis",
    title: "Cosa dice questo prezzo?",
    choose: "Partita",
    noMatch: "Nessuna partita · solo i conti",
    hint: "scrivi i prezzi del tuo book",
    useBook: (b) => `Prezzi ${b}`,
    useMarket: "Prezzo di mercato",
    fill: "Riempi con",
    verdict: (label, price, m, e, n, dir) =>
      dir === "flat"
        ? { lead: `${label} a ${price}`, body: [` vale `, `${m}%`, `, margine tolto. La nostra stima: `, `${e}%`, `. Il prezzo è in linea con il nostro numero.`] }
        : { lead: `${label} a ${price}`, body: [` vale `, `${m}%`, `, margine tolto. La nostra stima: `, `${e}%`, `. Il prezzo è ${n} punti più ${dir === "longer" ? "lungo" : "corto"} del nostro numero.`] },
    verdictNoEst: (sum, margin) => `Questi prezzi sommano a ${sum}: il book trattiene ${margin} di ogni puntata.`,
    yourPrice: "Il tuo prezzo",
    implied: "Implicita",
    noVig: "Margine tolto",
    total: "Margine del book",
    kept: (x) => `${x} trattenuto`,
    under: "sotto il 100%: nessun margine",
    invalid: "Scrivi una quota decimale sopra 1,00 in ogni casella.",
    fine: "Implicita = 1 ÷ prezzo. Margine tolto = implicita ÷ la somma. Stima: 70% mercato, 30% modello.",
    fineNoEst: "Implicita = 1 ÷ prezzo. Margine tolto = implicita ÷ la somma. Scegli una partita per vedere la nostra stima accanto.",
    strip: "Vai oltre con questi prezzi",
    partnerTitle: "Un altro book paga di più?",
    youBeat: (price) => `Il tuo ${price} è già pari o sopra il prezzo di ogni book connesso.`,
    whyTitle: "Perché il margine conta",
    whyBody: "Prezzi che sommano più del 100% nascondono la commissione del book. Tolta, mostrano cosa crede il book; la nostra stima sta lì accanto.",
    outcomes: ["1", "X", "2"],
    openMatch: "Apri la partita →",
    loading: "Caricamento delle partite di oggi",
  },
};

export const V3C_MATCH_COPY = { en: EN, it: IT };

/** Tutto ciò che non è `it` legge l'inglese (stessa regola di copyFor). */
export function matchCopyFor(lang: string | null | undefined): V3cMatchCopy {
  return lang === "it" ? IT : EN;
}
