// lib/v3c/pages-copy.ts (#REDESIGN-V3C · filone pages)
// La copy di News · Books · Pro · Metodo e del paywall «why». EN è la fonte, IT è
// completa; le altre nove lingue ricadono sull'inglese (F10 le completa, chiavi in
// docs/redesign/v3c-pages-i18n-keys.md). ≤22 parole per elemento.
// Lessico (POSITIONING §2): market · estimate · gap (in points) · sealed · record ·
// explain. Mai: beat the market, ROI, CLV, hit rate, guaranteed, lock, sure win.
// Nessun numero qui dentro: prezzi e conteggi arrivano dalle fonti (commercial-plan,
// board, catalogo partner) come argomenti.

export type PagesLang = "en" | "it";

const EN = {
  pricing: {
    tab: "Plans · two, no trial tricks",
    title: "Free shows the gap. Pro shows why.",
    metaStrong: (monthly: string) => `Pro ${monthly} a month`,
    metaRest: "Prices in USD. The card subscription is cancelled from your account.",
    freeName: "Free",
    freeLede: "The whole reading, free.",
    proName: "Pro",
    proLede: "The why behind the number, and more depth.",
    perMonth: "/ month",
    perYear: (annual: string) => `· ${annual} a year`,
    included: "Included",
    pro: "Pro",
    notLive: "Not live yet",
    free: [
      ["Today’s board", "every match: market, estimate and the signed gap"],
      ["The record", "every sealed estimate, won and lost"],
      ["Price check and 11 tools", "no account needed"],
      ["Watchlist", "the matches you follow, saved on this device"],
    ] as [string, string][],
    freeSoon: ["Alerts and bet tracker", "planned for Free; not live yet"] as [string, string],
    proItems: [
      ["Why the model disagrees", "each factor behind the estimate: form, venue, goals"],
      ["Full line movement", "every stored price since the market opened"],
      ["Live probabilities", "the estimate updates during the match"],
      ["Probability view", "combine markets on one match, model against market"],
      ["Weekly Model Case", "a worked example of how the model reads a week; not a bet to place"],
    ] as [string, string][],
    everythingFree: "Everything in Free",
    freeCta: "Create a free account",
    proCta: "Go Pro",
    railCard: "Card: a subscription that renews monthly; cancel it from your account.",
    railCardAnnual: "Yearly by card: renews every 12 months.",
    railCrypto: "Crypto: one payment for 30 days, no renewal.",
    railPaypal: "PayPal: available at checkout.",
    railUsdt: "USDT (TRC20) transfer: one payment, checked by hand.",
    withdrawal: "Before paying you confirm that Pro starts at once, which ends the 14-day withdrawal right.",
    promo: (until: string) => `Launch offer: the first purchase is half price until ${until}. It applies at checkout.`,
    sameStrong: "Same in both:",
    same: "every price, estimate, gap and the whole record. Pro never hides a number Free shows; it adds the why.",
    anatomyTitle: "What Pro opens on a match",
    anatomyLede: "Factor titles are visible to everyone. The first is explained in Free; the rest open with Pro.",
    anatomyNever: "Never shown when estimate and market agree (gap under 1.5 points).",
    fine: "Analysis, not advice. 18+. BetRedge is not a bookmaker and takes no bets.",
  },
  paywall: {
    lab: "Pro · the why",
    title: "Unlock why the model disagrees",
    lede: "See the factors that move our estimate away from the market price on this match. Analysis only, not advice. 18+.",
    blend: "Football estimates start from the market (70%); the model moves them (30%).",
    open: "Open in Free",
    closed: "Opens with Pro",
    cta: (price: string) => `See Pro · ${price}/month`,
    cancel: "Cancel the card subscription anytime from your account.",
    factorKinds: [
      ["Form", "Recent results of both sides, counted, not weighted by feeling."],
      ["Venue", "Home and away records this season, and how far apart they are."],
      ["Goals", "Expected goals for and against, where the data exists."],
    ] as [string, string][],
    example: "Layout example: titles only, no match data.",
  },
  news: {
    tab: "News · guides and match notes",
    title: "What moves a price",
    metaStrong: (n: number) => (n === 1 ? "1 article" : `${n} articles`),
    metaRest: "written by us; numbers explained, no picks",
    guide: "Guide",
    read: "Read",
    minutes: (m: number) => `${m} min read`,
    empty: "No articles published yet.",
    emptySub: "The board is live meanwhile.",
    notesTitle: "News at hh:mm",
    notesBody: "Match notes are coming: each tied to a price on the board, with the time it happened.",
    notesNot: "Not live yet. Nothing here is a feed from someone else.",
    toolsTitle: "The arithmetic, done for you",
    toolsBody: "Implied probability, margin, EV and Kelly: eleven free calculators.",
    toolsLink: "Open the tools",
    boardLink: "See today’s board",
    back: "All articles",
    crumb: "News",
    published: "Published",
    responsible: "18+. Probabilities are estimates and no outcome is certain. If gambling stops being fun, help is at",
  },
  books: {
    tab: "Books · partners",
    title: "Where our prices come from",
    metaStrong: (n: number) => (n === 1 ? "1 book with live prices" : `${n} books with live prices`),
    metaRest: "only these can appear as best price on the board",
    connected: "Live prices connected",
    bestOn: (k: number, n: number) => `best price on ${k} of ${n} lead outcomes today`,
    noBoard: "today’s comparison is unavailable",
    bonusNone: "No bonus shown",
    bonusWhy: "We haven’t verified one. Offers and their terms live on the book’s own site.",
    where: "Where",
    everywhere: "Every country where we show partners",
    onlyIn: (list: string) => `Only in ${list}`,
    localLink: (list: string) => `Local sign-up link in ${list}`,
    goTo: (name: string) => `Go to ${name}`,
    affiliate: "Affiliate link",
    moreTitle: "More books",
    moreSub: "No live feed, so no price shown and never best.",
    sportsbook: "sportsbook · sign-up link only",
    casino: "casino and more · sign-up link only",
    visit: "Visit",
    compareTitle: "Today’s prices, side by side",
    compareSub: "Lead outcome of each match, connected books only, margin included.",
    compareMatch: "Match · outcome",
    compareBest: "Best",
    compareChecked: (t: string) => `Checked ${t}. Prices move; the book’s price at click is what counts.`,
    compareNone: "No connected prices right now. The board shows them as soon as a book has one.",
    respTitle: "If you bet, set your limits first.",
    respBody: "Set a deposit limit at the book before your first bet. Free, confidential help:",
    blockedTitle: "Not available in your region",
    blockedBody: "Partner books aren’t shown from your location. The board and the tools work as usual.",
    blockedBack: "Back to the board",
    fine: "18+. Partner links are commercial affiliates. BetRedge is not a bookmaker and takes no bets.",
  },
  method: {
    tab: "Method · one screen",
    title: "How we read a price",
    metaStrong: "Four ideas",
    metaRest: "every number on BetRedge rests on them",
    more: (what: string) => `More on ${what}`,
    blocks: {
      blend: {
        k: "01",
        title: "The blend 70 / 30",
        body: "Our football estimate is 70% the market’s price and 30% our model. The market leads; the model nudges.",
        detail: "Tennis differs: where a market exists, the sealed number is mostly the market. Every row says which.",
        market: "market",
        model: "model",
      },
      seal: {
        k: "02",
        title: "The seal",
        body: "Before kick-off each estimate is stored with its time. After that it cannot be edited.",
        detail: "The record reads only sealed rows. Wins and losses both stay; nothing is removed after the result.",
        label: "sealed",
      },
      gap: {
        k: "03",
        title: "The gap",
        body: "Gap = our estimate minus the market’s, in points. We show negative gaps too.",
        detail: "Under 1.5 points we write “in line”. A gap is a disagreement, not a promise of profit.",
        market: "market",
        estimate: "estimate",
        gap: "gap",
      },
      not: {
        k: "04",
        title: "What we don’t say",
        body: "No claims of outguessing the market, no profit figures, no picks.",
        line: "A 48% estimate expects to be wrong 52 times in 100.",
        detail: "Analysis, not advice. BetRedge is not a bookmaker and takes no bets. 18+.",
      },
    },
    board: "See today’s board",
    record: "Open the record",
    tools: "Try the tools",
  },
};

export type PagesCopy = typeof EN;

const IT: PagesCopy = {
  pricing: {
    tab: "Piani · due, senza trucchi",
    title: "Free mostra il gap. Pro spiega perché.",
    metaStrong: (monthly: string) => `Pro ${monthly} al mese`,
    metaRest: "Prezzi in USD. L’abbonamento con carta si disdice dal tuo account.",
    freeName: "Free",
    freeLede: "La lettura intera, gratis.",
    proName: "Pro",
    proLede: "Il perché dietro il numero, e più profondità.",
    perMonth: "/ mese",
    perYear: (annual: string) => `· ${annual} l’anno`,
    included: "Incluso",
    pro: "Pro",
    notLive: "Non ancora attivo",
    free: [
      ["La board di oggi", "ogni partita: mercato, stima e gap con segno"],
      ["Il registro", "ogni stima sigillata, vinte e perse"],
      ["Price check e 11 tool", "senza account"],
      ["Watchlist", "le partite che segui, salvate su questo dispositivo"],
    ],
    freeSoon: ["Alert e tracker delle giocate", "previsti in Free; non ancora attivi"],
    proItems: [
      ["Perché il modello non è d’accordo", "ogni fattore dietro la stima: forma, campo, gol"],
      ["Movimento di quota completo", "ogni prezzo salvato dall’apertura del mercato"],
      ["Probabilità live", "la stima si aggiorna durante la partita"],
      ["Probability view", "combina mercati su una partita, modello contro mercato"],
      ["Weekly Model Case", "un esempio di come il modello legge una settimana; non una giocata"],
    ],
    everythingFree: "Tutto quello che c’è in Free",
    freeCta: "Crea un account gratuito",
    proCta: "Passa a Pro",
    railCard: "Carta: abbonamento che si rinnova ogni mese; lo disdici dal tuo account.",
    railCardAnnual: "Annuale con carta: si rinnova ogni 12 mesi.",
    railCrypto: "Crypto: un pagamento per 30 giorni, senza rinnovo.",
    railPaypal: "PayPal: disponibile al checkout.",
    railUsdt: "Bonifico USDT (TRC20): un pagamento, verificato a mano.",
    withdrawal: "Prima di pagare confermi che Pro parte subito, cosa che fa cadere il recesso di 14 giorni.",
    promo: (until: string) => `Offerta di lancio: il primo acquisto è a metà prezzo fino al ${until}. Si applica al checkout.`,
    sameStrong: "Uguale in entrambi:",
    same: "ogni prezzo, stima, gap e l’intero registro. Pro non nasconde nessun numero che Free mostra; aggiunge il perché.",
    anatomyTitle: "Cosa apre Pro su una partita",
    anatomyLede: "I titoli dei fattori li vedono tutti. Il primo è spiegato in Free; gli altri si aprono con Pro.",
    anatomyNever: "Mai mostrato quando stima e mercato coincidono (gap sotto 1,5 punti).",
    fine: "Analisi, non consigli. 18+. BetRedge non è un bookmaker e non accetta scommesse.",
  },
  paywall: {
    lab: "Pro · il perché",
    title: "Scopri perché il modello non è d’accordo",
    lede: "Vedi i fattori che allontanano la nostra stima dal prezzo di mercato su questa partita. Solo analisi, non consigli. 18+.",
    blend: "Nel calcio la stima parte dal mercato (70%); il modello la sposta (30%).",
    open: "Aperto in Free",
    closed: "Si apre con Pro",
    cta: (price: string) => `Vedi Pro · ${price}/mese`,
    cancel: "L’abbonamento con carta si disdice quando vuoi dal tuo account.",
    factorKinds: [
      ["Forma", "I risultati recenti delle due squadre, contati, non pesati a sensazione."],
      ["Campo", "Rendimento in casa e in trasferta in stagione, e quanto distano."],
      ["Gol", "Gol attesi fatti e subiti, dove il dato esiste."],
    ],
    example: "Esempio di impaginazione: solo titoli, nessun dato di partita.",
  },
  news: {
    tab: "News · guide e note partita",
    title: "Cosa muove un prezzo",
    metaStrong: (n: number) => (n === 1 ? "1 articolo" : `${n} articoli`),
    metaRest: "scritti da noi; numeri spiegati, niente pronostici",
    guide: "Guida",
    read: "Leggi",
    minutes: (m: number) => `${m} min di lettura`,
    empty: "Nessun articolo pubblicato per ora.",
    emptySub: "Intanto la board è live.",
    notesTitle: "News alle hh:mm",
    notesBody: "Arrivano le note partita: ognuna legata a un prezzo della board, con l’ora in cui è successa.",
    notesNot: "Non ancora attive. Qui niente è il feed di qualcun altro.",
    toolsTitle: "I conti, fatti per te",
    toolsBody: "Probabilità implicita, margine, EV e Kelly: undici calcolatori gratuiti.",
    toolsLink: "Apri i tool",
    boardLink: "Vedi la board di oggi",
    back: "Tutti gli articoli",
    crumb: "News",
    published: "Pubblicato",
    responsible: "18+. Le probabilità sono stime e nessun esito è certo. Se il gioco smette di divertire, aiuto su",
  },
  books: {
    tab: "Book · partner",
    title: "Da dove vengono i nostri prezzi",
    metaStrong: (n: number) => (n === 1 ? "1 book con prezzi live" : `${n} book con prezzi live`),
    metaRest: "solo questi possono comparire come miglior prezzo sulla board",
    connected: "Prezzi live collegati",
    bestOn: (k: number, n: number) => `miglior prezzo su ${k} di ${n} esiti guida oggi`,
    noBoard: "il confronto di oggi non è disponibile",
    bonusNone: "Nessun bonus mostrato",
    bonusWhy: "Non ne abbiamo verificato uno. Offerte e condizioni stanno sul sito del book.",
    where: "Dove",
    everywhere: "Ogni paese in cui mostriamo i partner",
    onlyIn: (list: string) => `Solo in ${list}`,
    localLink: (list: string) => `Link di registrazione locale in ${list}`,
    goTo: (name: string) => `Vai su ${name}`,
    affiliate: "Link affiliato",
    moreTitle: "Altri book",
    moreSub: "Nessun feed live: niente prezzo e mai «migliore».",
    sportsbook: "sportsbook · solo link di registrazione",
    casino: "casinò e altro · solo link di registrazione",
    visit: "Visita",
    compareTitle: "I prezzi di oggi, fianco a fianco",
    compareSub: "Esito guida di ogni partita, solo book collegati, margine incluso.",
    compareMatch: "Partita · esito",
    compareBest: "Migliore",
    compareChecked: (t: string) => `Controllato alle ${t}. I prezzi si muovono; conta quello del book al clic.`,
    compareNone: "Nessun prezzo collegato ora. La board li mostra appena un book ne ha uno.",
    respTitle: "Se scommetti, fissa prima i tuoi limiti.",
    respBody: "Imposta un limite di deposito sul book prima della prima giocata. Aiuto gratuito e riservato:",
    blockedTitle: "Non disponibile nella tua area",
    blockedBody: "I book partner non sono mostrati dalla tua posizione. Board e tool funzionano come sempre.",
    blockedBack: "Torna alla board",
    fine: "18+. I link ai partner sono affiliazioni commerciali. BetRedge non è un bookmaker e non accetta scommesse.",
  },
  method: {
    tab: "Metodo · una schermata",
    title: "Come leggiamo un prezzo",
    metaStrong: "Quattro idee",
    metaRest: "ogni numero di BetRedge poggia su queste",
    more: (what: string) => `Di più su ${what}`,
    blocks: {
      blend: {
        k: "01",
        title: "Il blend 70 / 30",
        body: "La nostra stima nel calcio è 70% prezzo di mercato e 30% modello. Il mercato guida; il modello sposta.",
        detail: "Nel tennis è diverso: dove c’è un mercato, il numero sigillato è per lo più il mercato. Ogni riga lo dice.",
        market: "mercato",
        model: "modello",
      },
      seal: {
        k: "02",
        title: "Il sigillo",
        body: "Prima del calcio d’inizio ogni stima è salvata con la sua ora. Da lì non si può più modificare.",
        detail: "Il registro legge solo righe sigillate. Vinte e perse restano; dopo il risultato non si toglie nulla.",
        label: "sigillata",
      },
      gap: {
        k: "03",
        title: "Il gap",
        body: "Gap = nostra stima meno quella del mercato, in punti. Mostriamo anche i gap negativi.",
        detail: "Sotto 1,5 punti scriviamo «in linea». Un gap è un disaccordo, non una promessa di guadagno.",
        market: "mercato",
        estimate: "stima",
        gap: "gap",
      },
      not: {
        k: "04",
        title: "Cosa non diciamo",
        body: "Nessuna pretesa di saperne più del mercato, nessuna cifra di guadagno, nessun pronostico.",
        line: "Una stima al 48% si aspetta di sbagliare 52 volte su 100.",
        detail: "Analisi, non consigli. BetRedge non è un bookmaker e non accetta scommesse. 18+.",
      },
    },
    board: "Vedi la board di oggi",
    record: "Apri il registro",
    tools: "Prova i tool",
  },
};

export const PAGES_COPY: Record<PagesLang, PagesCopy> = { en: EN, it: IT };

/** Le lingue che oggi leggono l'inglese su queste pagine (F10 le completa). */
export const PAGES_FALLBACK_TO_EN = ["es", "fr", "de", "pt", "nl", "pl", "tr", "sv", "ru"] as const;

export function pagesCopyFor(lang: string | null | undefined): PagesCopy {
  return (lang ?? "").toLowerCase().startsWith("it") ? IT : EN;
}
